In [ ]:
# Main analytical flow: Comp1 (normal vs target vs severe as group_1 vs group_2 vs group_3) 
import pandas as pd
import numpy as np
import os

In [3]:
os.listdir()

['.ipynb_checkpoints',
 'clinical_first_data.csv',
 'clinical_first_exposed_comp1_data.csv',
 'clinical_first_exposed_comp2_data.csv',
 'clinical_first_exposed_comp3_data.csv',
 'clinical_first_exposed_data.csv',
 'clinical_first_exposed_ordered_data.csv',
 'clinical_first_ordered_data.csv',
 'clinical_last_data.csv',
 'clinical_last_exposed_comp1_data.csv',
 'clinical_last_exposed_comp2_data.csv',
 'clinical_last_exposed_comp3_data.csv',
 'clinical_last_exposed_data.csv',
 'clinical_last_exposed_ordered_data.csv',
 'clinical_last_group_data.csv',
 'clinical_last_ordered_data.csv',
 'ETC',
 'example.pdf',
 'metabolome_first_mofa_data.csv',
 'metabolome_first_mofa_norm_data.csv',
 'metabolome_first_norm_data.csv',
 'metabolome_first_norm_final_data.csv',
 'metabolome_first_norm_ordered_data.csv',
 'metabolome_last_mofa_data.csv',
 'metabolome_last_mofa_norm_data.csv',
 'metabolome_last_norm_data.csv',
 'metabolome_last_norm_final_data.csv',
 'metabolome_last_norm_ordered_data.csv',
 'metabolome_quantile_first_data.csv',
 'methylome_first_mofa_data.csv',
 'methylome_first_mofa_norm_data.csv',
 'methylome_first_norm_data.csv',
 'methylome_first_norm_data_t.csv',
 'methylome_first_norm_final_data.csv',
 'methylome_first_norm_ordered_data.csv',
 'methylome_last_mofa_data.csv',
 'methylome_last_mofa_norm_data.csv',
 'methylome_last_norm_data.csv',
 'methylome_last_norm_data_t.csv',
 'methylome_last_norm_final_data.csv',
 'methylome_last_norm_ordered_data.csv',
 'mofa_factor9_metabolome_corr-heatmap_first_comp2.pdf',
 'mofa_factor9_metabolome_normal_corr-heatmap_first_comp2.pdf',
 'mofa_factor9_metabolome_target_corr-heatmap_first_comp2.pdf',
 'mofa_factor9_methylome_corr-heatmap_first_comp2.pdf',
 'mofa_factor9_methylome_normal_corr-heatmap_first_comp2.pdf',
 'mofa_factor9_methylome_target_corr-heatmap_first_comp2.pdf',
 'multiome_comp3.hdf5',
 'multiome_first_comp1.hdf5',
 'multiome_first_comp1_data.csv',
 'multiome_first_comp2.hdf5',
 'multiome_first_comp2_data.csv',
 'multiome_first_comp3.hdf5',
 'multiome_first_comp3_data.csv',
 'multiome_first_mofa-data.csv',
 'multiome_last_comp1_data.csv',
 'multiome_last_comp2_data.csv',
 'multiome_last_comp3_data.csv',
 'multiome_last_mofa-data.csv',
 'Multiomics_last_data.xlsm',
 'omics_input_changer.ipynb',
 'protein-gene_mapping.csv',
 'proteome_first_impute-norm_data.csv',
 'proteome_first_impute-norm_final_data.csv',
 'proteome_first_impute-norm_ordered_data.csv',
 'proteome_first_mofa_data.csv',
 'proteome_first_mofa_norm_data.csv',
 'proteome_last_impute-norm_data.csv',
 'proteome_last_impute-norm_final_data.csv',
 'proteome_last_impute-norm_ordered_data.csv',
 'proteome_last_mofa_data.csv',
 'proteome_last_mofa_impute-norm_data.csv',
 'proteome_quantile_first_data.csv',
 'Rplot.png',
 'SampleInfo.csv',
 'SampleInfo_raw.csv',
 'single-omics',
 'transcriptome_last_mofa_data.csv',
 'transcriptome_last_mofa_norm_data.csv',
 'transcriptome_last_norm_data.csv',
 'transcriptome_last_norm_data_t.csv',
 'transcriptome_last_norm_final_data.csv',
 'transcriptome_last_norm_ordered_data.csv']

In [13]:
df = pd.read_csv("metabolome_last_norm_ordered_data.csv")

df

,Label,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,met1,19.52402565,20.42635267,20.07477919,20.46286603,20.29931188,20.47283319,20.53523253,20.36082516,19.80269473,...,20.32523522,21.05363313,20.02527303,19.92535574,20.63277088,20.50608805,19.86861192,20.38616431,19.89437358,20.86997411
2,met2,14.41925066,14.00234889,12.21314616,12.54784449,12.44631352,15.04851052,14.88168857,13.60516599,13.61071711,...,14.09677782,13.90714663,15.05249085,12.23296802,13.83801935,12.22173106,12.53719855,15.22928617,13.55163342,15.28788878
3,met4,24.6410808,23.09800664,19.33096187,19.75470734,24.81611853,23.58174866,23.64401655,24.15330838,24.07811657,...,24.07834203,23.8975134,23.51993173,19.63338073,19.48288683,19.29880884,19.55257569,24.00644996,23.98613398,23.31814757
4,met5,17.90787554,17.097947,17.59731055,18.60262331,17.19242927,17.34438479,17.22068068,17.74156894,18.49192886,...,18.66824451,17.86320281,16.75672585,13.50933295,17.83476698,17.20860336,13.66023336,18.12131395,17.69716402,17.58415752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,met1140,19.27422443,16.98132557,18.80398348,18.63205365,17.57791688,18.93323956,17.63204026,18.85803124,17.52552065,...,17.86117946,18.42889685,17.56498885,16.82059345,18.49503384,17.32476136,16.19355829,19.73382576,18.86472298,16.82116718
749,met1141,21.10276279,19.81252361,21.07956038,20.61967454,20.93195179,20.88114198,19.83303844,19.64541154,20.07991729,...,20.73274322,20.59832175,20.34390816,19.52961809,20.58270831,20.15027397,20.06779972,20.61303671,20.59002255,20.72482181
750,met1142,17.1940344,15.92273052,17.31832514,16.91812215,16.05411673,16.96744344,16.77386528,16.57210526,16.30090278,...,17.0834136,17.15870455,16.49109103,15.88599625,16.90127408,16.4288137,15.72808508,16.74528443,16.94344486,16.23427747
751,met1143,18.73027254,16.9995465,18.37776507,18.59367994,17.8932215,18.77180461,18.06141842,18.78452327,18.04450206,...,18.30194834,18.09128578,17.71017679,16.9879062,18.32867823,16.71687707,17.08663089,19.20471717,18.44315219,17.51812164
752,met1144,15.55415223,14.35640899,16.43775004,15.65737182,14.86400675,15.49650895,15.54422085,15.86203093,16.0515584,...,15.37050024,15.84197411,15.66074234,15.82465559,15.64071059,15.27348029,14.06305132,14.56915218,15.78743826,15.9456557

In [15]:
df = pd.DataFrame(df)
df.shape

(753, 91)

In [17]:
df.columns

Index(['Label', 'A08_045_C13a', 'A08_056_C13a', 'S09_053_C13a', 'A10_020_C13a',
       'S09_104_C13a', 'A09_126_C13a', 'S09_072_C13a', 'S09_122_C13a',
       'S08_043_C13a', 'A09_072_C13a', 'A10_006_C', 'A10_072_C', 'A10_050_C',
       'A10_075_C', 'A07_006_C', 'A10_016_C', 'A10_062_C', 'S07_015_C',
       'S08_024_C', 'A09_003_C', 'GA694', 'GA818', 'GA825', 'GA828', 'GA845',
       'GA846', 'GA855', 'GA859', 'GA895', 'GA896', 'GA901', 'NA047', 'NA048',
       'NA050', 'NA160', 'NA161', 'NA291', 'NA344', 'NA390', 'NA423', 'GA753',
       'GA781', 'GA810', 'GA832', 'GA854', 'GA877', 'GA886', 'GA894', 'GA928',
       'NA040', 'NA055', 'NA059', 'NA093', 'NA094', 'NA147', 'NA151', 'NA196',
       'NA247', 'NA268', 'NA279', 'NA391', 'GA730', 'GA749', 'GA862', 'GA865',
       'GA878', 'GA881', 'NA033', 'NA039', 'NA053', 'NA063', 'NA102', 'NA109',
       'NA125', 'NA129', 'NA169', 'NA182', 'NA237', 'NA250', 'NA288', 'GA733',
       'GA738', 'GA960', 'NA074', 'NA084', 'NA092', 'NA132', 'NA225', 'NA327',
       'NA452'],
      dtype='object')

In [19]:
df.loc[:, 'Label']

0        Group
1         met1
2         met2
3         met4
4         met5
        ...
748    met1140
749    met1141
750    met1142
751    met1143
752    met1144
Name: Label, Length: 753, dtype: object

In [21]:
group_info = df.iloc[0]

In [23]:
df = df[1:]

In [25]:
df.index = df.loc[:, 'Label']

In [27]:
df = df.drop('Label', axis=1)

In [29]:
df

,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,A09_072_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
Label,,,,,,,,,,,,,,,,,,,,,
met1,19.52402565,20.42635267,20.07477919,20.46286603,20.29931188,20.47283319,20.53523253,20.36082516,19.80269473,20.45208167,...,20.32523522,21.05363313,20.02527303,19.92535574,20.63277088,20.50608805,19.86861192,20.38616431,19.89437358,20.86997411
met2,14.41925066,14.00234889,12.21314616,12.54784449,12.44631352,15.04851052,14.88168857,13.60516599,13.61071711,14.57208078,...,14.09677782,13.90714663,15.05249085,12.23296802,13.83801935,12.22173106,12.53719855,15.22928617,13.55163342,15.28788878
met4,24.6410808,23.09800664,19.33096187,19.75470734,24.81611853,23.58174866,23.64401655,24.15330838,24.07811657,24.38097527,...,24.07834203,23.8975134,23.51993173,19.63338073,19.48288683,19.29880884,19.55257569,24.00644996,23.98613398,23.31814757
met5,17.90787554,17.097947,17.59731055,18.60262331,17.19242927,17.34438479,17.22068068,17.74156894,18.49192886,17.39347838,...,18.66824451,17.86320281,16.75672585,13.50933295,17.83476698,17.20860336,13.66023336,18.12131395,17.69716402,17.58415752
met6,17.90787554,17.097947,17.59731055,18.60262331,16.10562045,17.34438479,17.22068068,17.74156894,18.49192886,17.39347838,...,18.66824451,17.86320281,16.75672585,17.24897359,17.83476698,17.20860336,14.6055674,18.12131395,17.69716402,17.58415752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
met1140,19.27422443,16.98132557,18.80398348,18.63205365,17.57791688,18.93323956,17.63204026,18.85803124,17.52552065,17.60158471,...,17.86117946,18.42889685,17.56498885,16.82059345,18.49503384,17.32476136,16.19355829,19.73382576,18.86472298,16.82116718
met1141,21.10276279,19.81252361,21.07956038,20.61967454,20.93195179,20.88114198,19.83303844,19.64541154,20.07991729,20.40403524,...,20.73274322,20.59832175,20.34390816,19.52961809,20.58270831,20.15027397,20.06779972,20.61303671,20.59002255,20.72482181
met1142,17.1940344,15.92273052,17.31832514,16.91812215,16.05411673,16.96744344,16.77386528,16.57210526,16.30090278,16.70414011,...,17.0834136,17.15870455,16.49109103,15.88599625,16.90127408,16.4288137,15.72808508,16.74528443,16.94344486,16.23427747
met1143,18.73027254,16.9995465,18.37776507,18.59367994,17.8932215,18.77180461,18.06141842,18.78452327,18.04450206,18.10966867,...,18.30194834,18.09128578,17.71017679,16.9879062,18.32867823,16.71687707,17.08663089,19.20471717,18.44315219,17.51812164
met1144,15.55415223,14.35640899,16.43775004,15.65737182,14.86400675,15.49650895,15.54422085,15.86203093,16.0515584,15.97260016,...,15.37050024,15.84197411,15.66074234,15.82465559,15.64071059,15.27348029,14.06305132,14.56915218,15.78743826,15.9456557

In [31]:
group_info = group_info[1:]

In [33]:
group_info

A08_045_C13a    group_1
A08_056_C13a    group_1
S09_053_C13a    group_1
A10_020_C13a    group_1
S09_104_C13a    group_1
                 ...
NA092           group_5
NA132           group_5
NA225           group_5
NA327           group_5
NA452           group_5
Name: 0, Length: 90, dtype: object

In [35]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [36]:
sample_list

['A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',

In [39]:
print(group_list)

['group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', 'group_1', '

In [41]:
feature_list

['met1',
 'met2',
 'met4',
 'met5',
 'met6',
 'met7',
 'met14',
 'met15',
 'met16',
 'met19',
 'met20',
 'met22',
 'met25',
 'met26',
 'met27',
 'met28',
 'met29',
 'met30',
 'met31',
 'met32',
 'met33',
 'met34',
 'met35',
 'met37',
 'met38',
 'met39',
 'met40',
 'met41',
 'met43',
 'met44',
 'met45',
 'met46',
 'met47',
 'met48',
 'met54',
 'met56',
 'met57',
 'met58',
 'met60',
 'met64',
 'met65',
 'met69',
 'met70',
 'met71',
 'met72',
 'met73',
 'met74',
 'met77',
 'met81',
 'met82',
 'met85',
 'met86',
 'met90',
 'met91',
 'met92',
 'met93',
 'met94',
 'met95',
 'met96',
 'met97',
 'met101',
 'met102',
 'met103',
 'met104',
 'met105',
 'met108',
 'met110',
 'met111',
 'met114',
 'met115',
 'met116',
 'met117',
 'met118',
 'met119',
 'met120',
 'met121',
 'met123',
 'met124',
 'met125',
 'met126',
 'met127',
 'met131',
 'met132',
 'met133',
 'met134',
 'met136',
 'met137',
 'met138',
 'met140',
 'met141',
 'met142',
 'met146',
 'met148',
 'met149',
 'met150',
 'met151',
 'met152',
 'met153',
 'met154',
 'met158',
 'met159',
 'met160',
 'met164',
 'met168',
 'met169',
 'met171',
 'met173',
 'met174',
 'met177',
 'met181',
 'met182',
 'met184',
 'met185',
 'met186',
 'met187',
 'met188',
 'met190',
 'met191',
 'met192',
 'met193',
 'met195',
 'met196',
 'met197',
 'met198',
 'met199',
 'met203',
 'met207',
 'met209',
 'met210',
 'met211',
 'met212',
 'met214',
 'met215',
 'met217',
 'met218',
 'met219',
 'met220',
 'met221',
 'met222',
 'met223',
 'met226',
 'met227',
 'met228',
 'met229',
 'met231',
 'met232',
 'met233',
 'met234',
 'met235',
 'met236',
 'met238',
 'met239',
 'met240',
 'met241',
 'met242',
 'met243',
 'met244',
 'met246',
 'met247',
 'met248',
 'met249',
 'met251',
 'met252',
 'met253',
 'met254',
 'met255',
 'met256',
 'met257',
 'met259',
 'met260',
 'met261',
 'met264',
 'met265',
 'met266',
 'met267',
 'met270',
 'met271',
 'met272',
 'met273',
 'met277',
 'met278',
 'met280',
 'met281',
 'met282',
 'met284',
 'met285',
 'met286',
 'met288',
 'met289',
 'met291',
 'met292',
 'met294',
 'met295',
 'met296',
 'met297',
 'met298',
 'met299',
 'met301',
 'met302',
 'met303',
 'met306',
 'met308',
 'met309',
 'met311',
 'met312',
 'met313',
 'met314',
 'met316',
 'met317',
 'met318',
 'met319',
 'met320',
 'met321',
 'met322',
 'met323',
 'met324',
 'met326',
 'met327',
 'met328',
 'met329',
 'met332',
 'met333',
 'met334',
 'met336',
 'met339',
 'met341',
 'met342',
 'met344',
 'met345',
 'met346',
 'met347',
 'met348',
 'met349',
 'met350',
 'met351',
 'met352',
 'met354',
 'met355',
 'met357',
 'met358',
 'met360',
 'met361',
 'met362',
 'met363',
 'met364',
 'met365',
 'met366',
 'met367',
 'met368',
 'met371',
 'met372',
 'met374',
 'met375',
 'met376',
 'met377',
 'met381',
 'met383',
 'met384',
 'met390',
 'met393',
 'met394',
 'met395',
 'met396',
 'met397',
 'met399',
 'met400',
 'met402',
 'met403',
 'met404',
 'met405',
 'met406',
 'met408',
 'met409',
 'met410',
 'met415',
 'met416',
 'met417',
 'met418',
 'met421',
 'met424',
 'met426',
 'met427',
 'met430',
 'met431',
 'met432',
 'met433',
 'met434',
 'met436',
 'met437',
 'met438',
 'met439',
 'met440',
 'met441',
 'met443',
 'met444',
 'met447',
 'met449',
 'met450',
 'met451',
 'met452',
 'met453',
 'met455',
 'met457',
 'met459',
 'met460',
 'met461',
 'met462',
 'met467',
 'met469',
 'met470',
 'met471',
 'met473',
 'met474',
 'met476',
 'met477',
 'met478',
 'met479',
 'met482',
 'met485',
 'met486',
 'met487',
 'met488',
 'met489',
 'met490',
 'met491',
 'met492',
 'met493',
 'met496',
 'met497',
 'met499',
 'met501',
 'met502',
 'met504',
 'met506',
 'met507',
 'met508',
 'met509',
 'met511',
 'met512',
 'met513',
 'met514',
 'met515',
 'met516',
 'met519',
 'met520',
 'met521',
 'met522',
 'met523',
 'met526',
 'met527',
 'met528',
 'met530',
 'met531',
 'met533',
 'met534',
 'met536',
 'met537',
 'met540',
 'met541',
 'met542',
 'met543',
 'met545',
 'met546',
 'met548',
 'met549',
 'met554',
 'met559',
 'met560',
 'met566',
 'met567',
 'met569',
 'met570',
 'met576',
 'met578',
 'met580',
 'met581',
 'met582',
 'met585',
 'met589',
 'met593',
 'met594',
 'met595',
 'met596',
 'met597',
 'met600',
 'met601',
 'met602',
 'met604',
 'met606',
 'met607',
 'met608',
 'met609',
 'met610',
 'met611',
 'met612',
 'met615',
 'met616',
 'met617',
 'met618',
 'met619',
 'met620',
 'met621',
 'met622',
 'met623',
 'met625',
 'met627',
 'met628',
 'met629',
 'met630',
 'met631',
 'met632',
 'met633',
 'met634',
 'met635',
 'met636',
 'met637',
 'met638',
 'met639',
 'met640',
 'met642',
 'met643',
 'met644',
 'met646',
 'met647',
 'met648',
 'met649',
 'met651',
 'met652',
 'met653',
 'met654',
 'met655',
 'met656',
 'met657',
 'met658',
 'met661',
 'met662',
 'met664',
 'met665',
 'met667',
 'met668',
 'met669',
 'met670',
 'met674',
 'met675',
 'met676',
 'met677',
 'met680',
 'met681',
 'met683',
 'met684',
 'met686',
 'met687',
 'met688',
 'met689',
 'met690',
 'met691',
 'met693',
 'met695',
 'met697',
 'met700',
 'met701',
 'met706',
 'met714',
 'met715',
 'met716',
 'met717',
 'met718',
 'met719',
 'met720',
 'met721',
 'met722',
 'met723',
 'met724',
 'met725',
 'met726',
 'met727',
 'met728',
 'met729',
 'met730',
 'met731',
 'met732',
 'met733',
 'met734',
 'met735',
 'met736',
 'met737',
 'met738',
 'met739',
 'met740',
 'met741',
 'met742',
 'met743',
 'met744',
 'met745',
 'met746',
 'met747',
 'met748',
 'met749',
 'met750',
 'met751',
 'met754',
 'met756',
 'met757',
 'met758',
 'met759',
 'met760',
 'met762',
 'met763',
 'met764',
 'met765',
 'met766',
 'met767',
 'met773',
 'met774',
 'met775',
 'met777',
 'met778',
 'met779',
 'met780',
 'met781',
 'met782',
 'met783',
 'met784',
 'met785',
 'met788',
 'met789',
 'met790',
 'met791',
 'met792',
 'met793',
 'met794',
 'met795',
 'met796',
 'met797',
 'met798',
 'met799',
 'met800',
 'met802',
 'met803',
 'met804',
 'met805',
 'met807',
 'met810',
 'met811',
 'met812',
 'met813',
 'met815',
 'met817',
 'met818',
 'met819',
 'met820',
 'met821',
 'met825',
 'met826',
 'met827',
 'met828',
 'met830',
 'met833',
 'met837',
 'met840',
 'met844',
 'met845',
 'met847',
 'met850',
 'met853',
 'met857',
 'met858',
 'met859',
 'met860',
 'met864',
 'met865',
 'met866',
 'met867',
 'met870',
 'met871',
 'met872',
 'met873',
 'met874',
 'met877',
 'met879',
 'met884',
 'met886',
 'met887',
 'met888',
 'met889',
 'met890',
 'met895',
 'met896',
 'met898',
 'met899',
 'met900',
 'met903',
 'met904',
 'met906',
 'met911',
 'met914',
 'met915',
 'met916',
 'met917',
 'met918',
 'met920',
 'met921',
 'met924',
 'met925',
 'met926',
 'met932',
 'met933',
 'met934',
 'met935',
 'met936',
 'met937',
 'met940',
 'met942',
 'met943',
 'met945',
 'met947',
 'met948',
 'met951',
 'met952',
 'met953',
 'met954',
 'met957',
 'met961',
 'met962',
 'met963',
 'met964',
 'met965',
 'met966',
 'met967',
 'met968',
 'met969',
 'met970',
 'met972',
 'met974',
 'met975',
 'met976',
 'met979',
 'met980',
 'met981',
 'met982',
 'met983',
 'met984',
 'met985',
 'met988',
 'met989',
 'met990',
 'met992',
 'met994',
 'met995',
 'met996',
 'met997',
 'met998',
 'met1000',
 'met1001',
 'met1002',
 'met1003',
 'met1005',
 'met1006',
 'met1008',
 'met1011',
 'met1012',
 'met1014',
 'met1015',
 'met1016',
 'met1020',
 'met1024',
 'met1025',
 'met1026',
 'met1027',
 'met1028',
 'met1029',
 'met1030',
 'met1032',
 'met1033',
 'met1034',
 'met1035',
 'met1036',
 'met1037',
 'met1038',
 'met1040',
 'met1042',
 'met1044',
 'met1045',
 'met1046',
 'met1047',
 'met1048',
 'met1050',
 'met1052',
 'met1053',
 'met1056',
 'met1058',
 'met1059',
 'met1060',
 'met1061',
 'met1062',
 'met1066',
 'met1068',
 'met1069',
 'met1070',
 'met1071',
 'met1073',
 'met1074',
 'met1075',
 'met1076',
 'met1077',
 'met1079',
 'met1081',
 'met1082',
 'met1083',
 'met1084',
 'met1086',
 'met1087',
 'met1088',
 'met1089',
 'met1090',
 'met1091',
 'met1092',
 'met1093',
 'met1094',
 'met1096',
 'met1097',
 'met1099',
 'met1100',
 'met1101',
 'met1102',
 'met1103',
 'met1104',
 'met1105',
 'met1106',
 'met1107',
 'met1108',
 'met1111',
 'met1112',
 'met1113',
 'met1114',
 'met1117',
 'met1118',
 'met1121',
 'met1127',
 'met1130',
 'met1131',
 'met1132',
 'met1134',
 'met1136',
 'met1137',
 'met1138',
 'met1139',
 'met1140',
 'met1141',
 'met1142',
 'met1143',
 'met1144',
 'met1',
 'met2',
 'met4',
 'met5',
 'met6',
 'met7',
 'met14',
 'met15',
 'met16',
 'met19',
 'met20',
 'met22',
 'met25',
 'met26',
 'met27',
 'met28',
 'met29',
 'met30',
 'met31',
 'met32',
 'met33',
 'met34',
 'met35',
 'met37',
 'met38',
 'met39',
 'met40',
 'met41',
 'met43',
 'met44',
 'met45',
 'met46',
 'met47',
 'met48',
 'met54',
 'met56',
 'met57',
 'met58',
 'met60',
 'met64',
 'met65',
 'met69',
 'met70',
 'met71',
 'met72',
 'met73',
 'met74',
 'met77',
 'met81',
 'met82',
 'met85',
 'met86',
 'met90',
 'met91',
 'met92',
 'met93',
 'met94',
 'met95',
 'met96',
 'met97',
 'met101',
 'met102',
 'met103',
 'met104',
 'met105',
 'met108',
 'met110',
 'met111',
 'met114',
 'met115',
 'met116',
 'met117',
 'met118',
 'met119',
 'met120',
 'met121',
 'met123',
 'met124',
 'met125',
 'met126',
 'met127',
 'met131',
 'met132',
 'met133',
 'met134',
 'met136',
 'met137',
 'met138',
 'met140',
 'met141',
 'met142',
 'met146',
 'met148',
 'met149',
 'met150',
 'met151',
 'met152',
 'met153',
 'met154',
 'met158',
 'met159',
 'met160',
 'met164',
 'met168',
 'met169',
 'met171',
 'met173',
 'met174',
 'met177',
 'met181',
 'met182',
 'met184',
 'met185',
 'met186',
 'met187',
 'met188',
 'met190',
 'met191',
 'met192',
 'met193',
 'met195',
 'met196',
 'met197',
 'met198',
 'met199',
 'met203',
 'met207',
 'met209',
 'met210',
 'met211',
 'met212',
 'met214',
 'met215',
 'met217',
 'met218',
 'met219',
 'met220',
 'met221',
 'met222',
 'met223',
 'met226',
 'met227',
 'met228',
 'met229',
 'met231',
 'met232',
 'met233',
 'met234',
 'met235',
 'met236',
 'met238',
 'met239',
 'met240',
 'met241',
 'met242',
 'met243',
 'met244',
 'met246',
 'met247',
 'met248',
 'met249',
 'met251',
 'met252',
 'met253',
 'met254',
 'met255',
 'met256',
 'met257',
 'met259',
 'met260',
 'met261',
 'met264',
 'met265',
 'met266',
 'met267',
 'met270',
 'met271',
 'met272',
 'met273',
 'met277',
 'met278',
 'met280',
 'met281',
 'met282',
 'met284',
 'met285',
 'met286',
 'met288',
 'met289',
 'met291',
 'met292',
 'met294',
 'met295',
 'met296',
 'met297',
 'met298',
 'met299',
 'met301',
 'met302',
 'met303',
 'met306',
 'met308',
 'met309',
 'met311',
 'met312',
 'met313',
 'met314',
 'met316',
 'met317',
 'met318',
 'met319',
 'met320',
 'met321',
 'met322',
 'met323',
 'met324',
 'met326',
 'met327',
 'met328',
 'met329',
 'met332',
 'met333',
 'met334',
 'met336',
 'met339',
 'met341',
 'met342',
 'met344',
 'met345',
 'met346',
 'met347',
 'met348',
 'met349',
 'met350',
 'met351',
 'met352',
 'met354',
 'met355',
 'met357',
 'met358',
 'met360',
 'met361',
 'met362',
 'met363',
 'met364',
 'met365',
 'met366',
 'met367',
 ...]

In [43]:
value_list

['19.52402565',
 '14.41925066',
 '24.6410808',
 '17.90787554',
 '17.90787554',
 '19.93254479',
 '16.85805549',
 '22.56970112',
 '21.07268811',
 '20.96727709',
 '18.20338325',
 '18.99192123',
 '17.95553631',
 '19.82281361',
 '14.96003079',
 '25.14616211',
 '18.1891543',
 '20.737867',
 '20.73760503',
 '20.96515597',
 '16.37856614',
 '17.04844503',
 '19.7764474',
 '16.70038348',
 '14.5698038',
 '14.56609965',
 '20.4480059',
 '17.3111923',
 '19.84981519',
 '16.80820141',
 '20.48973274',
 '23.60159982',
 '18.89132209',
 '20.0557467',
 '17.94835256',
 '19.84051549',
 '18.51494063',
 '16.33470331',
 '19.45411819',
 '17.4969631',
 '16.76395767',
 '15.49016578',
 '20.56349316',
 '18.06150372',
 '18.6136469',
 '17.63826333',
 '21.96618057',
 '17.40592348',
 '21.41101353',
 '21.97625647',
 '23.56194912',
 '23.19616174',
 '15.77341243',
 '15.1725008',
 '18.49035159',
 '19.34269571',
 '20.23044584',
 '21.35750738',
 '22.81113456',
 '14.27330084',
 '17.74232795',
 '18.46521705',
 '19.48992567',
 '20.71721158',
 '20.71721158',
 '14.16868544',
 '15.9154958',
 '19.5687171',
 '20.36014481',
 '19.06684731',
 '18.61556348',
 '17.16589798',
 '17.69131386',
 '17.74598396',
 '18.38171295',
 '19.26810092',
 '16.00783659',
 '21.03243171',
 '20.2982625',
 '23.73866844',
 '18.64958788',
 '17.33891007',
 '19.25692117',
 '19.38909014',
 '17.97110805',
 '18.41238728',
 '18.29764626',
 '14.1623779',
 '16.35098301',
 '14.57079655',
 '19.05374326',
 '16.73274338',
 '15.98284566',
 '14.65944605',
 '21.68930924',
 '20.82497614',
 '23.70250825',
 '23.63094607',
 '18.44900436',
 '16.94180689',
 '17.86437424',
 '25.41051244',
 '20.08608367',
 '16.06950851',
 '21.68706461',
 '21.60375803',
 '18.42987404',
 '17.68536623',
 '21.08819658',
 '16.60755666',
 '20.16728818',
 '17.91976093',
 '16.29386111',
 '16.31842342',
 '19.94328848',
 '13.96685299',
 '19.06740798',
 '15.74332188',
 '17.57798911',
 '19.60544312',
 '17.94899186',
 '18.07758644',
 '19.53216608',
 '15.37482072',
 '13.8304132',
 '17.81186248',
 '13.29337673',
 '15.84291359',
 '17.07943988',
 '17.87380879',
 '18.1085967',
 '20.17610932',
 '19.32342631',
 '18.45879176',
 '18.45879176',
 '19.31188719',
 '19.81833965',
 '18.03990114',
 '17.70319512',
 '25.23803393',
 '18.77289238',
 '15.21281101',
 '22.95473501',
 '20.82690602',
 '17.36404142',
 '17.23826833',
 '14.32112381',
 '12.88930876',
 '18.04370495',
 '18.29475926',
 '16.40878092',
 '17.21318122',
 '16.3093685',
 '21.42047908',
 '17.34023786',
 '17.34023786',
 '20.27747164',
 '14.82587557',
 '16.20714567',
 '16.27006796',
 '18.9563507',
 '16.95915859',
 '16.31333368',
 '19.83950346',
 '15.15999838',
 '17.80795866',
 '15.21903637',
 '13.28807778',
 '14.17284255',
 '17.51900826',
 '17.32477078',
 '16.51004749',
 '18.13472004',
 '14.14407812',
 '18.54342138',
 '29.19793644',
 '19.35737585',
 '22.9962761',
 '18.94525778',
 '16.91930026',
 '15.12111296',
 '19.50371709',
 '26.08954376',
 '18.27267507',
 '15.34204992',
 '18.56898164',
 '17.64801609',
 '14.81813192',
 '19.95463559',
 '20.95033516',
 '13.94455232',
 '23.10645058',
 '18.86459398',
 '18.56487521',
 '20.13895989',
 '15.79184075',
 '15.71825797',
 '18.04949824',
 '14.2942689',
 '19.37253676',
 '12.7592848',
 '18.24911168',
 '19.58903023',
 '18.73120937',
 '16.47332707',
 '20.46601565',
 '19.64928435',
 '17.37046904',
 '14.80973884',
 '20.28215263',
 '17.75181863',
 '20.43441393',
 '15.72293313',
 '25.18104029',
 '18.10399354',
 '21.53362021',
 '21.8965221',
 '19.1613392',
 '18.88601649',
 '20.34612265',
 '19.80799299',
 '16.81994191',
 '19.79573647',
 '17.44552466',
 '22.22822977',
 '23.80818223',
 '26.27759966',
 '19.64946438',
 '12.76294742',
 '17.36470356',
 '17.45650759',
 '22.92495516',
 '25.08010903',
 '22.36446017',
 '20.54784769',
 '24.19747386',
 '24.77045424',
 '18.9740907',
 '12.70638573',
 '22.31764405',
 '21.37233028',
 '23.43581621',
 '17.84853317',
 '18.78433641',
 '23.51691687',
 '21.70113297',
 '21.3693722',
 '24.10424732',
 '19.83808438',
 '19.19191278',
 '17.06110145',
 '20.46765358',
 '19.26005415',
 '16.01401688',
 '16.79379282',
 '18.71841367',
 '16.42098839',
 '17.58235343',
 '19.05682197',
 '22.08691531',
 '21.8723257',
 '19.27815524',
 '20.24081427',
 '20.51542831',
 '20.06309837',
 '17.56754394',
 '17.31400556',
 '14.91391266',
 '24.46734346',
 '17.69355457',
 '18.07396656',
 '17.22042865',
 '16.40017507',
 '18.55070181',
 '17.87648687',
 '16.20086437',
 '21.71284475',
 '14.9264341',
 '17.699767',
 '11.14243842',
 '19.26439781',
 '16.4578682',
 '18.69995126',
 '11.67421508',
 '16.1550708',
 '19.76153148',
 '18.21586408',
 '11.33794811',
 '15.40323262',
 '16.84314393',
 '13.41222999',
 '15.9251053',
 '14.2615443',
 '15.58023963',
 '21.07151416',
 '17.56893449',
 '17.39830572',
 '17.15258901',
 '14.6736339',
 '18.62759006',
 '14.10276826',
 '16.60502517',
 '15.85453209',
 '20.89148107',
 '16.73730667',
 '19.41687996',
 '12.80176715',
 '17.46735342',
 '15.95254132',
 '17.16244073',
 '14.92511173',
 '19.53143108',
 '12.21682941',
 '15.55571755',
 '12.06161147',
 '14.90893844',
 '19.55769329',
 '16.03270157',
 '8.7174115',
 '16.52287154',
 '11.67323814',
 '10.98532124',
 '21.1820329',
 '17.69508636',
 '15.63488483',
 '10.42916514',
 '19.50095073',
 '16.41563531',
 '14.86961984',
 '20.07881024',
 '17.46955501',
 '10.46148057',
 '13.08708752',
 '16.89946119',
 '11.85051941',
 '11.99173367',
 '15.47828794',
 '14.91543022',
 '16.44085573',
 '11.40385399',
 '18.53166009',
 '15.46769003',
 '17.39558216',
 '16.4286865',
 '16.29253671',
 '19.37556092',
 '16.74470916',
 '18.2531653',
 '16.53023128',
 '13.92725362',
 '16.14496202',
 '18.36862068',
 '12.26260672',
 '13.55387633',
 '12.15875557',
 '11.75201845',
 '21.35593648',
 '15.89968199',
 '18.2402395',
 '16.75079386',
 '15.48749026',
 '11.33128706',
 '18.56411037',
 '10.99029266',
 '11.12569677',
 '16.60337935',
 '13.40329077',
 '15.49662285',
 '18.0053424',
 '12.64308375',
 '16.35898918',
 '16.19478289',
 '16.56813737',
 '10.52531029',
 '13.35050498',
 '14.30430371',
 '16.44602383',
 '11.12045362',
 '16.30244309',
 '12.69345482',
 '12.97735129',
 '14.82965729',
 '14.81628115',
 '12.73663544',
 '17.95728415',
 '15.77847334',
 '15.13026083',
 '15.64636138',
 '11.75244757',
 '18.68596401',
 '15.92332173',
 '16.98414905',
 '12.56382596',
 '15.90342377',
 '18.36429734',
 '16.69782437',
 '17.25070439',
 '20.06371602',
 '13.67995107',
 '17.36596417',
 '16.5126795',
 '14.03427911',
 '19.74620348',
 '18.09639153',
 '12.36610942',
 '17.40631426',
 '18.86959313',
 '17.05916368',
 '20.82780354',
 '12.63717637',
 '14.67753873',
 '16.78406652',
 '16.02903001',
 '16.45552904',
 '21.31353902',
 '20.2361939',
 '21.5943761',
 '11.40150142',
 '11.99261451',
 '15.3665343',
 '13.1334868',
 '16.49737313',
 '15.14738279',
 '19.01519571',
 '16.74094837',
 '16.23767065',
 '20.73577887',
 '18.2366004',
 '16.16082914',
 '19.63756317',
 '16.13629843',
 '13.88135244',
 '20.76821491',
 '18.6007138',
 '14.28804392',
 '18.29517497',
 '15.63903452',
 '14.12367875',
 '16.26716083',
 '17.91155057',
 '17.39308482',
 '15.79683228',
 '17.13357623',
 '15.91047473',
 '15.24389573',
 '14.71882172',
 '17.75580042',
 '17.25996659',
 '14.2757709',
 '17.16031393',
 '14.86155717',
 '22.1906125',
 '15.58771775',
 '14.7479709',
 '16.79342909',
 '15.99919477',
 '17.53178327',
 '16.0858056',
 '15.95177465',
 '17.37559693',
 '14.76070194',
 '15.31149189',
 '15.16633865',
 '16.96412844',
 '18.04571236',
 '15.42284939',
 '17.26520255',
 '17.43741448',
 '18.20466895',
 '17.11299852',
 '15.57310958',
 '16.48707005',
 '15.3070637',
 '16.34265541',
 '19.58661408',
 '13.47141435',
 '18.76549485',
 '16.53730378',
 '18.15698185',
 '18.26508278',
 '15.8583001',
 '17.51598124',
 '17.1756407',
 '16.87673415',
 '20.13614313',
 '16.74981696',
 '20.9876546',
 '18.7066882',
 '14.98283774',
 '18.75056469',
 '16.77747233',
 '15.41678874',
 '16.82943219',
 '16.82246145',
 '16.26454232',
 '17.30759076',
 '17.70419779',
 '16.23887516',
 '18.50605762',
 '17.68927183',
 '17.12608121',
 '15.43727881',
 '16.08639468',
 '14.62611277',
 '14.86286086',
 '16.92653927',
 '15.52553245',
 '18.59029631',
 '15.64483622',
 '21.03304763',
 '18.9809206',
 '20.79019718',
 '16.16085796',
 '16.27516498',
 '17.37694214',
 '17.53933391',
 '19.76625',
 '18.66055872',
 '19.91531604',
 '16.67576922',
 '18.94506709',
 '21.23827121',
 '19.41473198',
 '19.79164891',
 '14.71144435',
 '18.1049131',
 '18.51707332',
 '17.06938534',
 '16.18646052',
 '15.93619557',
 '19.04538932',
 '19.15297263',
 '19.25035125',
 '19.60106569',
 '18.70912954',
 '14.53847731',
 '16.2754431',
 '22.4125987',
 '26.40788116',
 '21.20945643',
 '20.8992682',
 '23.91788526',
 '20.84793381',
 '19.1249436',
 '19.99882384',
 '19.98544152',
 '21.16263325',
 '20.42862094',
 '21.21217427',
 '25.91051351',
 '14.30646167',
 '23.39591426',
 '18.09004618',
 '21.19927651',
 '23.91281908',
 '22.98011075',
 '21.23367058',
 '19.36825953',
 '26.9892822',
 '22.30774891',
 '23.64133806',
 '25.96913841',
 '22.75348496',
 '20.18680376',
 '15.75039078',
 '20.2319449',
 '20.93462324',
 '19.02253131',
 '24.23162001',
 '20.17343418',
 '22.43585316',
 '26.35538259',
 '21.38636497',
 '25.90087189',
 '19.59740487',
 '19.8753749',
 '18.31176463',
 '25.91467629',
 '22.547337',
 '22.39295308',
 '19.04130089',
 '25.05471568',
 '21.18349282',
 '21.75899714',
 '17.91996409',
 '19.8849247',
 '22.8488289',
 '18.81164951',
 '19.25478031',
 '23.87833752',
 '22.38149769',
 '18.62811632',
 '21.35510398',
 '21.9570987',
 '20.53204486',
 '21.99726188',
 '18.97923285',
 '23.85273377',
 '17.85461108',
 '15.66590733',
 '19.82830814',
 '19.87107164',
 '17.74779758',
 '18.46776905',
 '22.83833359',
 '18.23744452',
 '18.68654866',
 '18.68867137',
 '19.06114062',
 '18.01572074',
 '19.94171211',
 '18.54637728',
 '15.47284582',
 '23.35791321',
 '21.4802118',
 '19.28226208',
 '18.43857358',
 '17.13862223',
 '14.91667414',
 '16.59163883',
 '16.64776703',
 '18.32607462',
 '20.75181394',
 '15.08500467',
 '14.25938854',
 '20.47534427',
 '15.98225717',
 '16.41447133',
 '16.87123331',
 '20.52110164',
 '19.7095059',
 '20.38401408',
 '17.3487711',
 '19.38193725',
 '18.8240863',
 '16.39168072',
 '18.11762619',
 '17.99905136',
 '15.44189191',
 '15.51397796',
 '19.68612487',
 '19.15240499',
 '20.51220291',
 '22.36434873',
 '18.8631083',
 '18.59376106',
 '16.69001506',
 '17.01658312',
 '20.24334308',
 '19.73983441',
 '23.85083702',
 '17.47555476',
 '16.12309927',
 '16.48029393',
 '18.69902526',
 '17.21948869',
 '16.95338133',
 '18.61643157',
 '17.43929891',
 '17.00034562',
 '17.27030098',
 '23.8493856',
 '14.97786188',
 '17.32605679',
 '19.8073574',
 '21.99042138',
 '17.46599443',
 '20.68542059',
 '16.14393484',
 '22.71013168',
 '20.7010885',
 '17.96165572',
 '18.85326529',
 '21.40702762',
 '19.18388981',
 '19.36004345',
 '18.46873285',
 '17.10727848',
 '20.34201087',
 '17.57051263',
 '18.53415705',
 '21.15977364',
 '16.82032412',
 '20.99075248',
 '12.61240738',
 '15.8087432',
 '16.73836976',
 '17.33772226',
 '18.61962258',
 '19.01006799',
 '20.32874282',
 '17.74056775',
 '18.496066',
 '18.6481162',
 '16.64579193',
 '16.91470047',
 '21.14897685',
 '19.82861797',
 '14.54588898',
 '21.12847104',
 '18.82329573',
 '20.88594605',
 '14.98260108',
 '17.76092502',
 '17.66680582',
 '16.85270593',
 '21.03039562',
 '14.32872107',
 '15.56070513',
 '15.3515506',
 '10.58315505',
 '12.00173766',
 '13.02248638',
 '17.3826997',
 '17.2072709',
 '17.2072709',
 '16.50064594',
 '19.25071145',
 '16.54130404',
 '19.0858344',
 '19.87969905',
 '19.17252154',
 '16.20379845',
 '16.32085839',
 '20.01558325',
 '16.50003675',
 '24.91023266',
 '17.99585056',
 '14.41827272',
 '15.90757116',
 '13.88232879',
 '19.94247535',
 '14.33727632',
 '18.23735985',
 '17.00075026',
 '17.42569655',
 '22.81788202',
 '14.8406808',
 '18.80031923',
 '16.94227312',
 '13.12228009',
 '15.32385088',
 '16.14015071',
 '18.91010599',
 '18.36410091',
 '15.63314199',
 '14.45036187',
 '19.27422443',
 '21.10276279',
 '17.1940344',
 '18.73027254',
 '15.55415223',
 '20.42635267',
 '14.00234889',
 '23.09800664',
 '17.097947',
 '17.097947',
 '19.56798394',
 '16.13612279',
 '21.98276896',
 '17.18899596',
 '20.03830197',
 '16.44348576',
 '18.13455089',
 '20.88255076',
 '19.69050231',
 '14.47323738',
 '23.69257549',
 '18.57999377',
 '20.26596077',
 '20.26567',
 '20.48392968',
 '16.47387501',
 '15.53271593',
 '18.88228944',
 '16.69278567',
 '13.27161014',
 '14.06871126',
 '20.04849882',
 '15.59720377',
 '21.94201266',
 '15.74226936',
 '20.28932146',
 '21.96185885',
 '17.98502658',
 '19.87944452',
 '17.19364478',
 '19.11476075',
 '18.34932969',
 '14.49049397',
 '18.41093981',
 '16.34766511',
 '16.62839854',
 '15.08346699',
 '19.95739403',
 '18.04240214',
 '18.38343428',
 '17.07098405',
 '21.23881838',
 '17.78260786',
 '21.1244201',
 '21.13764404',
 '23.4887303',
 '23.12029583',
 '15.2519494',
 '15.07594593',
 '18.06185728',
 '20.02677455',
 '19.78645391',
 '20.77707463',
 '21.73342686',
 '13.94540304',
 '17.51419565',
 '18.99093896',
 '19.21441984',
 '20.35248726',
 '20.35248726',
 '14.27192211',
 '19.80564585',
 '18.84983185',
 '20.30903514',
 '18.48084843',
 '17.94423664',
 '17.08860185',
 '17.46365071',
 '17.80347596',
 '17.38396041',
 '19.39554711',
 '17.36009732',
 '21.01079696',
 '19.92847616',
 '24.50255447',
 '19.30965442',
 '18.52085505',
 '20.06830103',
 '19.22509146',
 '19.2746152',
 '17.50155143',
 '17.94188167',
 '13.84978792',
 '19.78270023',
 '16.40508701',
 '18.52381173',
 '16.3202454',
 '15.60929651',
 '14.61200878',
 '21.52464383',
 '21.23455599',
 '23.27266127',
 '23.21275931',
 '18.33461362',
 '15.8268282',
 '17.78989587',
 '25.06896148',
 '19.39217151',
 '20.07669431',
 '21.99081714',
 '22.6532058',
 '18.80645894',
 '17.52855799',
 '20.53288723',
 '16.30923912',
 '21.07534098',
 '18.06243444',
 '17.81870748',
 '17.84514484',
 '21.67275056',
 '17.31792913',
 '17.61072904',
 '17.90678891',
 '17.36178953',
 '19.84239566',
 '17.38416296',
 '17.62626372',
 '19.15228638',
 '20.00411231',
 '13.58572462',
 '18.62913504',
 '13.12199416',
 '14.59209018',
 '18.04564193',
 '18.08219444',
 '18.11061235',
 '19.77859828',
 '19.33636181',
 '17.82477271',
 '17.82477271',
 '18.61713927',
 '19.21064018',
 '15.64136258',
 '13.82036118',
 '24.97621512',
 '18.7741948',
 '14.52217494',
 '22.70305293',
 '20.42991709',
 '16.9258682',
 '17.18648311',
 '17.16769778',
 '12.44744559',
 '19.72208208',
 '18.17183489',
 '12.98462287',
 '18.91569705',
 '19.22123142',
 '20.8210607',
 '19.99043884',
 '19.99043884',
 '20.22203086',
 '13.66413904',
 '17.97703666',
 '16.89030778',
 '18.87585401',
 '16.95469445',
 '14.9029074',
 '17.68745965',
 '19.31355099',
 '16.91406423',
 '19.56835686',
 '16.43557313',
 '13.69080753',
 '17.08154921',
 '19.40276332',
 '16.8601214',
 '20.41788989',
 '12.99731491',
 '18.02395919',
 '28.62804633',
 '19.60792741',
 '23.16637825',
 '17.73219846',
 '15.46800518',
 '17.39292541',
 '19.66884964',
 '25.90845212',
 '18.05067812',
 '18.14789452',
 '18.47665924',
 '17.50728274',
 '19.05091909',
 '18.42477366',
 '15.86965754',
 '15.32439525',
 '21.33088119',
 '17.96526235',
 '17.36719478',
 '20.77993325',
 '16.52239226',
 '16.7693699',
 '19.03179401',
 '13.06813596',
 '19.47894579',
 '12.91568635',
 '17.62176786',
 '19.3658267',
 '18.10215134',
 '17.68616989',
 '20.63850778',
 '20.3047282',
 '13.15125653',
 '16.88949672',
 '18.77809222',
 '14.95434122',
 '20.1136525',
 '15.47274643',
 '25.23696627',
 '15.90922433',
 '19.81436057',
 '19.30313357',
 '16.36504085',
 '17.74765748',
 '18.38972662',
 '18.79670128',
 '15.56311842',
 '18.76444801',
 '18.0630841',
 '20.87986475',
 '22.26087932',
 '25.39999337',
 '18.77266662',
 '14.4933532',
 '16.21737406',
 '17.11708948',
 '21.84327616',
 '23.81626425',
 '20.86073281',
 '19.36065289',
 '23.21314757',
 '24.10882077',
 '17.49080795',
 '12.08017925',
 '22.51959787',
 '20.18066234',
 '22.79222408',
 '17.70406387',
 '18.23039126',
 '22.92440118',
 '21.37923249',
 '20.62432728',
 '24.04362667',
 ...]

In [45]:
metabolome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

In [51]:
metabolome_data   # 59408 x 4 -> 752*90 = 67680

                     sample    group  feature        value
0      A08_045_C13a_group_1  group_1     met1  19.52402565
1      A08_045_C13a_group_1  group_1     met2  14.41925066
2      A08_045_C13a_group_1  group_1     met4   24.6410808
3      A08_045_C13a_group_1  group_1     met5  17.90787554
4      A08_045_C13a_group_1  group_1     met6  17.90787554
...                     ...      ...      ...          ...
67675         NA452_group_5  group_5  met1140  16.82116718
67676         NA452_group_5  group_5  met1141  20.72482181
67677         NA452_group_5  group_5  met1142  16.23427747
67678         NA452_group_5  group_5  met1143  17.51812164
67679         NA452_group_5  group_5  met1144   15.9456557

[67680 rows x 4 columns]

In [53]:
type(metabolome_data)

pandas.core.frame.DataFrame

In [55]:
metabolome_data.to_csv("./metabolome_last_mofa_norm_data.csv")

In [57]:
# Proteome
df = pd.read_csv("proteome_last_impute-norm_ordered_data.csv")
df = pd.DataFrame(df)
df

,Label,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,P05154,10.49738622,10.76795523,11.24273335,10.97984757,11.15883055,10.93616845,11.20195456,11.16704198,10.54410684,...,11.13350342,11.3004919,10.90043331,10.56172114,11.27956026,11.05179401,10.86268596,11.25993923,10.94215059,11.07826456
2,P02786,5.970053052,5.485496474,5.009514539,5.471120003,5.825181725,5.265523335,5.280762167,5.402688587,5.591521906,...,5.835340779,4.849620508,5.829201492,5.343285071,5.968794652,5.175383702,5.812588798,5.540887506,5.776379344,5.837460707
3,Q9Y490,5.582031801,6.598374854,8.370319267,6.460850616,6.788652779,5.676334558,7.929071449,7.265884543,6.807713731,...,7.016377656,4.670973448,6.454176286,7.258689434,4.883610053,6.81242856,5.886218992,6.386709105,3.999766027,5.399076231
4,Q15063-5,4.751896795,4.41135894,4.649739812,4.023219339,5.080629837,3.788815542,4.490804,4.906420996,4.357890793,...,3.198248233,3.240640425,4.579293616,2.953399835,4.490350792,3.986597683,4.329277195,4.059789048,4.061709401,4.289284664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,P52701;P52701-3;P52701-4,7.596987305,6.757783342,5.975132604,5.689220873,6.316759409,5.923182466,6.439470217,6.613101373,5.992711791,...,5.780554203,6.067991432,6.160734678,6.636591271,6.419581026,6.210961558,6.858304322,5.999952661,6.005054095,5.800511679
826,Q9C0G6,3.837014776,3.411521157,5.455705313,6.219377648,5.4212435,6.343377618,5.435008449,5.404954199,6.476828815,...,7.127622963,3.958545756,4.731139786,5.610933288,3.782607761,6.805163453,6.803291626,4.362112151,3.189100263,6.990750691
827,Q9Y5R5,12.68882072,12.85587683,11.65037415,12.61233637,12.38803613,12.49718571,12.79967422,12.84401328,12.56247618,...,12.55410435,10.8530264,12.5376164,12.75890817,10.9108367,12.40893206,11.16289565,12.6000453,12.57664023,12.73110049
828,Q01581,3.379745709,4.446011348,4.030132992,11.02831177,4.141628974,10.92100753,3.417879512,3.269559844,10.92904121,...,10.98143024,10.8530264,4.554337125,5.061763239,4.410768476,11.02194421,4.196591308,11.0658181,3.814273547,3.976904316
829,P01814,5.452045161,3.68416792,4.54511584,3.843109523,3.057316828,4.140541459,4.079617047,4.439097821,3.533438758,...,4.825515987,3.193984584,4.860411629,4.593718283,4.61776277,2.237419931,4.892089826,4.503017921,4.823010503,5.121405042

In [59]:
df.columns

Index(['Label', 'A08_045_C13a', 'A08_056_C13a', 'S09_053_C13a', 'A10_020_C13a',
       'S09_104_C13a', 'A09_126_C13a', 'S09_072_C13a', 'S09_122_C13a',
       'S08_043_C13a', 'A09_072_C13a', 'GA694', 'GA818', 'GA825', 'GA828',
       'GA845', 'GA846', 'GA855', 'GA859', 'GA895', 'GA896', 'GA901', 'NA047',
       'NA048', 'NA050', 'NA160', 'NA161', 'NA291', 'NA344', 'NA390', 'NA423',
       'GA753', 'GA781', 'GA810', 'GA832', 'GA854', 'GA877', 'GA886', 'GA894',
       'GA928', 'NA040', 'NA055', 'NA059', 'NA093', 'NA094', 'NA147', 'NA151',
       'NA196', 'NA247', 'NA268', 'NA279', 'NA391', 'GA730', 'GA749', 'GA862',
       'GA865', 'GA878', 'GA881', 'NA033', 'NA039', 'NA053', 'NA063', 'NA102',
       'NA109', 'NA125', 'NA129', 'NA169', 'NA182', 'NA237', 'NA250', 'NA288',
       'GA733', 'GA738', 'GA960', 'NA074', 'NA084', 'NA092', 'NA132', 'NA225',
       'NA327', 'NA452'],
      dtype='object')

In [61]:
df.loc[:, 'Label']

0                         Group
1                        P05154
2                        P02786
3                        Q9Y490
4                      Q15063-5
                 ...
825    P52701;P52701-3;P52701-4
826                      Q9C0G6
827                      Q9Y5R5
828                      Q01581
829                      P01814
Name: Label, Length: 830, dtype: object

In [63]:
group_info = df.iloc[0]
df = df[1:]
df.index = df.loc[:, 'Label']
df = df.drop('Label', axis=1)
df

,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,A09_072_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
Label,,,,,,,,,,,,,,,,,,,,,
P05154,10.49738622,10.76795523,11.24273335,10.97984757,11.15883055,10.93616845,11.20195456,11.16704198,10.54410684,10.79839362,...,11.13350342,11.3004919,10.90043331,10.56172114,11.27956026,11.05179401,10.86268596,11.25993923,10.94215059,11.07826456
P02786,5.970053052,5.485496474,5.009514539,5.471120003,5.825181725,5.265523335,5.280762167,5.402688587,5.591521906,5.822978148,...,5.835340779,4.849620508,5.829201492,5.343285071,5.968794652,5.175383702,5.812588798,5.540887506,5.776379344,5.837460707
Q9Y490,5.582031801,6.598374854,8.370319267,6.460850616,6.788652779,5.676334558,7.929071449,7.265884543,6.807713731,3.636207989,...,7.016377656,4.670973448,6.454176286,7.258689434,4.883610053,6.81242856,5.886218992,6.386709105,3.999766027,5.399076231
Q15063-5,4.751896795,4.41135894,4.649739812,4.023219339,5.080629837,3.788815542,4.490804,4.906420996,4.357890793,4.728711587,...,3.198248233,3.240640425,4.579293616,2.953399835,4.490350792,3.986597683,4.329277195,4.059789048,4.061709401,4.289284664
P02730,5.285658419,7.532456183,7.322349713,6.423822221,8.385428175,5.653984858,6.757399153,7.232235245,8.76943461,7.320448976,...,7.251876542,6.386256258,6.139433634,5.96831214,6.955028036,6.259887186,6.319174067,7.443723657,7.875461744,6.632780879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P52701;P52701-3;P52701-4,7.596987305,6.757783342,5.975132604,5.689220873,6.316759409,5.923182466,6.439470217,6.613101373,5.992711791,6.377075149,...,5.780554203,6.067991432,6.160734678,6.636591271,6.419581026,6.210961558,6.858304322,5.999952661,6.005054095,5.800511679
Q9C0G6,3.837014776,3.411521157,5.455705313,6.219377648,5.4212435,6.343377618,5.435008449,5.404954199,6.476828815,4.587034886,...,7.127622963,3.958545756,4.731139786,5.610933288,3.782607761,6.805163453,6.803291626,4.362112151,3.189100263,6.990750691
Q9Y5R5,12.68882072,12.85587683,11.65037415,12.61233637,12.38803613,12.49718571,12.79967422,12.84401328,12.56247618,11.14899859,...,12.55410435,10.8530264,12.5376164,12.75890817,10.9108367,12.40893206,11.16289565,12.6000453,12.57664023,12.73110049
Q01581,3.379745709,4.446011348,4.030132992,11.02831177,4.141628974,10.92100753,3.417879512,3.269559844,10.92904121,11.14899859,...,10.98143024,10.8530264,4.554337125,5.061763239,4.410768476,11.02194421,4.196591308,11.0658181,3.814273547,3.976904316
P01814,5.452045161,3.68416792,4.54511584,3.843109523,3.057316828,4.140541459,4.079617047,4.439097821,3.533438758,3.990991154,...,4.825515987,3.193984584,4.860411629,4.593718283,4.61776277,2.237419931,4.892089826,4.503017921,4.823010503,5.121405042

In [65]:
group_info = group_info[1:]
group_info

A08_045_C13a    group_1
A08_056_C13a    group_1
S09_053_C13a    group_1
A10_020_C13a    group_1
S09_104_C13a    group_1
                 ...
NA092           group_5
NA132           group_5
NA225           group_5
NA327           group_5
NA452           group_5
Name: 0, Length: 80, dtype: object

In [67]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [57]:
sample_list

['A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',

In [59]:
feature_list

['P05154',
 'P02786',
 'Q9Y490',
 'Q15063-5',
 'P02730',
 'P0C0L4',
 'P02768',
 'P17483',
 'P06753',
 'P02766',
 'P26927',
 'O95445-2',
 'P98160',
 'P04114',
 'P19827',
 'P02765',
 'P01019',
 'P31146',
 'P01854',
 'O00391',
 'P12111-4',
 'A0M8Q6',
 'P04180',
 'P04075',
 'P01023',
 'P18206;P18206-2',
 'P10643',
 'P01042-2',
 'P02649',
 'P02549',
 'Q9Y6Y1;Q9Y6Y1-2',
 'P39060;P39060-1',
 'P06733',
 'P01024',
 'P00558',
 'P05156',
 'P00742',
 'Q16610;Q16610-4',
 'Q8IUL8',
 'P01833',
 'P35579',
 'P01008',
 'P00915',
 'B9A064',
 'Q13113',
 'P12259',
 'P13645',
 'P04196',
 'P07900;P07900-2',
 'P01011',
 'Q12805;Q12805-2;Q12805-3;Q12805-4',
 'P02787',
 'P22105;P22105-1;P22105-4',
 'P0DOY2;P0DOY3',
 'P02538',
 'P04040',
 'P09493-8',
 'P04264',
 'P21333;P21333-2',
 'Q14624',
 'P08514',
 'P07360',
 'P13796',
 'P19823',
 'A0A075B6Q5',
 'A0A0C4DH30',
 'A0A0C4DH32',
 'P01782',
 'P01764',
 'P01780',
 'P0DTE1',
 'A0A0J9YX35',
 'A0A0C4DH35',
 'P00450',
 'P00748',
 'P06276',
 'Q9Y5Y7',
 'P67936',
 'P04275',
 'P14618',
 'A0A0C4DH36',
 'P14151;P14151-2',
 'Q93084;Q93084-1;Q93084-3;Q93084-4;Q93084-5;Q93084-6;Q93084-7',
 'P02647',
 'P0C0L5',
 'P02748',
 'P43652',
 'P01031',
 'P23229;P23229-2;P23229-3;P23229-4;P23229-5;P23229-6;P23229-9',
 'P02760',
 'Q8N972',
 'O95445',
 'P08571',
 'P08253;P08253-2;P08253-3',
 'P00747',
 'P68366;P68366-2',
 'P35858;P35858-2',
 'Q01518',
 'P06396',
 'P55058',
 'P27487',
 'Q86UX7;Q86UX7-2',
 'P01766',
 'P13591;P13591-1;P13591-3;P13591-4',
 'P08603',
 'P25311',
 'P60709;P63261',
 'O75636',
 'P22792',
 'P08294',
 'Q9NTI5;Q9NTI5-2',
 'Q96PD5',
 'Q92945',
 'P02776',
 'P52209;P52209-2',
 'Q9UKY3',
 'P07996',
 'Q8N4Q0;Q8N4Q0-2',
 'Q9Y6Z7',
 'O00187',
 'O95925-2',
 'P11277;P11277-2',
 'Q8NBP7',
 'P07225',
 'P02675',
 'Q86XI6',
 'P07357',
 'P00734',
 'Q9UGM5',
 'Q9BWP8-6',
 'Q92954-3',
 'Q9Y6R7',
 'P00751',
 'Q96KN2',
 'P07437',
 'Q9NP58;Q9NP58-4',
 'P02679;P02679-2',
 'P23142',
 'P02774;P02774-3',
 'Q8IUG5;Q8IUG5-2;Q8IUG5-3',
 'O15511',
 'O14791;O14791-2',
 'P04278',
 'P17936;P17936-2',
 'P01034',
 'P12814',
 'Q06033;Q06033-2',
 'P02533',
 'Q04695',
 'P80108',
 'O43301',
 'P14770',
 'Q8NHQ9',
 'A0A0B4J1V2',
 'A0A0C4DH43',
 'Q13740;Q13740-2',
 'Q8TDL5',
 'P02750',
 'P60660;P60660-2',
 'P06681',
 'P04211',
 'P20851;P20851-2',
 'P20742',
 'Q86YD7',
 'Q10588',
 'P00390;P00390-2;P00390-3',
 'O75144;O75144-2',
 'O00329',
 'P13671',
 'P05109',
 'P01857',
 'P51841',
 'P15259',
 'P09211',
 'P02790',
 'P10909-6',
 'P11226',
 'P03951',
 'P16070;P16070-10;P16070-11;P16070-16;P16070-17;P16070-3;P16070-4;P16070-5;P16070-6;P16070-7;P16070-9',
 'Q9H4B7',
 'P02671',
 'P07333',
 'P26038',
 'Q99497',
 'P06727',
 'P29622',
 'O75882-2',
 'P36955',
 'Q9BXR6',
 'Q2KHR3;Q2KHR3-2',
 'P11597',
 'A0A0B4J1V6',
 'A0A0B4J1Y9',
 'P24592',
 'P22891;P22891-2',
 'P01880;P01880-2',
 'Q9NZP8',
 'A0A087WSZ0',
 'P48740-2',
 'P09486',
 'P02741',
 'P52566',
 'P05019;P05019-2;P05019-3;P05019-4',
 'P08779',
 'P04217-2',
 'P01889',
 'Q15166',
 'P41222',
 'P02751-1',
 'P00813',
 'Q02985;Q02985-2',
 'Q9UDT6;Q9UDT6-2',
 'Q6UXB8',
 'P05543',
 'P13647',
 'P35908',
 'Q9HBI1;Q9HBI1-2;Q9HBI1-3',
 'Q6ZMI0;Q6ZMI0-2;Q6ZMI0-3',
 'Q9H4G4',
 'A0A0C4DH38',
 'A0A0C4DH39',
 'P01742',
 'A0A087WW87;P01614',
 'O75884;O75884-2',
 'P23083',
 'A0A0C4DH29',
 'A0A0J9YVY3',
 'P0DP01',
 'A0A0C4DH31',
 'P01743',
 'A0A0A0MS14',
 'Q08380',
 'P14543;P14543-2',
 'Q12860;Q12860-2',
 'P04430',
 'A0A075B6S5',
 'A0A0B4J2D9;P0DP09',
 'P01601',
 'A0A0C4DH67',
 'A0A0A0MT36',
 'P0DOX7',
 'P01602',
 'P01597;P04432',
 'A0A087WSY6',
 'P01619',
 'A0A075B6H7',
 'P04433',
 'Q53LP3',
 'O43795',
 'Q6UX71',
 'P05362',
 'O43166;O43166-2;O43166-3',
 'P18428',
 'P32119',
 'P02749',
 'Q2Q1W2',
 'P04259',
 'P69891',
 'P00746',
 'A0A0C4DH25',
 'P61626',
 'P24844',
 'P04217',
 'P49747',
 'Q71U36;Q71U36-2',
 'P00738',
 'A0A075B6K2',
 'P23528',
 'P08185',
 'P01009',
 'P68371',
 'Q99543;Q99543-2',
 'P00488',
 'P16452;P16452-2;P16452-3',
 'P00918',
 'P04004',
 'Q12913;Q12913-3',
 'Q9NR56;Q9NR56-2;Q9NR56-3;Q9NR56-4;Q9NR56-5;Q9NR56-6;Q9NR56-7',
 'Q04917',
 'P54198;P54198-2',
 'P08637',
 'P12955',
 'P24593',
 'P55056',
 'Q9UGU5',
 'A0A0A0MS15',
 'Q96IY4',
 'Q03692',
 'P02743',
 'P35542',
 'P27918',
 'P01859',
 'P07358',
 'P04003',
 'P05160',
 'P05452',
 'O00151',
 'Q92496;Q92496-2',
 'P49908',
 'P36980;P36980-2',
 'P03952',
 'P00736',
 'P78380;P78380-3',
 'P01860',
 'P01042',
 'P05090',
 'P05106',
 'P09871',
 'P04070;P04070-2',
 'O43866',
 'P01591',
 'P40197',
 'P48740',
 'P11142',
 'P11021',
 'P0DMV8;P0DMV8-2;P0DMV9',
 'P19320;P19320-2;P19320-3',
 'P05546',
 'Q13103',
 'P02656',
 'P51451',
 'P43251;P43251-2;P43251-3;P43251-4',
 'P01877',
 'P01876',
 'P37802;P37802-2',
 'Q7Z794',
 'Q9NQ79;Q9NQ79-2;Q9NQ79-3',
 'Q14520;Q14520-2',
 'P08697',
 'O15037',
 'P05155;P05155-3',
 'P30041',
 'P02788;P02788-2',
 'P0DP23;P0DP24;P0DP25',
 'P04439;P04439-2',
 'P01871',
 'P04792',
 'P63104',
 'O95452',
 'P35527',
 'Q6DN14;Q6DN14-2;Q6DN14-3;Q6DN14-4;Q6DN14-5',
 'Q8WTT2',
 'P00338;P00338-3',
 'P02768-2',
 'P50395',
 'P23142-4',
 'Q15582',
 'P15144',
 'P06702',
 'P04066',
 'P98194;P98194-2;P98194-3;P98194-4;P98194-5;P98194-6;P98194-7;P98194-8;P98194-9',
 'P62736',
 'Q9UBX5',
 'O95810',
 'P02753',
 'P0DJI8',
 'O14792',
 'Q13201',
 'P02745',
 'P02746',
 'Q04756',
 'P01718',
 'P06310',
 'Q8N4C7',
 'P07737',
 'A0A075B6K5',
 'P01834',
 'P61224;P61224-3',
 'Q96PQ0',
 'Q8ND24',
 'P12109',
 'P23284',
 'P21926',
 'Q96KJ4',
 'Q92820',
 'P62258',
 'Q8N5G2',
 'Q05682;Q05682-2;Q05682-3;Q05682-4;Q05682-5;Q05682-6',
 'Q9H8L6',
 'Q63HM2',
 'P15169',
 'O94812;O94812-2;O94812-3;O94812-5;O94812-6;O94812-7',
 'P08519',
 'P27105',
 'P51884',
 'P08567',
 'P78417',
 'O95497',
 'P06753-2',
 'P02775',
 'P14625',
 'P02654',
 'Q9UNN8',
 'P68871',
 'P02042',
 'Q9C0A6;Q9C0A6-2;Q9C0A6-3',
 'P16157;P16157-10;P16157-12;P16157-14;P16157-16;P16157-3;P16157-5;P16157-8',
 'P62937',
 'Q13418',
 'P05976-2',
 'P37840;P37840-2',
 'P19652',
 'Q15063-2',
 'Q9HBB8;Q9HBB8-2;Q9HBB8-4',
 'Q9UHG3',
 'Q9NR34',
 'P33151',
 'Q8TCU4;Q8TCU4-2;Q8TCU4-3',
 'Q15404;Q15404-2',
 'P59998;P59998-2;P59998-3',
 'P26447',
 'Q9NRC6',
 'P30101',
 'Q14643;Q14643-2;Q14643-3;Q14643-4;Q14643-5;Q14643-6;Q14643-7;Q14643-8',
 'P81605;P81605-2',
 'Q7L1S5',
 'P33908',
 'P02652',
 'P01861',
 'Q8IWU2',
 'P02763',
 'P0DOX6',
 'O95793-3',
 'P01817',
 'Q6EMK4',
 'Q96Q89;Q96Q89-2;Q96Q89-3;Q96Q89-4',
 'P02655',
 'P0CG47;P0CG48;P62979;P62987',
 'P09493-5',
 'P09172',
 'Q9UK55',
 'P05062',
 'P42680',
 'O14503',
 'P0DOX3',
 'Q08257;Q08257-3',
 'P0DOX2',
 'P27169',
 'P43121',
 'P00740',
 'P49913',
 'P07339',
 'B2RNN3',
 'Q76LX8;Q76LX8-2',
 'Q9BYV7-5',
 'P00491',
 'Q15942',
 'Q99784;Q99784-3;Q99784-5',
 'P40227;P40227-2',
 'P07195',
 'P69905',
 'Q8N309',
 'P22352',
 'Q9H3R1',
 'Q6YHK3;Q6YHK3-2;Q6YHK3-4',
 'A0A075B6K6',
 'P02747',
 'Q8ND04-2',
 'O14867',
 'Q08AN1',
 'A0A075B6R9;A0A0C4DH68',
 'P01721',
 'A0A075B6I0',
 'A0A075B6I9',
 'A0A0A0MRZ9',
 'A0A075B6I1',
 'A0A075B6H9',
 'P01714',
 'A2NJV5',
 'P08709;P08709-2',
 'P40261',
 'A0A0B4J1Y8',
 'O14950;P19105',
 'Q9HB29;Q9HB29-2',
 'P48059-2',
 'O14786;O14786-2;O14786-3',
 'P0DJI9',
 'P04406',
 'Q96LP6;Q96LP6-2',
 'P62491;P62491-2;Q15907;Q15907-2',
 'P38646',
 'Q9UBR2',
 'Q15848',
 'P55290;P55290-4',
 'Q07954',
 'P01033',
 'Q14315;Q14315-2',
 'P40967;P40967-2;P40967-4;P40967-5',
 'Q9HBA9',
 'Q8NEP3;Q8NEP3-2;Q8NEP3-3',
 'Q5JTN6',
 'Q6P4A7;Q6P4A7-2;Q6P4A7-3',
 'Q9NRV9',
 'P13473;P13473-2;P13473-3',
 'P01344;P01344-2;P01344-3',
 'P06331',
 'A0A075B6R2',
 'P0DP08',
 'A0A0B4J1U7',
 'A0A0C4DH33',
 'A0A0J9YXX1',
 'P01768;P0DP03',
 'A0A0B4J1V1',
 'P01763',
 'Q9HDC9',
 'Q06830',
 'P07359',
 'P05783',
 'Q99439',
 'Q5JSZ5',
 'P29508',
 'A0A0B4J1X5',
 'P08F94',
 'Q9H0W8;Q9H0W8-2',
 'O00533;O00533-2',
 'Q9Y2Z2;Q9Y2Z2-2;Q9Y2Z2-4;Q9Y2Z2-5;Q9Y2Z2-6',
 'Q0VDD7;Q0VDD7-2',
 'Q9P281',
 'A0A075B6J1',
 'Q92934',
 'Q9NVM6',
 'P11166',
 'Q15485',
 'P31151',
 'P48634;P48634-2;P48634-3',
 'Q9NQC3-3',
 'Q15113',
 'P52895;Q04828',
 'Q3LI63',
 'Q15555-5',
 'P61586',
 'P15153',
 'A0A075B6S4',
 'Q13402;Q13402-2;Q13402-5;Q13402-6;Q13402-7;Q13402-8',
 'P07237',
 'A0A1B0GVH6',
 'O95622;O95622-2',
 'Q9ULV4;Q9ULV4-2;Q9ULV4-3',
 'O75602;O75602-2;O75602-3;O75602-5',
 'Q8TDM6;Q8TDM6-2;Q8TDM6-4',
 'Q9ULV3;Q9ULV3-2;Q9ULV3-3;Q9ULV3-4;Q9ULV3-5',
 'O75083',
 'Q08830',
 'P30740',
 'Q14651',
 'Q9Y6J0;Q9Y6J0-2',
 'P68104;Q5VTE0',
 'Q8NI27',
 'Q96BY7',
 'Q5T013;Q5T013-3',
 'O95568',
 'Q8N103;Q8N103-2;Q8N103-3',
 'P29401;P29401-2',
 'P25705;P25705-2',
 'Q4KWH8;Q4KWH8-3;Q4KWH8-4',
 'P06744-2',
 'P13598',
 'Q99459',
 'P61204;P84077',
 'Q9NP80-2',
 'Q92823;Q92823-2;Q92823-3;Q92823-4;Q92823-5;Q92823-6',
 'Q6UY14;Q6UY14-2;Q6UY14-3',
 'P59665;P59666',
 'P17301',
 'Q8TCS8',
 'Q92608',
 'P59190-2',
 'Q9H299',
 'P07864',
 'A0A075B6K4',
 'A0A075B6K0',
 'Q7Z6K1;Q7Z6K1-2',
 'Q86U17',
 'Q5TCS8',
 'Q8WWZ8',
 'Q86VZ2',
 'A0A087WSX0',
 'Q86V48;Q86V48-2;Q86V48-3',
 'P37837;P37837-2',
 'P25391',
 'Q8NI99',
 'O15484',
 'P13716;P13716-2',
 'Q5T6F0',
 'Q5SRE5;Q5SRE5-2',
 'P19013',
 'Q86VD1;Q86VD1-2',
 'O95479;O95479-2',
 'Q9UNW1',
 'P58335;P58335-2;P58335-4',
 'P83105',
 'Q09161',
 'Q96H15;Q96H15-2',
 'Q9Y259',
 'P18065',
 'P16112;P16112-2;P16112-3',
 'P16930',
 'Q9Y2X3',
 'A8MQ27;A8MQ27-2',
 'P24557;P24557-2;P24557-3',
 'Q9ULL1',
 'Q16853',
 'Q12884',
 'Q99996;Q99996-1;Q99996-3;Q99996-5;Q99996-6',
 'O15145',
 'O94973;O94973-2;O94973-3',
 'Q7Z7G0',
 'Q9HC35;Q9HC35-2',
 'P01599',
 'P09086;P09086-2;P09086-3;P09086-4;P09086-5;P14859;P14859-2;P14859-3;P14859-4;P14859-5;P14859-6;Q9UKI9;Q9UKI9-2;Q9UKI9-3',
 'P14174',
 'Q9Y4R8',
 'Q14571',
 'O60312',
 'Q92887',
 'P01593;P01594',
 'P01701',
 'P01703',
 'A0A075B6S9;P0DSN7',
 'P01700',
 'P06312',
 'A0A0B4J1U3',
 'Q08345;Q08345-5',
 'Q9NQU5;Q9NQU5-2',
 'P52907',
 'O60814;P06899;P23527;P33778;P57053;P58876;P62807;Q16778;Q5QNW6;Q5QNW6-2;Q93079;Q99877;Q99879;Q99880',
 'Q6ZS72',
 'O95477',
 'Q9BQL6;Q9BQL6-2;Q9BQL6-4',
 'P13224;P13224-2',
 'B1AJZ9;B1AJZ9-4',
 'Q9Y2X7-3',
 'P08195;P08195-2;P08195-3;P08195-4',
 'P01706',
 'P01705',
 'P01709',
 'A0A075B6J9',
 'P01704',
 'Q68DL7',
 'P30043',
 'O43677',
 'Q96MM7;Q96MM7-2;Q96MM7-3;Q96MM7-4',
 'A0A0B4J1X8',
 'A0A0B4J1V0',
 'P0DOX5',
 'P01767',
 'Q8NGJ5',
 'P19022;P19022-2',
 'P05556',
 'O75717;O75717-2',
 'P02100',
 'O15270',
 'Q02224;Q02224-3',
 'A0A075B6V5',
 'A0A0C4DH34',
 'Q9H6Y7;Q9H6Y7-2',
 'Q9Y277;Q9Y277-2',
 'Q53FP2',
 'Q96JA1;Q96JA1-2',
 'Q9BTZ2;Q9BTZ2-2;Q9BTZ2-7',
 'Q86VB7-2',
 'Q99969',
 'Q13228;Q13228-4',
 'Q14118',
 'Q9NPH3-5',
 'Q8TAW3',
 'Q9Y5Z7',
 'P12830',
 'O60841',
 'Q8NB91',
 'Q13609;Q13609-2',
 'P08493;P08493-2',
 'O95980',
 'Q9NVF9;Q9NVF9-2;Q9NVF9-3',
 'Q8WXW3;Q8WXW3-4',
 'P07093;P07093-2;P07093-3',
 'Q99715;Q99715-4',
 'Q9HAR2-2;Q9HAR2-4',
 'Q9NTJ5',
 'A0A075B6I4',
 'P35443',
 'P03950',
 'P00739',
 'Q14697;Q14697-2',
 'Q823',
 'Q8WTQ7',
 'Q16627;Q16627-2',
 'P80748',
 'A0A075B6S2',
 'A0A075B6P5;P01615',
 'P01715',
 'Q8TBB0-2',
 'P63272',
 'A0A1W2PQ73',
 'Q8IUX7',
 'A6NM28',
 'P07203',
 'Q99700;Q99700-2;Q99700-4',
 'Q13467',
 'P36957;P36957-2',
 'Q9BYG5',
 'Q6AHZ1;Q6AHZ1-2',
 'Q16706',
 'Q9HAS0',
 'Q9Y3R4',
 'Q86UP2;Q86UP2-2;Q86UP2-4',
 'Q3V6T2;Q3V6T2-2;Q3V6T2-3;Q3V6T2-4;Q3V6T2-5',
 'P98077',
 'Q9UKN1;Q9UKN1-2',
 'O15034',
 'Q9NQW1;Q9NQW1-2;Q9NQW1-4;Q9NQW1-5',
 'Q6ZQQ6;Q6ZQQ6-2',
 'Q86Y38',
 'Q8WXA3;Q8WXA3-1;Q8WXA3-3',
 'Q9H3Y8',
 'P60174;P60174-3',
 'P01906',
 'Q16644',
 'P0DOX4',
 'P16671',
 'P01717',
 'Q5CZC0',
 'A7MCY6',
 'Q6ZU45',
 'Q13822;Q13822-3',
 'P25100',
 'Q14244;Q14244-3;Q14244-5;Q14244-6;Q14244-7',
 'A6NLC5',
 'P84243',
 'P28340',
 'Q5T749',
 'A0A0G2JS06',
 'Q13790',
 'Q96QB1;Q96QB1-3;Q96QB1-5',
 'Q96Q40;Q96Q40-3;Q96Q40-4;Q96Q40-5',
 'Q9NP78;Q9NP78-2;Q9NP78-3;Q9NP78-5;Q9NP78-6;Q9NP78-7',
 'Q9NVI1;Q9NVI1-1;Q9NVI1-2',
 'Q7Z2Z1;Q7Z2Z1-2',
 'Q96ME1',
 'P61769',
 'Q9Y4B5',
 'Q92802;Q92802-2;Q92802-3',
 'Q17RB8;Q17RB8-2',
 'Q03591',
 'Q9Y5Q9',
 'Q15772;Q15772-1',
 'Q8WZ59',
 'Q86UX2;Q86UX2-3',
 'P51797;P51797-5',
 'P10599;P10599-2',
 'Q9H0C2',
 'Q9NU02',
 'Q66GS9',
 'P15531;P15531-2;P22392;P22392-2',
 'Q9HAU8',
 'P62913;P62913-2',
 'P09668',
 'Q14515',
 'A8MTZ0-4',
 'Q8NB49;Q8NB49-2;Q8NB49-3;Q8NB49-4',
 'P08238',
 'Q13939',
 'Q16515-2',
 'Q562R1',
 'O14498',
 'P23378',
 'Q16891;Q16891-2;Q16891-3;Q16891-4',
 'Q9NZ43-3',
 'Q14247;Q14247-3',
 'P12273',
 'P21980;P21980-2',
 'Q14376;Q14376-2',
 'Q4G0P3',
 'O95340;O95340-2',
 'P09496;P09496-3',
 'A6NHZ5',
 'A6NGE4',
 'P15291;P15291-2',
 'Q9BYX7',
 'P07738',
 'P09417;P09417-2',
 'Q96IK1;Q96IK1-2',
 'Q15413;Q15413-2;Q15413-3',
 'Q13098;Q13098-5;Q13098-7',
 'Q9H8W3',
 'Q9H8M5;Q9H8M5-2',
 'Q9Y646',
 'Q9BUN1',
 'Q02413',
 'Q16773;Q16773-2',
 'P63241;P63241-2',
 'P0DOX8',
 'P78563;P78563-2;P78563-4;P78563-5',
 'P35030;P35030-2',
 'Q96S38;Q96S38-2',
 'Q6ZRS2;Q6ZRS2-2;Q6ZRS2-3',
 'P13929;P13929-2;P13929-3',
 'Q9NZJ4;Q9NZJ4-2',
 'Q9NQV5;Q9NQV5-2',
 'Q9HCH0;Q9HCH0-2',
 'Q9H257;Q9H257-2;Q9H257-3',
 'Q8TDD1;Q8TDD1-2',
 'Q9NPR2',
 'A0A0G2JMI3',
 'P24821;P24821-4',
 'A0A075B6S6',
 'Q15326;Q15326-2;Q15326-3;Q15326-4;Q15326-5;Q15326-6',
 'P19235;P19235-2;P19235-3',
 'P01699',
 'O14543',
 'P78324;P78324-2;P78324-4;Q5TFQ8;Q9P1W8;Q9P1W8-2;Q9P1W8-3;Q9P1W8-4',
 'A6NHQ2',
 'P13727;P13727-2',
 'P54108;P54108-2;P54108-3',
 'P54793',
 'Q9H5I1;Q9H5I1-2;Q9H5I1-3',
 'Q6ZMG9-2',
 'A0A0A0MT89',
 'P15814',
 'Q7L014',
 'A0A0C4DH24',
 'Q8WWW0;Q8WWW0-3',
 'Q16880',
 'P07998',
 'P52701;P52701-3;P52701-4',
 'Q9C0G6',
 'Q9Y5R5',
 'Q01581',
 'P01814',
 'P05154',
 'P02786',
 'Q9Y490',
 'Q15063-5',
 'P02730',
 'P0C0L4',
 'P02768',
 'P17483',
 'P06753',
 'P02766',
 'P26927',
 'O95445-2',
 'P98160',
 'P04114',
 'P19827',
 'P02765',
 'P01019',
 'P31146',
 'P01854',
 'O00391',
 'P12111-4',
 'A0M8Q6',
 'P04180',
 'P04075',
 'P01023',
 'P18206;P18206-2',
 'P10643',
 'P01042-2',
 'P02649',
 'P02549',
 'Q9Y6Y1;Q9Y6Y1-2',
 'P39060;P39060-1',
 'P06733',
 'P01024',
 'P00558',
 'P05156',
 'P00742',
 'Q16610;Q16610-4',
 'Q8IUL8',
 'P01833',
 'P35579',
 'P01008',
 'P00915',
 'B9A064',
 'Q13113',
 'P12259',
 'P13645',
 'P04196',
 'P07900;P07900-2',
 'P01011',
 'Q12805;Q12805-2;Q12805-3;Q12805-4',
 'P02787',
 'P22105;P22105-1;P22105-4',
 'P0DOY2;P0DOY3',
 'P02538',
 'P04040',
 'P09493-8',
 'P04264',
 'P21333;P21333-2',
 'Q14624',
 'P08514',
 'P07360',
 'P13796',
 'P19823',
 'A0A075B6Q5',
 'A0A0C4DH30',
 'A0A0C4DH32',
 'P01782',
 'P01764',
 'P01780',
 'P0DTE1',
 'A0A0J9YX35',
 'A0A0C4DH35',
 'P00450',
 'P00748',
 'P06276',
 'Q9Y5Y7',
 'P67936',
 'P04275',
 'P14618',
 'A0A0C4DH36',
 'P14151;P14151-2',
 'Q93084;Q93084-1;Q93084-3;Q93084-4;Q93084-5;Q93084-6;Q93084-7',
 'P02647',
 'P0C0L5',
 'P02748',
 'P43652',
 'P01031',
 'P23229;P23229-2;P23229-3;P23229-4;P23229-5;P23229-6;P23229-9',
 'P02760',
 'Q8N972',
 'O95445',
 'P08571',
 'P08253;P08253-2;P08253-3',
 'P00747',
 'P68366;P68366-2',
 'P35858;P35858-2',
 'Q01518',
 'P06396',
 'P55058',
 'P27487',
 'Q86UX7;Q86UX7-2',
 'P01766',
 'P13591;P13591-1;P13591-3;P13591-4',
 'P08603',
 'P25311',
 'P60709;P63261',
 'O75636',
 'P22792',
 'P08294',
 'Q9NTI5;Q9NTI5-2',
 'Q96PD5',
 'Q92945',
 'P02776',
 'P52209;P52209-2',
 'Q9UKY3',
 'P07996',
 'Q8N4Q0;Q8N4Q0-2',
 'Q9Y6Z7',
 'O00187',
 'O95925-2',
 'P11277;P11277-2',
 'Q8NBP7',
 'P07225',
 'P02675',
 'Q86XI6',
 'P07357',
 'P00734',
 'Q9UGM5',
 'Q9BWP8-6',
 'Q92954-3',
 'Q9Y6R7',
 'P00751',
 'Q96KN2',
 'P07437',
 'Q9NP58;Q9NP58-4',
 'P02679;P02679-2',
 'P23142',
 'P02774;P02774-3',
 'Q8IUG5;Q8IUG5-2;Q8IUG5-3',
 'O15511',
 'O14791;O14791-2',
 'P04278',
 'P17936;P17936-2',
 'P01034',
 'P12814',
 'Q06033;Q06033-2',
 'P02533',
 'Q04695',
 'P80108',
 'O43301',
 'P14770',
 'Q8NHQ9',
 'A0A0B4J1V2',
 'A0A0C4DH43',
 'Q13740;Q13740-2',
 'Q8TDL5',
 'P02750',
 'P60660;P60660-2',
 'P06681',
 'P04211',
 'P20851;P20851-2',
 'P20742',
 'Q86YD7',
 'Q10588',
 'P00390;P00390-2;P00390-3',
 'O75144;O75144-2',
 'O00329',
 'P13671',
 'P05109',
 'P01857',
 ...]

In [69]:
proteome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

proteome_data      # 829 * 79 = 65491

                     sample    group                   feature        value
0      A08_045_C13a_group_1  group_1                    P05154  10.49738622
1      A08_045_C13a_group_1  group_1                    P02786  5.970053052
2      A08_045_C13a_group_1  group_1                    Q9Y490  5.582031801
3      A08_045_C13a_group_1  group_1                  Q15063-5  4.751896795
4      A08_045_C13a_group_1  group_1                    P02730  5.285658419
...                     ...      ...                       ...          ...
66315         NA452_group_5  group_5  P52701;P52701-3;P52701-4  5.800511679
66316         NA452_group_5  group_5                    Q9C0G6  6.990750691
66317         NA452_group_5  group_5                    Q9Y5R5  12.73110049
66318         NA452_group_5  group_5                    Q01581  3.976904316
66319         NA452_group_5  group_5                    P01814  5.121405042

[66320 rows x 4 columns]

In [71]:
proteome_data.to_csv("./proteome_last_mofa_impute-norm_data.csv")

In [73]:
# Transcriptome
df = pd.read_csv("transcriptome_last_norm_ordered_data.csv", low_memory=False)
df = pd.DataFrame(df)
df

,Label,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,16659637,0.86314,1.21357,1.39364,1.53159,1.21563,1.39848,1.72079,0.72676,1.7319,...,1.47654,1.29275,1.94308,1.63443,1.57844,1.56274,0.86799,1.99235,1.4993,0.97502
2,16664406,1.25862,1.39001,0.81366,1.08916,0.80341,1.31593,1.03926,1.35179,1.45531,...,1.19542,1.61435,0.97501,1.37691,0.9932,0.71453,1.17141,0.77827,1.03242,0.64173
3,16665159,1.39798,1.37535,1.25231,1.55429,1.45725,1.22063,1.29021,1.1208,1.79425,...,1.48516,1.40757,1.02428,1.09439,1.00745,1.13538,0.72924,1.30162,0.98353,1.06039
4,16665603,0.78432,0.71935,0.84219,1.44859,0.79489,0.74165,0.90227,1.13519,0.91891,...,0.50991,0.39126,0.745,0.99561,0.39861,0.67146,0.34088,0.74965,0.57917,0.43188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,17114322,1.13471,1.14963,1.25407,1.13812,1.28838,1.52156,1.05127,1.43208,1.41318,...,0.8224,1.29065,1.17727,0.94143,1.54946,1.05201,1.05819,0.70263,1.30952,1.37988
304,17114768,1.49652,1.73469,1.43508,1.73391,1.49996,1.63881,1.63394,1.52747,1.63487,...,1.89585,1.24586,1.43993,1.42443,1.69255,1.63538,0.89949,1.38476,1.5803,1.36799
305,17114783,1.34644,1.03372,1.26863,0.9554,1.54736,1.42942,1.57353,1.0607,1.52643,...,1.64292,1.097,1.6315,1.21056,1.13699,0.89847,0.93103,0.5503,1.29747,1.07501
306,17114795,2.23753,2.17749,1.93852,2.11166,1.90734,2.09612,2.03066,1.92942,1.99992,...,2.04646,1.84058,2.04844,1.92315,2.02821,2.03405,1.55866,1.66581,2.01897,1.82632
307,17116977,1.78634,2.79327,1.73966,1.66679,2.89374,1.74219,1.90706,1.74415,1.70309,...,2.8296,1.81057,2.87942,1.78393,2.8699,2.86381,2.95828,2.95703,1.73277,2.87321

In [75]:
df.columns

Index(['Label', 'A08_045_C13a', 'A08_056_C13a', 'S09_053_C13a', 'A10_020_C13a',
       'S09_104_C13a', 'A09_126_C13a', 'S09_072_C13a', 'S09_122_C13a',
       'S08_043_C13a', 'A09_072_C13a', 'GA694', 'GA818', 'GA825', 'GA828',
       'GA845', 'GA846', 'GA855', 'GA859', 'GA895', 'GA896', 'GA901', 'NA047',
       'NA048', 'NA050', 'NA160', 'NA161', 'NA291', 'NA344', 'NA390', 'NA423',
       'GA753', 'GA781', 'GA810', 'GA832', 'GA854', 'GA877', 'GA886', 'GA894',
       'GA928', 'NA040', 'NA055', 'NA059', 'NA093', 'NA094', 'NA147', 'NA151',
       'NA196', 'NA247', 'NA268', 'NA279', 'NA391', 'GA730', 'GA862', 'GA865',
       'GA878', 'GA881', 'NA033', 'NA039', 'NA053', 'NA063', 'NA102', 'NA109',
       'NA125', 'NA129', 'NA169', 'NA182', 'NA237', 'NA250', 'NA288', 'GA733',
       'GA738', 'GA960', 'NA074', 'NA084', 'NA092', 'NA132', 'NA225', 'NA327',
       'NA452'],
      dtype='object')

In [77]:
group_info = df.iloc[0]
df = df[1:]
df.index = df.loc[:, 'Label']
df = df.drop('Label', axis=1)
df

,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,A09_072_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
Label,,,,,,,,,,,,,,,,,,,,,
16659637,0.86314,1.21357,1.39364,1.53159,1.21563,1.39848,1.72079,0.72676,1.7319,1.33592,...,1.47654,1.29275,1.94308,1.63443,1.57844,1.56274,0.86799,1.99235,1.4993,0.97502
16664406,1.25862,1.39001,0.81366,1.08916,0.80341,1.31593,1.03926,1.35179,1.45531,1.29202,...,1.19542,1.61435,0.97501,1.37691,0.9932,0.71453,1.17141,0.77827,1.03242,0.64173
16665159,1.39798,1.37535,1.25231,1.55429,1.45725,1.22063,1.29021,1.1208,1.79425,1.38385,...,1.48516,1.40757,1.02428,1.09439,1.00745,1.13538,0.72924,1.30162,0.98353,1.06039
16665603,0.78432,0.71935,0.84219,1.44859,0.79489,0.74165,0.90227,1.13519,0.91891,0.9467,...,0.50991,0.39126,0.745,0.99561,0.39861,0.67146,0.34088,0.74965,0.57917,0.43188
16665833,1.31378,1.49305,1.09123,1.42688,1.28457,1.2193,1.41157,1.18806,1.34805,1.35665,...,1.46213,1.47872,1.16177,1.1885,1.32037,1.09998,0.87767,0.75427,1.27486,1.05456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17114322,1.13471,1.14963,1.25407,1.13812,1.28838,1.52156,1.05127,1.43208,1.41318,1.12681,...,0.8224,1.29065,1.17727,0.94143,1.54946,1.05201,1.05819,0.70263,1.30952,1.37988
17114768,1.49652,1.73469,1.43508,1.73391,1.49996,1.63881,1.63394,1.52747,1.63487,1.89024,...,1.89585,1.24586,1.43993,1.42443,1.69255,1.63538,0.89949,1.38476,1.5803,1.36799
17114783,1.34644,1.03372,1.26863,0.9554,1.54736,1.42942,1.57353,1.0607,1.52643,1.34789,...,1.64292,1.097,1.6315,1.21056,1.13699,0.89847,0.93103,0.5503,1.29747,1.07501
17114795,2.23753,2.17749,1.93852,2.11166,1.90734,2.09612,2.03066,1.92942,1.99992,1.87041,...,2.04646,1.84058,2.04844,1.92315,2.02821,2.03405,1.55866,1.66581,2.01897,1.82632
17116977,1.78634,2.79327,1.73966,1.66679,2.89374,1.74219,1.90706,1.74415,1.70309,2.87195,...,2.8296,1.81057,2.87942,1.78393,2.8699,2.86381,2.95828,2.95703,1.73277,2.87321

In [79]:
group_info = group_info[1:]
group_info

A08_045_C13a    group_1
A08_056_C13a    group_1
S09_053_C13a    group_1
A10_020_C13a    group_1
S09_104_C13a    group_1
                 ...
NA092           group_5
NA132           group_5
NA225           group_5
NA327           group_5
NA452           group_5
Name: 0, Length: 79, dtype: object

In [81]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [83]:
sample_list

['A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'A08_056_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',
 'S09_053_C13a_group_1',

In [85]:
feature_list

['16659637',
 '16664406',
 '16665159',
 '16665603',
 '16665833',
 '16666266',
 '16669374',
 '16674287',
 '16675443',
 '16678499',
 '16678880',
 '16679789',
 '16679791',
 '16682987',
 '16691368',
 '16693370',
 '16693753',
 '16697526',
 '16697664',
 '16698797',
 '16699874',
 '16701603',
 '16705006',
 '16707744',
 '16707757',
 '16708511',
 '16708984',
 '16710666',
 '16711795',
 '16712421',
 '16713948',
 '16714373',
 '16714491',
 '16714534',
 '16716369',
 '16717731',
 '16721175',
 '16721522',
 '16724706',
 '16730782',
 '16731020',
 '16734291',
 '16734818',
 '16734953',
 '16735325',
 '16736674',
 '16738371',
 '16738383',
 '16743249',
 '16743612',
 '16745507',
 '16745581',
 '16746904',
 '16757524',
 '16759924',
 '16761139',
 '16763470',
 '16765686',
 '16767362',
 '16767886',
 '16767892',
 '16769244',
 '16770469',
 '16770778',
 '16775247',
 '16775258',
 '16777427',
 '16778553',
 '16780087',
 '16780151',
 '16780203',
 '16781456',
 '16784067',
 '16784296',
 '16788538',
 '16788618',
 '16788620',
 '16788661',
 '16788681',
 '16788687',
 '16788697',
 '16788699',
 '16788737',
 '16788794',
 '16790917',
 '16793689',
 '16794295',
 '16796202',
 '16797121',
 '16797921',
 '16798132',
 '16798194',
 '16798212',
 '16798262',
 '16798282',
 '16798292',
 '16798307',
 '16798331',
 '16798343',
 '16798400',
 '16798406',
 '16798410',
 '16798412',
 '16798414',
 '16798418',
 '16798420',
 '16798424',
 '16798438',
 '16800989',
 '16801784',
 '16802102',
 '16805870',
 '16809807',
 '16817210',
 '16830193',
 '16830910',
 '16831334',
 '16832315',
 '16834158',
 '16834165',
 '16836866',
 '16842501',
 '16848262',
 '16852272',
 '16852617',
 '16854218',
 '16855244',
 '16855541',
 '16856168',
 '16860219',
 '16865034',
 '16865040',
 '16865046',
 '16865052',
 '16865074',
 '16865076',
 '16865078',
 '16865086',
 '16865102',
 '16869479',
 '16869721',
 '16870854',
 '16872871',
 '16872897',
 '16882055',
 '16885506',
 '16888669',
 '16892114',
 '16897506',
 '16897863',
 '16899527',
 '16900041',
 '16900201',
 '16901512',
 '16902373',
 '16902875',
 '16906350',
 '16907668',
 '16911257',
 '16914060',
 '16918172',
 '16919646',
 '16921478',
 '16921491',
 '16924300',
 '16924824',
 '16928664',
 '16929404',
 '16933468',
 '16937668',
 '16941942',
 '16942520',
 '16942804',
 '16943153',
 '16943161',
 '16943167',
 '16943169',
 '16943171',
 '16943756',
 '16943938',
 '16947022',
 '16949562',
 '16950335',
 '16953327',
 '16955255',
 '16956379',
 '16956541',
 '16956769',
 '16957013',
 '16959091',
 '16961194',
 '16962728',
 '16963507',
 '16965775',
 '16966169',
 '16967269',
 '16970749',
 '16972369',
 '16972702',
 '16973220',
 '16973493',
 '16975145',
 '16976524',
 '16976533',
 '16978107',
 '16979108',
 '16979587',
 '16979656',
 '16979851',
 '16980446',
 '16981037',
 '16981810',
 '16983603',
 '16986965',
 '16988441',
 '16988469',
 '16994207',
 '16996541',
 '16997058',
 '16997782',
 '16997851',
 '16997882',
 '16997990',
 '16998648',
 '16999347',
 '17001022',
 '17002743',
 '17004849',
 '17005211',
 '17009908',
 '17010193',
 '17010196',
 '17011032',
 '17011806',
 '17011814',
 '17012138',
 '17013100',
 '17013102',
 '17013217',
 '17013460',
 '17016363',
 '17016681',
 '17016692',
 '17017852',
 '17017885',
 '17023653',
 '17024556',
 '17043635',
 '17044199',
 '17046422',
 '17046834',
 '17047754',
 '17048223',
 '17048225',
 '17052509',
 '17055638',
 '17055649',
 '17056807',
 '17057051',
 '17058314',
 '17059824',
 '17062211',
 '17069240',
 '17070769',
 '17071445',
 '17072003',
 '17072523',
 '17074282',
 '17080786',
 '17080933',
 '17081518',
 '17085183',
 '17086561',
 '17086746',
 '17088821',
 '17089368',
 '17092642',
 '17092819',
 '17092831',
 '17092862',
 '17093971',
 '17094372',
 '17095410',
 '17096338',
 '17096722',
 '17096726',
 '17098640',
 '17100616',
 '17101304',
 '17101317',
 '17104120',
 '17104941',
 '17105249',
 '17105683',
 '17106677',
 '17107487',
 '17108232',
 '17109394',
 '17110026',
 '17111364',
 '17112265',
 '17114308',
 '17114322',
 '17114768',
 '17114783',
 '17114795',
 '17116977',
 '16659637',
 '16664406',
 '16665159',
 '16665603',
 '16665833',
 '16666266',
 '16669374',
 '16674287',
 '16675443',
 '16678499',
 '16678880',
 '16679789',
 '16679791',
 '16682987',
 '16691368',
 '16693370',
 '16693753',
 '16697526',
 '16697664',
 '16698797',
 '16699874',
 '16701603',
 '16705006',
 '16707744',
 '16707757',
 '16708511',
 '16708984',
 '16710666',
 '16711795',
 '16712421',
 '16713948',
 '16714373',
 '16714491',
 '16714534',
 '16716369',
 '16717731',
 '16721175',
 '16721522',
 '16724706',
 '16730782',
 '16731020',
 '16734291',
 '16734818',
 '16734953',
 '16735325',
 '16736674',
 '16738371',
 '16738383',
 '16743249',
 '16743612',
 '16745507',
 '16745581',
 '16746904',
 '16757524',
 '16759924',
 '16761139',
 '16763470',
 '16765686',
 '16767362',
 '16767886',
 '16767892',
 '16769244',
 '16770469',
 '16770778',
 '16775247',
 '16775258',
 '16777427',
 '16778553',
 '16780087',
 '16780151',
 '16780203',
 '16781456',
 '16784067',
 '16784296',
 '16788538',
 '16788618',
 '16788620',
 '16788661',
 '16788681',
 '16788687',
 '16788697',
 '16788699',
 '16788737',
 '16788794',
 '16790917',
 '16793689',
 '16794295',
 '16796202',
 '16797121',
 '16797921',
 '16798132',
 '16798194',
 '16798212',
 '16798262',
 '16798282',
 '16798292',
 '16798307',
 '16798331',
 '16798343',
 '16798400',
 '16798406',
 '16798410',
 '16798412',
 '16798414',
 '16798418',
 '16798420',
 '16798424',
 '16798438',
 '16800989',
 '16801784',
 '16802102',
 '16805870',
 '16809807',
 '16817210',
 '16830193',
 '16830910',
 '16831334',
 '16832315',
 '16834158',
 '16834165',
 '16836866',
 '16842501',
 '16848262',
 '16852272',
 '16852617',
 '16854218',
 '16855244',
 '16855541',
 '16856168',
 '16860219',
 '16865034',
 '16865040',
 '16865046',
 '16865052',
 '16865074',
 '16865076',
 '16865078',
 '16865086',
 '16865102',
 '16869479',
 '16869721',
 '16870854',
 '16872871',
 '16872897',
 '16882055',
 '16885506',
 '16888669',
 '16892114',
 '16897506',
 '16897863',
 '16899527',
 '16900041',
 '16900201',
 '16901512',
 '16902373',
 '16902875',
 '16906350',
 '16907668',
 '16911257',
 '16914060',
 '16918172',
 '16919646',
 '16921478',
 '16921491',
 '16924300',
 '16924824',
 '16928664',
 '16929404',
 '16933468',
 '16937668',
 '16941942',
 '16942520',
 '16942804',
 '16943153',
 '16943161',
 '16943167',
 '16943169',
 '16943171',
 '16943756',
 '16943938',
 '16947022',
 '16949562',
 '16950335',
 '16953327',
 '16955255',
 '16956379',
 '16956541',
 '16956769',
 '16957013',
 '16959091',
 '16961194',
 '16962728',
 '16963507',
 '16965775',
 '16966169',
 '16967269',
 '16970749',
 '16972369',
 '16972702',
 '16973220',
 '16973493',
 '16975145',
 '16976524',
 '16976533',
 '16978107',
 '16979108',
 '16979587',
 '16979656',
 '16979851',
 '16980446',
 '16981037',
 '16981810',
 '16983603',
 '16986965',
 '16988441',
 '16988469',
 '16994207',
 '16996541',
 '16997058',
 '16997782',
 '16997851',
 '16997882',
 '16997990',
 '16998648',
 '16999347',
 '17001022',
 '17002743',
 '17004849',
 '17005211',
 '17009908',
 '17010193',
 '17010196',
 '17011032',
 '17011806',
 '17011814',
 '17012138',
 '17013100',
 '17013102',
 '17013217',
 '17013460',
 '17016363',
 '17016681',
 '17016692',
 '17017852',
 '17017885',
 '17023653',
 '17024556',
 '17043635',
 '17044199',
 '17046422',
 '17046834',
 '17047754',
 '17048223',
 '17048225',
 '17052509',
 '17055638',
 '17055649',
 '17056807',
 '17057051',
 '17058314',
 '17059824',
 '17062211',
 '17069240',
 '17070769',
 '17071445',
 '17072003',
 '17072523',
 '17074282',
 '17080786',
 '17080933',
 '17081518',
 '17085183',
 '17086561',
 '17086746',
 '17088821',
 '17089368',
 '17092642',
 '17092819',
 '17092831',
 '17092862',
 '17093971',
 '17094372',
 '17095410',
 '17096338',
 '17096722',
 '17096726',
 '17098640',
 '17100616',
 '17101304',
 '17101317',
 '17104120',
 '17104941',
 '17105249',
 '17105683',
 '17106677',
 '17107487',
 '17108232',
 '17109394',
 '17110026',
 '17111364',
 '17112265',
 '17114308',
 '17114322',
 '17114768',
 '17114783',
 '17114795',
 '17116977',
 '16659637',
 '16664406',
 '16665159',
 '16665603',
 '16665833',
 '16666266',
 '16669374',
 '16674287',
 '16675443',
 '16678499',
 '16678880',
 '16679789',
 '16679791',
 '16682987',
 '16691368',
 '16693370',
 '16693753',
 '16697526',
 '16697664',
 '16698797',
 '16699874',
 '16701603',
 '16705006',
 '16707744',
 '16707757',
 '16708511',
 '16708984',
 '16710666',
 '16711795',
 '16712421',
 '16713948',
 '16714373',
 '16714491',
 '16714534',
 '16716369',
 '16717731',
 '16721175',
 '16721522',
 '16724706',
 '16730782',
 '16731020',
 '16734291',
 '16734818',
 '16734953',
 '16735325',
 '16736674',
 '16738371',
 '16738383',
 '16743249',
 '16743612',
 '16745507',
 '16745581',
 '16746904',
 '16757524',
 '16759924',
 '16761139',
 '16763470',
 '16765686',
 '16767362',
 '16767886',
 '16767892',
 '16769244',
 '16770469',
 '16770778',
 '16775247',
 '16775258',
 '16777427',
 '16778553',
 '16780087',
 '16780151',
 '16780203',
 '16781456',
 '16784067',
 '16784296',
 '16788538',
 '16788618',
 '16788620',
 '16788661',
 '16788681',
 '16788687',
 '16788697',
 '16788699',
 '16788737',
 '16788794',
 '16790917',
 '16793689',
 '16794295',
 '16796202',
 '16797121',
 '16797921',
 '16798132',
 '16798194',
 '16798212',
 '16798262',
 '16798282',
 '16798292',
 '16798307',
 '16798331',
 '16798343',
 '16798400',
 '16798406',
 '16798410',
 '16798412',
 '16798414',
 '16798418',
 '16798420',
 '16798424',
 '16798438',
 '16800989',
 '16801784',
 '16802102',
 '16805870',
 '16809807',
 '16817210',
 '16830193',
 '16830910',
 '16831334',
 '16832315',
 '16834158',
 '16834165',
 '16836866',
 '16842501',
 '16848262',
 '16852272',
 '16852617',
 '16854218',
 '16855244',
 '16855541',
 '16856168',
 '16860219',
 '16865034',
 '16865040',
 '16865046',
 '16865052',
 '16865074',
 '16865076',
 '16865078',
 '16865086',
 '16865102',
 '16869479',
 '16869721',
 '16870854',
 '16872871',
 '16872897',
 '16882055',
 '16885506',
 '16888669',
 '16892114',
 '16897506',
 '16897863',
 '16899527',
 '16900041',
 '16900201',
 '16901512',
 '16902373',
 '16902875',
 '16906350',
 '16907668',
 '16911257',
 '16914060',
 '16918172',
 '16919646',
 '16921478',
 '16921491',
 '16924300',
 '16924824',
 '16928664',
 '16929404',
 '16933468',
 '16937668',
 '16941942',
 '16942520',
 '16942804',
 '16943153',
 '16943161',
 '16943167',
 '16943169',
 '16943171',
 '16943756',
 '16943938',
 '16947022',
 '16949562',
 '16950335',
 '16953327',
 '16955255',
 '16956379',
 '16956541',
 '16956769',
 '16957013',
 '16959091',
 '16961194',
 '16962728',
 '16963507',
 '16965775',
 '16966169',
 '16967269',
 '16970749',
 '16972369',
 '16972702',
 '16973220',
 '16973493',
 '16975145',
 '16976524',
 '16976533',
 '16978107',
 '16979108',
 '16979587',
 '16979656',
 '16979851',
 '16980446',
 '16981037',
 '16981810',
 '16983603',
 '16986965',
 '16988441',
 '16988469',
 '16994207',
 '16996541',
 '16997058',
 '16997782',
 '16997851',
 '16997882',
 '16997990',
 '16998648',
 '16999347',
 '17001022',
 '17002743',
 '17004849',
 '17005211',
 '17009908',
 '17010193',
 '17010196',
 '17011032',
 '17011806',
 '17011814',
 '17012138',
 '17013100',
 '17013102',
 '17013217',
 '17013460',
 '17016363',
 '17016681',
 '17016692',
 '17017852',
 '17017885',
 '17023653',
 '17024556',
 '17043635',
 '17044199',
 '17046422',
 '17046834',
 '17047754',
 '17048223',
 '17048225',
 '17052509',
 '17055638',
 '17055649',
 '17056807',
 '17057051',
 '17058314',
 '17059824',
 '17062211',
 '17069240',
 '17070769',
 '17071445',
 '17072003',
 '17072523',
 '17074282',
 '17080786',
 '17080933',
 '17081518',
 '17085183',
 '17086561',
 '17086746',
 '17088821',
 '17089368',
 '17092642',
 '17092819',
 '17092831',
 '17092862',
 '17093971',
 '17094372',
 '17095410',
 '17096338',
 '17096722',
 '17096726',
 '17098640',
 '17100616',
 '17101304',
 '17101317',
 '17104120',
 '17104941',
 '17105249',
 '17105683',
 '17106677',
 '17107487',
 '17108232',
 '17109394',
 '17110026',
 '17111364',
 '17112265',
 '17114308',
 '17114322',
 '17114768',
 '17114783',
 '17114795',
 '17116977',
 '16659637',
 '16664406',
 '16665159',
 '16665603',
 '16665833',
 '16666266',
 '16669374',
 '16674287',
 '16675443',
 '16678499',
 '16678880',
 '16679789',
 '16679791',
 '16682987',
 '16691368',
 '16693370',
 '16693753',
 '16697526',
 '16697664',
 '16698797',
 '16699874',
 '16701603',
 '16705006',
 '16707744',
 '16707757',
 '16708511',
 '16708984',
 '16710666',
 '16711795',
 '16712421',
 '16713948',
 '16714373',
 '16714491',
 '16714534',
 '16716369',
 '16717731',
 '16721175',
 '16721522',
 '16724706',
 '16730782',
 '16731020',
 '16734291',
 '16734818',
 '16734953',
 '16735325',
 '16736674',
 '16738371',
 '16738383',
 '16743249',
 '16743612',
 '16745507',
 '16745581',
 '16746904',
 '16757524',
 '16759924',
 '16761139',
 '16763470',
 '16765686',
 '16767362',
 '16767886',
 '16767892',
 '16769244',
 '16770469',
 '16770778',
 '16775247',
 '16775258',
 '16777427',
 '16778553',
 '16780087',
 '16780151',
 '16780203',
 '16781456',
 '16784067',
 '16784296',
 '16788538',
 '16788618',
 '16788620',
 '16788661',
 '16788681',
 ...]

In [89]:
transcriptome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

transcriptome_data      # 307 * 79 = 24253

                     sample    group   feature    value
0      A08_045_C13a_group_1  group_1  16659637  0.86314
1      A08_045_C13a_group_1  group_1  16664406  1.25862
2      A08_045_C13a_group_1  group_1  16665159  1.39798
3      A08_045_C13a_group_1  group_1  16665603  0.78432
4      A08_045_C13a_group_1  group_1  16665833  1.31378
...                     ...      ...       ...      ...
24248         NA452_group_5  group_5  17114322  1.37988
24249         NA452_group_5  group_5  17114768  1.36799
24250         NA452_group_5  group_5  17114783  1.07501
24251         NA452_group_5  group_5  17114795  1.82632
24252         NA452_group_5  group_5  17116977  2.87321

[24253 rows x 4 columns]

In [91]:
transcriptome_data.to_csv("./transcriptome_last_mofa_norm_data.csv")

In [93]:
# methylome
df = pd.read_csv("methylome_last_norm_ordered_data.csv", low_memory=False)
df = pd.DataFrame(df)
df

,Label,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,cg25625370,0.06501,0.08648,0.46095,0.08412,0.03481,0.14438,0.06221,0.03951,0.03261,...,0.09166,0.05674,0.04764,0.12854,0.07356,0.07947,0.1223,0.04359,0.08014,0.03166
2,cg25980689,0.02864,0.03364,0.03401,0.02988,0.1837,0.02678,0.02646,0.02768,0.02998,...,0.0237,0.37318,0.02157,0.42138,0.03566,0.37218,0.031,0.25237,0.0324,0.02987
3,cg00767000,0.04263,0.04383,0.04931,0.04755,0.04223,0.03812,0.03435,0.04423,0.11724,...,0.03059,0.03342,0.22831,0.05804,0.43353,0.07275,0.04283,0.03169,0.04043,0.36656
4,cg15212418,0.0554,0.21352,0.06912,0.07401,0.09526,0.09171,0.03868,0.12111,0.12743,...,0.0634,0.06646,0.06608,0.05328,0.06654,0.12336,0.07282,0.08676,0.05398,0.08415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,rs6426327,0.05075,0.90271,0.03854,0.03851,0.03256,4.89449,0.89976,0.03721,0.90326,...,0.88165,0.98427,0.92875,0.04378,4.86644,0.03905,0.84795,0.92145,0.87834,0.89468
1472,rs7660805,0.03886,1.01893,0.96006,4.9103,0.03207,0.97078,0.03397,5.19613,0.99232,...,0.02394,4.75858,5.17984,4.26073,0.98113,0.03715,0.03059,0.93605,0.96709,0.03592
1473,rs9363764,0.04275,1.02898,1.04313,0.03747,1.07719,0.03778,0.03795,1.01553,1.04584,...,0.03307,1.07676,0.02593,0.04957,0.99346,0.95055,4.07512,0.04513,0.03664,0.03459
1474,rs348937,1.28268,0.05129,1.10316,0.05908,0.05194,4.4914,0.04596,0.0572,1.12741,...,0.04442,0.0423,0.03468,1.08585,0.06749,4.20449,0.06091,0.06018,4.52065,1.12554
1475,rs7746156,0.05167,0.99911,4.06328,1.02055,4.83632,1.08298,0.0473,0.97967,0.03566,...,0.05944,0.04683,0.03548,0.05479,0.04107,0.04652,0.05143,0.05318,0.0526,1.03721

In [95]:
df.columns

Index(['Label', 'A08_045_C13a', 'A08_056_C13a', 'S09_053_C13a', 'A10_020_C13a',
       'S09_104_C13a', 'A09_126_C13a', 'S09_072_C13a', 'S09_122_C13a',
       'S08_043_C13a', 'A09_072_C13a', 'GA694', 'GA818', 'GA825', 'GA828',
       'GA845', 'GA846', 'GA855', 'GA859', 'GA895', 'GA896', 'GA901', 'NA047',
       'NA048', 'NA050', 'NA160', 'NA161', 'NA291', 'NA344', 'NA390', 'NA423',
       'GA753', 'GA781', 'GA810', 'GA832', 'GA854', 'GA877', 'GA886', 'GA894',
       'GA928', 'NA040', 'NA055', 'NA059', 'NA093', 'NA094', 'NA147', 'NA151',
       'NA196', 'NA247', 'NA268', 'NA279', 'NA391', 'GA730', 'GA749', 'GA862',
       'GA865', 'GA878', 'GA881', 'NA033', 'NA039', 'NA053', 'NA063', 'NA102',
       'NA109', 'NA125', 'NA129', 'NA169', 'NA182', 'NA237', 'NA250', 'NA288',
       'GA733', 'GA738', 'GA960', 'NA074', 'NA084', 'NA092', 'NA132', 'NA225',
       'NA327', 'NA452'],
      dtype='object')

In [97]:
group_info = df.iloc[0]
df = df[1:]
df.index = df.loc[:, 'Label']
df = df.drop('Label', axis=1)
df

,A08_045_C13a,A08_056_C13a,S09_053_C13a,A10_020_C13a,S09_104_C13a,A09_126_C13a,S09_072_C13a,S09_122_C13a,S08_043_C13a,A09_072_C13a,...,GA733,GA738,GA960,NA074,NA084,NA092,NA132,NA225,NA327,NA452
Label,,,,,,,,,,,,,,,,,,,,,
cg25625370,0.06501,0.08648,0.46095,0.08412,0.03481,0.14438,0.06221,0.03951,0.03261,0.03935,...,0.09166,0.05674,0.04764,0.12854,0.07356,0.07947,0.1223,0.04359,0.08014,0.03166
cg25980689,0.02864,0.03364,0.03401,0.02988,0.1837,0.02678,0.02646,0.02768,0.02998,0.02795,...,0.0237,0.37318,0.02157,0.42138,0.03566,0.37218,0.031,0.25237,0.0324,0.02987
cg00767000,0.04263,0.04383,0.04931,0.04755,0.04223,0.03812,0.03435,0.04423,0.11724,0.04007,...,0.03059,0.03342,0.22831,0.05804,0.43353,0.07275,0.04283,0.03169,0.04043,0.36656
cg15212418,0.0554,0.21352,0.06912,0.07401,0.09526,0.09171,0.03868,0.12111,0.12743,0.05407,...,0.0634,0.06646,0.06608,0.05328,0.06654,0.12336,0.07282,0.08676,0.05398,0.08415
cg19515398,0.10917,0.08015,0.07033,0.09347,0.08341,0.06169,0.04148,0.05739,0.06576,0.07082,...,0.07811,0.07593,0.03635,0.06887,0.06971,0.08753,0.06761,0.08401,0.09298,0.06767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs6426327,0.05075,0.90271,0.03854,0.03851,0.03256,4.89449,0.89976,0.03721,0.90326,0.89824,...,0.88165,0.98427,0.92875,0.04378,4.86644,0.03905,0.84795,0.92145,0.87834,0.89468
rs7660805,0.03886,1.01893,0.96006,4.9103,0.03207,0.97078,0.03397,5.19613,0.99232,0.03643,...,0.02394,4.75858,5.17984,4.26073,0.98113,0.03715,0.03059,0.93605,0.96709,0.03592
rs9363764,0.04275,1.02898,1.04313,0.03747,1.07719,0.03778,0.03795,1.01553,1.04584,0.04326,...,0.03307,1.07676,0.02593,0.04957,0.99346,0.95055,4.07512,0.04513,0.03664,0.03459
rs348937,1.28268,0.05129,1.10316,0.05908,0.05194,4.4914,0.04596,0.0572,1.12741,1.18315,...,0.04442,0.0423,0.03468,1.08585,0.06749,4.20449,0.06091,0.06018,4.52065,1.12554
rs7746156,0.05167,0.99911,4.06328,1.02055,4.83632,1.08298,0.0473,0.97967,0.03566,0.05176,...,0.05944,0.04683,0.03548,0.05479,0.04107,0.04652,0.05143,0.05318,0.0526,1.03721

In [99]:
group_info = group_info[1:]
group_info

A08_045_C13a    group_1
A08_056_C13a    group_1
S09_053_C13a    group_1
A10_020_C13a    group_1
S09_104_C13a    group_1
                 ...
NA092           group_5
NA132           group_5
NA225           group_5
NA327           group_5
NA452           group_5
Name: 0, Length: 80, dtype: object

In [101]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [99]:
sample_list

['A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',
 'A08_045_C13a_group_1',

In [103]:
feature_list

['cg25625370',
 'cg25980689',
 'cg00767000',
 'cg15212418',
 'cg19515398',
 'cg16298867',
 'cg06749803',
 'cg16574807',
 'cg06545038',
 'cg14414865',
 'cg27169846',
 'cg18171715',
 'cg17504203',
 'cg00414890',
 'cg05237023',
 'cg24364070',
 'cg10387956',
 'cg15694117',
 'cg18232235',
 'cg22621695',
 'cg26764761',
 'cg23800435',
 'cg01050810',
 'cg13571460',
 'cg04386759',
 'cg01831771',
 'cg17723549',
 'cg20079298',
 'cg07178278',
 'cg09520857',
 'cg09655876',
 'cg09698465',
 'cg08103988',
 'cg21897676',
 'cg11342941',
 'cg05162523',
 'cg04633141',
 'cg15257930',
 'cg13752114',
 'cg05923197',
 'cg01079515',
 'cg17189020',
 'cg05475404',
 'cg05692422',
 'cg10243004',
 'cg24783935',
 'cg02820566',
 'cg20973476',
 'cg12951094',
 'cg00614959',
 'cg18337575',
 'cg11383134',
 'cg24519533',
 'cg18805164',
 'cg18853010',
 'cg08008636',
 'cg23353080',
 'cg22846391',
 'cg14677130',
 'cg13565624',
 'cg13632935',
 'cg13641185',
 'cg25735398',
 'cg16784970',
 'cg00810939',
 'cg11064039',
 'cg02198617',
 'cg13474370',
 'cg03653399',
 'cg19778375',
 'cg22691119',
 'cg22712681',
 'cg15715746',
 'cg02885007',
 'cg04454872',
 'cg06406458',
 'cg01628528',
 'cg01651570',
 'cg01676844',
 'cg07600533',
 'cg14215338',
 'cg10365886',
 'cg22494932',
 'cg16059038',
 'cg12045875',
 'cg27508960',
 'cg23182840',
 'cg23376390',
 'cg09565319',
 'cg08162124',
 'cg18447419',
 'cg09139047',
 'cg24289452',
 'cg05694749',
 'cg07028389',
 'cg12005649',
 'cg22526939',
 'cg11479503',
 'cg00400448',
 'cg16936421',
 'cg22262702',
 'cg22708961',
 'cg02004499',
 'cg05928290',
 'cg15472170',
 'cg24451422',
 'cg17266581',
 'cg26695758',
 'cg18251019',
 'cg21110052',
 'cg23473419',
 'cg03543448',
 'cg16237672',
 'cg13162615',
 'cg11717189',
 'cg17380795',
 'cg12500731',
 'cg04011897',
 'cg24002522',
 'cg03003335',
 'cg23651812',
 'cg22923398',
 'cg08311689',
 'cg08857906',
 'cg10864200',
 'cg16903122',
 'cg18202502',
 'cg19205926',
 'cg25445931',
 'cg26845390',
 'cg02976929',
 'cg05522011',
 'cg06003267',
 'cg04781796',
 'cg24449463',
 'cg06127335',
 'cg16550477',
 'cg09595050',
 'cg00889627',
 'cg23450357',
 'cg21477691',
 'cg27527593',
 'cg25840318',
 'cg20483857',
 'cg21679391',
 'cg12274407',
 'cg13362546',
 'cg20883195',
 'cg22999099',
 'cg15838301',
 'cg10244666',
 'cg07828340',
 'cg17052964',
 'cg19023977',
 'cg07303187',
 'cg03308399',
 'cg14496753',
 'cg16003687',
 'cg24077454',
 'cg02463440',
 'cg04785299',
 'cg16752592',
 'cg00964333',
 'cg27215475',
 'cg19486507',
 'cg03444184',
 'cg21540367',
 'cg18582362',
 'cg01224393',
 'cg22103003',
 'cg20146569',
 'cg23997132',
 'cg08941173',
 'cg03338924',
 'cg05062510',
 'cg17702455',
 'cg19873602',
 'cg26393261',
 'cg14862260',
 'cg19052042',
 'cg13737221',
 'cg12973548',
 'cg11445109',
 'cg08203849',
 'cg10951117',
 'cg03973420',
 'cg05904041',
 'cg22821289',
 'cg24231558',
 'cg16904399',
 'cg17983814',
 'cg05069728',
 'cg24521757',
 'cg12014181',
 'cg15260428',
 'cg05216211',
 'cg24251942',
 'cg13853046',
 'cg07618979',
 'cg03613822',
 'cg09570535',
 'cg23834812',
 'cg21840211',
 'cg04764687',
 'cg18141400',
 'cg11836154',
 'cg02113521',
 'cg11949518',
 'cg06657917',
 'cg13639582',
 'cg05390473',
 'cg19004594',
 'cg01707795',
 'cg01586208',
 'cg13262513',
 'cg24757533',
 'cg09247692',
 'cg01882058',
 'cg24522982',
 'cg11615743',
 'cg26877022',
 'cg02158065',
 'cg03704748',
 'cg14767529',
 'cg18550476',
 'cg16234831',
 'cg11674105',
 'cg23896871',
 'cg24488271',
 'cg01282504',
 'cg24785250',
 'cg14512630',
 'cg07968522',
 'cg02816447',
 'cg09514664',
 'cg01121464',
 'cg13556539',
 'cg15158031',
 'cg09860529',
 'cg07102406',
 'cg27461200',
 'cg27036347',
 'cg05827468',
 'cg02869163',
 'cg06238300',
 'cg25974442',
 'cg15656087',
 'cg03310027',
 'cg27380724',
 'cg11990813',
 'cg18155407',
 'cg12479899',
 'cg05917748',
 'cg00629117',
 'cg00451058',
 'cg08845486',
 'cg10000246',
 'cg03662545',
 'cg18624777',
 'cg01156747',
 'cg09763180',
 'cg24209115',
 'cg09122588',
 'cg21537187',
 'cg17999099',
 'cg27562174',
 'cg13695309',
 'cg18492799',
 'cg19508985',
 'cg06583077',
 'cg07571142',
 'cg13193179',
 'cg01391680',
 'cg06528862',
 'cg08763351',
 'cg14272706',
 'cg22185378',
 'cg21948655',
 'cg03035849',
 'cg16575408',
 'cg01957330',
 'cg04413148',
 'cg07597976',
 'cg01365152',
 'cg07403350',
 'cg08947964',
 'cg26709720',
 'cg06090864',
 'cg23959977',
 'cg26813508',
 'cg00455546',
 'cg05942349',
 'cg21104276',
 'cg13046237',
 'cg00329040',
 'cg23621496',
 'cg20363450',
 'cg20472752',
 'cg09532726',
 'cg23248424',
 'cg22622899',
 'cg20795680',
 'cg19767548',
 'cg21856695',
 'cg21469772',
 'cg03249561',
 'cg05627365',
 'cg05297328',
 'cg26697424',
 'cg22258388',
 'cg24875593',
 'cg19106893',
 'cg22135490',
 'cg22909333',
 'cg21358336',
 'cg24441899',
 'cg10867226',
 'cg10985479',
 'cg27063237',
 'cg21133261',
 'cg22591002',
 'cg06713830',
 'cg09721595',
 'cg02891314',
 'cg04282082',
 'cg14904079',
 'cg06989968',
 'cg22459517',
 'cg01179055',
 'cg01218414',
 'cg16216281',
 'cg03433313',
 'cg03513647',
 'cg06610254',
 'cg15059639',
 'cg15135166',
 'cg22843765',
 'cg14356213',
 'cg06182205',
 'cg07700233',
 'cg16932820',
 'cg00356500',
 'cg15727285',
 'cg13803647',
 'cg25764137',
 'cg06244897',
 'cg06533319',
 'cg16272324',
 'cg18406106',
 'cg05521315',
 'cg08186575',
 'cg15553776',
 'cg11218060',
 'cg24056954',
 'cg07615435',
 'cg04611087',
 'cg12659291',
 'cg17984198',
 'cg23736728',
 'cg04531182',
 'cg10877170',
 'cg01934390',
 'cg13295660',
 'cg26094470',
 'cg00917413',
 'cg13502686',
 'cg12392126',
 'cg18872420',
 'cg17242574',
 'cg18837922',
 'cg08368792',
 'cg01403557',
 'cg10669755',
 'cg12418213',
 'cg16912848',
 'cg07037964',
 'cg09013068',
 'cg06707197',
 'cg20318229',
 'cg00645431',
 'cg24088508',
 'cg25371048',
 'cg25485190',
 'cg02002523',
 'cg02771260',
 'cg09869665',
 'cg09996597',
 'cg11379809',
 'cg13862711',
 'cg11043221',
 'cg18358136',
 'cg03649429',
 'cg27354084',
 'cg27374734',
 'cg08556080',
 'cg08564027',
 'cg08653161',
 'cg08750459',
 'cg08776296',
 'cg25597117',
 'cg25709703',
 'cg00077566',
 'cg22867893',
 'cg26519051',
 'cg11037025',
 'cg05850870',
 'cg05906492',
 'cg10354017',
 'cg02954704',
 'cg05212259',
 'cg01144124',
 'cg23985820',
 'cg23403192',
 'cg23489630',
 'cg23495837',
 'cg17857456',
 'cg12797157',
 'cg07506458',
 'cg14332815',
 'cg14345464',
 'cg03571863',
 'cg18712599',
 'cg08041188',
 'cg04592785',
 'cg05111364',
 'cg13320211',
 'cg06198928',
 'cg24672310',
 'cg25155158',
 'cg01505705',
 'cg04553038',
 'cg27063617',
 'cg10587254',
 'cg15131001',
 'cg02905940',
 'cg14474522',
 'cg15103446',
 'cg05939300',
 'cg05953785',
 'cg27373156',
 'cg23076151',
 'cg09414774',
 'cg09503310',
 'cg13552668',
 'cg09769427',
 'cg09853393',
 'cg05437771',
 'cg05465951',
 'cg06107030',
 'cg19247601',
 'cg22234267',
 'cg09610179',
 'cg19585676',
 'cg03471711',
 'cg17537241',
 'cg21551951',
 'cg02057050',
 'cg02088761',
 'cg17661563',
 'cg05374263',
 'cg15882603',
 'cg15898343',
 'cg18835549',
 'cg18928442',
 'cg18974084',
 'cg19029797',
 'cg19126690',
 'cg10644638',
 'cg10691742',
 'cg10725542',
 'cg06655840',
 'cg01429604',
 'cg01475204',
 'cg01496381',
 'cg01498833',
 'cg07434806',
 'cg07711952',
 'cg18484110',
 'cg21629581',
 'cg07906019',
 'cg20870820',
 'cg17064981',
 'cg17147978',
 'cg17189664',
 'cg03867377',
 'cg03897729',
 'cg00398911',
 'cg13244672',
 'cg17698935',
 'cg17861914',
 'cg16100486',
 'cg04761931',
 'cg04798314',
 'cg18346506',
 'cg03363289',
 'cg03430065',
 'cg16961923',
 'cg14379000',
 'cg25221180',
 'cg04294438',
 'cg01591573',
 'cg01595178',
 'cg04454629',
 'cg09067993',
 'cg08234376',
 'cg16527105',
 'cg25052156',
 'cg14846874',
 'cg14904946',
 'cg20467217',
 'cg04839741',
 'cg14019859',
 'cg24882168',
 'cg02255808',
 'cg05225889',
 'cg03046482',
 'cg07214562',
 'cg15512879',
 'cg20498994',
 'cg20544479',
 'cg26451856',
 'cg09629758',
 'cg18466312',
 'cg12046064',
 'cg14921999',
 'cg05170020',
 'cg15044146',
 'cg03647307',
 'cg04453629',
 'cg06667758',
 'cg18148620',
 'cg20668001',
 'cg25448407',
 'cg07811074',
 'cg00178122',
 'cg08165340',
 'cg04755386',
 'cg18429374',
 'cg22985281',
 'cg25071794',
 'cg11139599',
 'cg14186321',
 'cg05997278',
 'cg04022560',
 'cg04098985',
 'cg11238518',
 'cg09125286',
 'cg22768676',
 'cg06148784',
 'cg00353407',
 'cg08786822',
 'cg04634182',
 'cg26828494',
 'cg19307391',
 'cg10607557',
 'cg13041470',
 'cg27311590',
 'cg23673397',
 'cg15882726',
 'cg03889251',
 'cg01291129',
 'cg02257700',
 'cg06848468',
 'cg11217934',
 'cg22814916',
 'cg02443816',
 'cg01101677',
 'cg00605523',
 'cg25350722',
 'cg01022189',
 'cg03959147',
 'cg27585147',
 'cg09811599',
 'cg23671626',
 'cg19455292',
 'cg13402298',
 'cg11398309',
 'cg22159109',
 'cg18575452',
 'cg10507762',
 'cg15004787',
 'cg00389619',
 'cg10156706',
 'cg21445764',
 'cg21331845',
 'cg11081809',
 'cg04636251',
 'cg01765322',
 'cg00998735',
 'cg21908960',
 'cg10362527',
 'cg02105087',
 'cg27292870',
 'cg10174575',
 'cg23659308',
 'cg06870484',
 'cg21475003',
 'cg26319363',
 'cg26308992',
 'cg10089413',
 'cg10506618',
 'cg02033040',
 'cg11655389',
 'cg11380092',
 'cg00554858',
 'cg07166795',
 'cg24429037',
 'cg23946548',
 'cg03446399',
 'cg05777410',
 'cg09060784',
 'cg14862385',
 'cg13647486',
 'cg13691824',
 'cg07278174',
 'cg11371162',
 'cg11430766',
 'cg08010337',
 'cg08295072',
 'cg00097088',
 'cg00019826',
 'cg03521085',
 'cg06665095',
 'cg08370506',
 'cg04348561',
 'cg01421044',
 'cg18677812',
 'cg19530800',
 'cg21958394',
 'cg05672616',
 'cg05652528',
 'cg24673955',
 'cg19270089',
 'cg16057532',
 'cg08548315',
 'cg21972741',
 'cg27511630',
 'cg00178877',
 'cg00119241',
 'cg00152878',
 'cg02154531',
 'cg19729188',
 'cg17416233',
 'cg01114138',
 'cg19079233',
 'cg07418777',
 'cg26835568',
 'cg00610205',
 'cg02032984',
 'cg21513803',
 'cg03920522',
 'cg22394948',
 'cg08258915',
 'cg03722185',
 'cg16819768',
 'cg07180897',
 'cg14412639',
 'cg15676292',
 'cg11514604',
 'cg25315991',
 'cg04086327',
 'cg16667459',
 'cg18762825',
 'cg07290269',
 'cg13676726',
 'cg05369766',
 'cg10482532',
 'cg21083936',
 'cg08621168',
 'cg02918166',
 'cg04225508',
 'cg25548350',
 'cg23932711',
 'cg22690322',
 'cg05032595',
 'cg04306248',
 'cg26496920',
 'cg24849475',
 'cg07068181',
 'cg10221654',
 'cg14136372',
 'cg19992785',
 'cg06891613',
 'cg21440284',
 'cg01409873',
 'cg10494638',
 'cg02172885',
 'cg03812751',
 'cg01904886',
 'cg13209192',
 'cg18671115',
 'cg05134857',
 'cg03065803',
 'cg06669598',
 'cg20347648',
 'cg10390762',
 'cg12955305',
 'cg20093020',
 'cg14233716',
 'cg05188488',
 'cg09179397',
 'cg19436700',
 'cg07454788',
 'cg08604594',
 'cg06728077',
 'cg03220363',
 'cg27135936',
 'cg11930274',
 'cg21178568',
 'cg13468804',
 'cg22562569',
 'cg00315816',
 'cg25511725',
 'cg08272591',
 'cg04426607',
 'cg03849834',
 'cg12294678',
 'cg06145508',
 'cg07420867',
 'cg08112356',
 'cg26014281',
 'cg01145442',
 'cg10596483',
 'cg19098690',
 'cg14415857',
 'cg27229586',
 'cg09005399',
 'cg14528451',
 'cg13486404',
 'cg09077672',
 'cg25687777',
 'cg15476885',
 'cg22236485',
 'cg14715383',
 'cg07005960',
 'cg09869811',
 'cg13689497',
 'cg02513556',
 'cg25824218',
 'cg18290190',
 'cg18098534',
 'cg14354881',
 'cg10226073',
 'cg14647989',
 'cg16989086',
 'cg10476347',
 'cg13124801',
 'cg10273072',
 'cg10293824',
 'cg11140875',
 'cg25388939',
 'cg07141545',
 'cg00781839',
 'cg13990980',
 'cg16668397',
 'cg02341645',
 'cg07092293',
 'cg06661612',
 'cg02719221',
 'cg01096587',
 'cg18691133',
 'cg05135033',
 'cg05444556',
 'cg03381007',
 'cg00151170',
 'cg18998002',
 'cg05726756',
 'cg02311180',
 'cg10284310',
 'cg19874095',
 'cg22615910',
 'cg00128718',
 'cg10064312',
 'cg11666515',
 'cg26933384',
 'cg25271770',
 'cg11881861',
 'cg12582555',
 'cg25357666',
 'cg25524108',
 'cg17199181',
 'cg02391633',
 'cg04461311',
 'cg22825473',
 'cg00855396',
 'cg26175287',
 'cg10943931',
 'cg04395006',
 'cg07876611',
 'cg18048953',
 'cg27018309',
 'cg27075786',
 'cg24943736',
 'cg21013395',
 'cg09743906',
 'cg22696944',
 'cg08628428',
 'cg17860133',
 'cg26256771',
 'cg19366479',
 'cg19037241',
 'cg20045696',
 'cg16887110',
 'cg01525839',
 'cg19899561',
 'cg23467628',
 'cg18284050',
 'cg24190979',
 'cg18047214',
 'cg05207870',
 'cg10980860',
 'cg05222618',
 'cg15251217',
 'cg23554922',
 'cg16598774',
 'cg09891332',
 'cg19104037',
 'cg25610945',
 'cg13577755',
 'cg26584465',
 'cg23076547',
 'cg01363387',
 'cg20186982',
 'cg15684003',
 'cg08879722',
 'cg24224638',
 'cg20082916',
 'cg03947687',
 'cg20020625',
 'cg21329470',
 'cg23583501',
 'cg23670702',
 'cg22729091',
 'cg08977827',
 'cg04897744',
 'cg25984203',
 'cg03838944',
 'cg20059427',
 'cg10984515',
 'cg12039910',
 'cg16361921',
 'cg09184537',
 'cg04631440',
 'cg07160992',
 'cg02756136',
 'cg25486412',
 'cg21294295',
 'cg24676276',
 'cg23568161',
 'cg05853394',
 'cg23042158',
 'cg00005249',
 'cg03860010',
 'cg18602829',
 'cg01705981',
 'cg10508018',
 'cg27418891',
 'cg23366754',
 'cg10694456',
 'cg07526131',
 'cg14606439',
 'cg09251548',
 'cg08286630',
 'cg27249778',
 'cg00879723',
 'cg00308904',
 'cg14614789',
 'cg22878634',
 'cg22408844',
 'cg25002963',
 'cg22704163',
 'cg13758111',
 'cg01053354',
 'cg06993367',
 'cg08024468',
 'cg10936998',
 'cg12365675',
 'cg22998472',
 'cg12334758',
 'cg24116081',
 'cg11571098',
 'cg23202853',
 'cg07374666',
 'cg18702850',
 'cg22664564',
 'cg21200055',
 'cg22711847',
 'cg10081084',
 'cg22281761',
 'cg11627090',
 'cg22640553',
 'cg09007881',
 'cg22223109',
 'cg18809403',
 'cg05400446',
 'cg24819596',
 'cg09214323',
 'cg01003893',
 'cg09208012',
 'cg01920890',
 'cg14476057',
 'cg04345744',
 'cg11722504',
 'cg05330301',
 'cg11240813',
 'cg15997319',
 'cg08679702',
 'cg14596477',
 'cg25558228',
 'cg11853350',
 'cg17539777',
 'cg09684899',
 'cg25913970',
 'cg09409594',
 'cg04067970',
 'cg26430004',
 'cg05003619',
 'cg12080266',
 'cg07195891',
 'cg05642964',
 'cg06725641',
 'cg06937654',
 'cg19227294',
 'cg10651174',
 'cg15648058',
 'cg11654142',
 'cg13278328',
 'cg14475362',
 'cg06578230',
 'cg10154189',
 'cg03816966',
 'cg19316074',
 'cg20569482',
 'cg22891632',
 'cg15124400',
 'cg12304447',
 'cg21015078',
 'cg20055392',
 'cg02969609',
 'cg09422970',
 'cg26801741',
 'cg03412823',
 'cg05004137',
 'cg25665103',
 'cg23102351',
 'cg06698547',
 'cg11877490',
 'cg23411027',
 'cg26269565',
 'cg24517995',
 'cg21785376',
 'cg07725712',
 'cg18390724',
 'cg25182828',
 'cg19121956',
 'cg25447813',
 'cg17947181',
 'cg01672655',
 'cg26054541',
 'cg16263148',
 'cg06059109',
 'cg03252488',
 'cg23114830',
 'cg11691705',
 'cg05780479',
 'cg22771850',
 'cg27400458',
 'cg04921708',
 'cg21063107',
 'cg00629612',
 'cg22750284',
 'cg21863379',
 'cg13643885',
 'cg17171826',
 'cg05041591',
 'cg06853088',
 'cg20296174',
 'cg15124946',
 'cg22312534',
 'cg01392238',
 'cg22306690',
 'cg23071707',
 'cg00038681',
 'cg23024108',
 'cg24214626',
 'cg19799745',
 'cg17769356',
 'cg08986950',
 'cg02054390',
 'cg02053175',
 'cg00982543',
 'cg10870282',
 'cg19613533',
 'cg09659380',
 'cg24690092',
 'cg13529673',
 'cg02970458',
 'cg03063030',
 'cg17764313',
 'cg10436837',
 ...]

In [107]:
methylome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

methylome_data      # 1475 * 79 = 116525 (filtered) # 700419 * 79 = 55332390 (raw)  # 1475 * 80 = 118000 (ordered)

                      sample    group     feature    value
0       A08_045_C13a_group_1  group_1  cg25625370  0.06501
1       A08_045_C13a_group_1  group_1  cg25980689  0.02864
2       A08_045_C13a_group_1  group_1  cg00767000  0.04263
3       A08_045_C13a_group_1  group_1  cg15212418   0.0554
4       A08_045_C13a_group_1  group_1  cg19515398  0.10917
...                      ...      ...         ...      ...
117995         NA452_group_5  group_5   rs6426327  0.89468
117996         NA452_group_5  group_5   rs7660805  0.03592
117997         NA452_group_5  group_5   rs9363764  0.03459
117998         NA452_group_5  group_5    rs348937  1.12554
117999         NA452_group_5  group_5   rs7746156  1.03721

[118000 rows x 4 columns]

In [109]:
methylome_data.to_csv("./methylome_last_mofa_norm_data.csv")

In [109]:
# View 추가 
metabolome_data2 = metabolome_data

In [111]:
metabolome_data2.insert(3, 'view', 'metabolome')

In [113]:
metabolome_data2

                     sample    group  feature        view        value
0      A08_045_C13a_group_1  group_1     met1  metabolome  19.52402565
1      A08_045_C13a_group_1  group_1     met2  metabolome  14.41925066
2      A08_045_C13a_group_1  group_1     met4  metabolome   24.6410808
3      A08_045_C13a_group_1  group_1     met5  metabolome  17.90787554
4      A08_045_C13a_group_1  group_1     met6  metabolome  17.90787554
...                     ...      ...      ...         ...          ...
59403         NA452_group_5  group_5  met1140  metabolome  16.82116718
59404         NA452_group_5  group_5  met1141  metabolome  20.72482181
59405         NA452_group_5  group_5  met1142  metabolome  16.23427747
59406         NA452_group_5  group_5  met1143  metabolome  17.51812164
59407         NA452_group_5  group_5  met1144  metabolome   15.9456557

[59408 rows x 5 columns]

In [ ]:
# Add view 
metabolome_data.insert(3, 'view', 'metabolome')
proteome_data.insert(3, 'view', 'proteome')

In [113]:
transcriptome_data.insert(3, 'view', 'transcriptome')

In [115]:
methylome_data.insert(3, 'view', 'methylome')

In [117]:
metabolome_data.to_csv("./metabolome_last_mofa_data.csv")

In [119]:
proteome_data.to_csv("./proteome_last_mofa_data.csv")

In [121]:
transcriptome_data.to_csv("./transcriptome_last_mofa_data.csv")

In [123]:
methylome_data.to_csv("./methylome_last_mofa_data.csv")

In [125]:
# feature update
metabolome_data['feature'] = metabolome_data['feature'] + '_' + metabolome_data['view']

In [127]:
metabolome_data

,sample,group,feature,view,value
0,A08_045_C13a_group_1,group_1,met1_metabolome,metabolome,19.52402565
1,A08_045_C13a_group_1,group_1,met2_metabolome,metabolome,14.41925066
2,A08_045_C13a_group_1,group_1,met4_metabolome,metabolome,24.6410808
3,A08_045_C13a_group_1,group_1,met5_metabolome,metabolome,17.90787554
4,A08_045_C13a_group_1,group_1,met6_metabolome,metabolome,17.90787554
...,...,...,...,...,...
67675,NA452_group_5,group_5,met1140_metabolome,metabolome,16.82116718
67676,NA452_group_5,group_5,met1141_metabolome,metabolome,20.72482181
67677,NA452_group_5,group_5,met1142_metabolome,metabolome,16.23427747
67678,NA452_group_5,group_5,met1143_metabolome,metabolome,17.51812164
67679,NA452_group_5,group_5,met1144_metabolome,metabolome,15.9456557

In [129]:
proteome_data['feature'] = proteome_data['feature'] + '_' + proteome_data['view']

In [131]:
proteome_data

,sample,group,feature,view,value
0,A08_045_C13a_group_1,group_1,P05154_proteome,proteome,10.49738622
1,A08_045_C13a_group_1,group_1,P02786_proteome,proteome,5.970053052
2,A08_045_C13a_group_1,group_1,Q9Y490_proteome,proteome,5.582031801
3,A08_045_C13a_group_1,group_1,Q15063-5_proteome,proteome,4.751896795
4,A08_045_C13a_group_1,group_1,P02730_proteome,proteome,5.285658419
...,...,...,...,...,...
66315,NA452_group_5,group_5,P52701;P52701-3;P52701-4_proteome,proteome,5.800511679
66316,NA452_group_5,group_5,Q9C0G6_proteome,proteome,6.990750691
66317,NA452_group_5,group_5,Q9Y5R5_proteome,proteome,12.73110049
66318,NA452_group_5,group_5,Q01581_proteome,proteome,3.976904316
66319,NA452_group_5,group_5,P01814_proteome,proteome,5.121405042

In [133]:
transcriptome_data['feature'] = transcriptome_data['feature'] + '_' + transcriptome_data['view']

In [135]:
transcriptome_data

,sample,group,feature,view,value
0,A08_045_C13a_group_1,group_1,16659637_transcriptome,transcriptome,0.86314
1,A08_045_C13a_group_1,group_1,16664406_transcriptome,transcriptome,1.25862
2,A08_045_C13a_group_1,group_1,16665159_transcriptome,transcriptome,1.39798
3,A08_045_C13a_group_1,group_1,16665603_transcriptome,transcriptome,0.78432
4,A08_045_C13a_group_1,group_1,16665833_transcriptome,transcriptome,1.31378
...,...,...,...,...,...
24248,NA452_group_5,group_5,17114322_transcriptome,transcriptome,1.37988
24249,NA452_group_5,group_5,17114768_transcriptome,transcriptome,1.36799
24250,NA452_group_5,group_5,17114783_transcriptome,transcriptome,1.07501
24251,NA452_group_5,group_5,17114795_transcriptome,transcriptome,1.82632
24252,NA452_group_5,group_5,17116977_transcriptome,transcriptome,2.87321

In [137]:
methylome_data['feature'] = methylome_data['feature'] + '_' + methylome_data['view']

In [139]:
methylome_data

,sample,group,feature,view,value
0,A08_045_C13a_group_1,group_1,cg25625370_methylome,methylome,0.06501
1,A08_045_C13a_group_1,group_1,cg25980689_methylome,methylome,0.02864
2,A08_045_C13a_group_1,group_1,cg00767000_methylome,methylome,0.04263
3,A08_045_C13a_group_1,group_1,cg15212418_methylome,methylome,0.0554
4,A08_045_C13a_group_1,group_1,cg19515398_methylome,methylome,0.10917
...,...,...,...,...,...
117995,NA452_group_5,group_5,rs6426327_methylome,methylome,0.89468
117996,NA452_group_5,group_5,rs7660805_methylome,methylome,0.03592
117997,NA452_group_5,group_5,rs9363764_methylome,methylome,0.03459
117998,NA452_group_5,group_5,rs348937_methylome,methylome,1.12554
117999,NA452_group_5,group_5,rs7746156_methylome,methylome,1.03721

In [141]:
sample_list[-5:-1]

['NA452_group_5', 'NA452_group_5', 'NA452_group_5', 'NA452_group_5']

In [143]:
omics1 = pd.concat([proteome_data, metabolome_data])

In [145]:
omics2 = pd.concat([omics1, transcriptome_data])

In [147]:
omics3 = pd.concat([omics2, methylome_data])

In [151]:
omics3  # 276253 x 5

,sample,group,feature,view,value
0,A08_045_C13a_group_1,group_1,P05154_proteome,proteome,10.49738622
1,A08_045_C13a_group_1,group_1,P02786_proteome,proteome,5.970053052
2,A08_045_C13a_group_1,group_1,Q9Y490_proteome,proteome,5.582031801
3,A08_045_C13a_group_1,group_1,Q15063-5_proteome,proteome,4.751896795
4,A08_045_C13a_group_1,group_1,P02730_proteome,proteome,5.285658419
...,...,...,...,...,...
117995,NA452_group_5,group_5,rs6426327_methylome,methylome,0.89468
117996,NA452_group_5,group_5,rs7660805_methylome,methylome,0.03592
117997,NA452_group_5,group_5,rs9363764_methylome,methylome,0.03459
117998,NA452_group_5,group_5,rs348937_methylome,methylome,1.12554
117999,NA452_group_5,group_5,rs7746156_methylome,methylome,1.03721

In [153]:
omics3.to_csv("./multiome_last_mofa-data.csv")

In [155]:
omics = pd.read_csv("./multiome_last_mofa-data.csv", low_memory=False)
omics = pd.DataFrame(omics)

In [ ]:
import pandas as pd
import re

# group_1 (unexposed normal group) was deleted. 
omics_comp1 = omics[omics['group'] != 'group_1'].copy()

In [159]:
omics_comp1

,Unnamed: 0,sample,group,feature,view,value
8290,8290,GA694_group_2,group_2,P05154_proteome,proteome,11.044280
8291,8291,GA694_group_2,group_2,P02786_proteome,proteome,5.926753
8292,8292,GA694_group_2,group_2,Q9Y490_proteome,proteome,6.834279
8293,8293,GA694_group_2,group_2,Q15063-5_proteome,proteome,4.845327
8294,8294,GA694_group_2,group_2,P02730_proteome,proteome,6.662301
...,...,...,...,...,...,...
276248,117995,NA452_group_5,group_5,rs6426327_methylome,methylome,0.894680
276249,117996,NA452_group_5,group_5,rs7660805_methylome,methylome,0.035920
276250,117997,NA452_group_5,group_5,rs9363764_methylome,methylome,0.034590
276251,117998,NA452_group_5,group_5,rs348937_methylome,methylome,1.125540
276252,117999,NA452_group_5,group_5,rs7746156_methylome,methylome,1.037210

In [ ]:
# Change group
omics_comp1.loc[:, 'group'] = omics_comp1['group'].replace({
    'group_2': 'group_1',
    'group_3': 'group_2',
    'group_4': 'group_2',
    'group_5': 'group_3'
})

In [163]:
omics_comp1

,Unnamed: 0,sample,group,feature,view,value
8290,8290,GA694_group_2,group_1,P05154_proteome,proteome,11.044280
8291,8291,GA694_group_2,group_1,P02786_proteome,proteome,5.926753
8292,8292,GA694_group_2,group_1,Q9Y490_proteome,proteome,6.834279
8293,8293,GA694_group_2,group_1,Q15063-5_proteome,proteome,4.845327
8294,8294,GA694_group_2,group_1,P02730_proteome,proteome,6.662301
...,...,...,...,...,...,...
276248,117995,NA452_group_5,group_3,rs6426327_methylome,methylome,0.894680
276249,117996,NA452_group_5,group_3,rs7660805_methylome,methylome,0.035920
276250,117997,NA452_group_5,group_3,rs9363764_methylome,methylome,0.034590
276251,117998,NA452_group_5,group_3,rs348937_methylome,methylome,1.125540
276252,117999,NA452_group_5,group_3,rs7746156_methylome,methylome,1.037210

In [ ]:
# Change group information of sample column - using regular expression
def update_sample(sample_name):
    match = re.search(r'_group_(\d+)', sample_name)
    if match:
        group_number = int(match.group(1))
        if group_number == 2:
            new_group_number = 1
        elif group_number in [3, 4]:
            new_group_number = 2
        elif group_number == 5:
            new_group_number = 3
        else:
            return sample_name
        return re.sub(r'_group_\d+', f'_group_{new_group_number}', sample_name)
    return sample_name

omics_comp1.loc[:, 'sample'] = omics_comp1['sample'].apply(update_sample)

print(omics_comp1)

        Unnamed: 0         sample    group              feature       view  \
8290          8290  GA694_group_1  group_1      P05154_proteome   proteome
8291          8291  GA694_group_1  group_1      P02786_proteome   proteome
8292          8292  GA694_group_1  group_1      Q9Y490_proteome   proteome
8293          8293  GA694_group_1  group_1    Q15063-5_proteome   proteome
8294          8294  GA694_group_1  group_1      P02730_proteome   proteome
...            ...            ...      ...                  ...        ...
276248      117995  NA452_group_3  group_3  rs6426327_methylome  methylome
276249      117996  NA452_group_3  group_3  rs7660805_methylome  methylome
276250      117997  NA452_group_3  group_3  rs9363764_methylome  methylome
276251      117998  NA452_group_3  group_3   rs348937_methylome  methylome
276252      117999  NA452_group_3  group_3  rs7746156_methylome  methylome

            value
8290    11.044280
8291     5.926753
8292     6.834279
8293     4.845327
8294     6.662301
...           ...
276248   0.894680
276249   0.035920
276250   0.034590
276251   1.125540
276252   1.037210

[235103 rows x 6 columns]

In [167]:
omics_comp1 = omics_comp1.drop(columns=['Unnamed: 0'])
omics_comp1.index = range(1, len(omics_comp1)+1)

print(omics_comp1)

               sample    group              feature       view      value
1       GA694_group_1  group_1      P05154_proteome   proteome  11.044280
2       GA694_group_1  group_1      P02786_proteome   proteome   5.926753
3       GA694_group_1  group_1      Q9Y490_proteome   proteome   6.834279
4       GA694_group_1  group_1    Q15063-5_proteome   proteome   4.845327
5       GA694_group_1  group_1      P02730_proteome   proteome   6.662301
...               ...      ...                  ...        ...        ...
235099  NA452_group_3  group_3  rs6426327_methylome  methylome   0.894680
235100  NA452_group_3  group_3  rs7660805_methylome  methylome   0.035920
235101  NA452_group_3  group_3  rs9363764_methylome  methylome   0.034590
235102  NA452_group_3  group_3   rs348937_methylome  methylome   1.125540
235103  NA452_group_3  group_3  rs7746156_methylome  methylome   1.037210

[235103 rows x 5 columns]

In [169]:
omics_comp1.to_csv("./multiome_last_comp1_data.csv")

In [ ]:
# comp2 (vs 2 groups)
import re
# exclude group_1 (unexposed normal group), group_5 (severe lung injury)) data
omics_comp2 = omics[~omics['group'].isin(['group_1', 'group_5'])].copy()

In [173]:
omics_comp2

,Unnamed: 0,sample,group,feature,view,value
8290,8290,GA694_group_2,group_2,P05154_proteome,proteome,11.044280
8291,8291,GA694_group_2,group_2,P02786_proteome,proteome,5.926753
8292,8292,GA694_group_2,group_2,Q9Y490_proteome,proteome,6.834279
8293,8293,GA694_group_2,group_2,Q15063-5_proteome,proteome,4.845327
8294,8294,GA694_group_2,group_2,P02730_proteome,proteome,6.662301
...,...,...,...,...,...,...
261498,103245,NA288_group_4,group_4,rs6426327_methylome,methylome,0.898350
261499,103246,NA288_group_4,group_4,rs7660805_methylome,methylome,0.034510
261500,103247,NA288_group_4,group_4,rs9363764_methylome,methylome,1.040480
261501,103248,NA288_group_4,group_4,rs348937_methylome,methylome,0.057300
261502,103249,NA288_group_4,group_4,rs7746156_methylome,methylome,1.030100

In [ ]:
# Change group
omics_comp2.loc[:, 'group'] = omics_comp2['group'].replace({
    'group_2': 'group_1',
    'group_3': 'group_2',
    'group_4': 'group_2',
})

In [177]:
omics_comp2

,Unnamed: 0,sample,group,feature,view,value
8290,8290,GA694_group_2,group_1,P05154_proteome,proteome,11.044280
8291,8291,GA694_group_2,group_1,P02786_proteome,proteome,5.926753
8292,8292,GA694_group_2,group_1,Q9Y490_proteome,proteome,6.834279
8293,8293,GA694_group_2,group_1,Q15063-5_proteome,proteome,4.845327
8294,8294,GA694_group_2,group_1,P02730_proteome,proteome,6.662301
...,...,...,...,...,...,...
261498,103245,NA288_group_4,group_2,rs6426327_methylome,methylome,0.898350
261499,103246,NA288_group_4,group_2,rs7660805_methylome,methylome,0.034510
261500,103247,NA288_group_4,group_2,rs9363764_methylome,methylome,1.040480
261501,103248,NA288_group_4,group_2,rs348937_methylome,methylome,0.057300
261502,103249,NA288_group_4,group_2,rs7746156_methylome,methylome,1.030100

In [ ]:
# Change group information of sample column - using regular expression
def update_sample(sample_name):
    match = re.search(r'_group_(\d+)', sample_name)
    if match:
        group_number = int(match.group(1))
        if group_number == 2:
            new_group_number = 1
        elif group_number in [3, 4]:
            new_group_number = 2
        else:
            return sample_name
        return re.sub(r'_group_\d+', f'_group_{new_group_number}', sample_name)
    return sample_name

omics_comp2.loc[:, 'sample'] = omics_comp2['sample'].apply(update_sample)

print(omics_comp2)

        Unnamed: 0         sample    group              feature       view  \
8290          8290  GA694_group_1  group_1      P05154_proteome   proteome
8291          8291  GA694_group_1  group_1      P02786_proteome   proteome
8292          8292  GA694_group_1  group_1      Q9Y490_proteome   proteome
8293          8293  GA694_group_1  group_1    Q15063-5_proteome   proteome
8294          8294  GA694_group_1  group_1      P02730_proteome   proteome
...            ...            ...      ...                  ...        ...
261498      103245  NA288_group_2  group_2  rs6426327_methylome  methylome
261499      103246  NA288_group_2  group_2  rs7660805_methylome  methylome
261500      103247  NA288_group_2  group_2  rs9363764_methylome  methylome
261501      103248  NA288_group_2  group_2   rs348937_methylome  methylome
261502      103249  NA288_group_2  group_2  rs7746156_methylome  methylome

            value
8290    11.044280
8291     5.926753
8292     6.834279
8293     4.845327
8294     6.662301
...           ...
261498   0.898350
261499   0.034510
261500   1.040480
261501   0.057300
261502   1.030100

[201473 rows x 6 columns]

In [181]:
omics_comp2 = omics_comp2.drop(columns=['Unnamed: 0'])
omics_comp2.index = range(1, len(omics_comp2)+1)

print(omics_comp2)

               sample    group              feature       view      value
1       GA694_group_1  group_1      P05154_proteome   proteome  11.044280
2       GA694_group_1  group_1      P02786_proteome   proteome   5.926753
3       GA694_group_1  group_1      Q9Y490_proteome   proteome   6.834279
4       GA694_group_1  group_1    Q15063-5_proteome   proteome   4.845327
5       GA694_group_1  group_1      P02730_proteome   proteome   6.662301
...               ...      ...                  ...        ...        ...
201469  NA288_group_2  group_2  rs6426327_methylome  methylome   0.898350
201470  NA288_group_2  group_2  rs7660805_methylome  methylome   0.034510
201471  NA288_group_2  group_2  rs9363764_methylome  methylome   1.040480
201472  NA288_group_2  group_2   rs348937_methylome  methylome   0.057300
201473  NA288_group_2  group_2  rs7746156_methylome  methylome   1.030100

[201473 rows x 5 columns]

In [183]:
omics_comp2.to_csv("./multiome_last_comp2_data.csv")

In [185]:
omics_comp3 = omics_comp2[omics_comp2['group'] != 'group_1'].copy()

In [187]:
omics_comp3

               sample    group              feature       view      value
16581   GA753_group_2  group_2      P05154_proteome   proteome  10.922110
16582   GA753_group_2  group_2      P02786_proteome   proteome   5.638221
16583   GA753_group_2  group_2      Q9Y490_proteome   proteome   9.349634
16584   GA753_group_2  group_2    Q15063-5_proteome   proteome   4.609786
16585   GA753_group_2  group_2      P02730_proteome   proteome   6.381731
...               ...      ...                  ...        ...        ...
201469  NA288_group_2  group_2  rs6426327_methylome  methylome   0.898350
201470  NA288_group_2  group_2  rs7660805_methylome  methylome   0.034510
201471  NA288_group_2  group_2  rs9363764_methylome  methylome   1.040480
201472  NA288_group_2  group_2   rs348937_methylome  methylome   0.057300
201473  NA288_group_2  group_2  rs7746156_methylome  methylome   1.030100

[134213 rows x 5 columns]

In [ ]:
# Change group
omics_comp3.loc[:, 'group'] = omics_comp3['group'].replace({'group_2': 'group_1'})

In [ ]:
# Change group information of sample column - using regular expression
import re

def update_sample(sample_name):
    match = re.search(r'_group_(\d+)', sample_name)
    if match:
        group_number = int(match.group(1))
        if group_number == 2:
            new_group_number = 1
        else:
            return sample_name
        return re.sub(r'_group_\d+', f'_group_{new_group_number}', sample_name)
    return sample_name

omics_comp3.loc[:, 'sample'] = omics_comp3['sample'].apply(update_sample)

print(omics_comp3)

               sample    group              feature       view      value
16581   GA753_group_1  group_1      P05154_proteome   proteome  10.922110
16582   GA753_group_1  group_1      P02786_proteome   proteome   5.638221
16583   GA753_group_1  group_1      Q9Y490_proteome   proteome   9.349634
16584   GA753_group_1  group_1    Q15063-5_proteome   proteome   4.609786
16585   GA753_group_1  group_1      P02730_proteome   proteome   6.381731
...               ...      ...                  ...        ...        ...
201469  NA288_group_1  group_1  rs6426327_methylome  methylome   0.898350
201470  NA288_group_1  group_1  rs7660805_methylome  methylome   0.034510
201471  NA288_group_1  group_1  rs9363764_methylome  methylome   1.040480
201472  NA288_group_1  group_1   rs348937_methylome  methylome   0.057300
201473  NA288_group_1  group_1  rs7746156_methylome  methylome   1.030100

[134213 rows x 5 columns]

In [193]:
omics_comp3.index = range(1, len(omics_comp3)+1)
print(omics_comp3)

               sample    group              feature       view      value
1       GA753_group_1  group_1      P05154_proteome   proteome  10.922110
2       GA753_group_1  group_1      P02786_proteome   proteome   5.638221
3       GA753_group_1  group_1      Q9Y490_proteome   proteome   9.349634
4       GA753_group_1  group_1    Q15063-5_proteome   proteome   4.609786
5       GA753_group_1  group_1      P02730_proteome   proteome   6.381731
...               ...      ...                  ...        ...        ...
134209  NA288_group_1  group_1  rs6426327_methylome  methylome   0.898350
134210  NA288_group_1  group_1  rs7660805_methylome  methylome   0.034510
134211  NA288_group_1  group_1  rs9363764_methylome  methylome   1.040480
134212  NA288_group_1  group_1   rs348937_methylome  methylome   0.057300
134213  NA288_group_1  group_1  rs7746156_methylome  methylome   1.030100

[134213 rows x 5 columns]

In [197]:
omics_comp3.to_csv("./multiome_last_comp3_data.csv")

In [ ]:
## process first_data 
import pandas as pd
import numpy as np
import os

os.listdir()

['.ipynb_checkpoints',
 'clinical_first_data.csv',
 'clinical_first_exposed_data.csv',
 'clinical_first_exposed_ordered_data.csv',
 'clinical_first_ordered_data.csv',
 'clinical_last_data.csv',
 'clinical_last_exposed_comp2_data.csv',
 'clinical_last_exposed_comp3_data.csv',
 'clinical_last_exposed_data.csv',
 'clinical_last_exposed_ordered_data.csv',
 'clinical_last_group_data.csv',
 'clinical_last_ordered_data.csv',
 'ETC',
 'metabolome_first_norm_data.csv',
 'metabolome_first_norm_final_data.csv',
 'metabolome_first_norm_ordered_data.csv',
 'metabolome_last_mofa_data.csv',
 'metabolome_last_mofa_norm_data.csv',
 'metabolome_last_norm_data.csv',
 'metabolome_last_norm_final_data.csv',
 'metabolome_last_norm_ordered_data.csv',
 'methylome_first_norm_data.csv',
 'methylome_first_norm_data_t.csv',
 'methylome_first_norm_final_data.csv',
 'methylome_first_norm_ordered_data.csv',
 'methylome_last_mofa_data.csv',
 'methylome_last_mofa_norm_data.csv',
 'methylome_last_norm_data.csv',
 'methylome_last_norm_data_t.csv',
 'methylome_last_norm_final_data.csv',
 'methylome_last_norm_ordered_data.csv',
 'multiome_comp3.hdf5',
 'multiome_last_comp1_data.csv',
 'multiome_last_comp2_data.csv',
 'multiome_last_comp3_data.csv',
 'multiome_last_mofa-data.csv',
 'Multiomics_last_data.xlsm',
 'omics_input_changer.ipynb',
 'proteome_first_impute-norm_data.csv',
 'proteome_first_impute-norm_final_data.csv',
 'proteome_first_impute-norm_ordered_data.csv',
 'proteome_last_impute-norm_data.csv',
 'proteome_last_impute-norm_final_data.csv',
 'proteome_last_impute-norm_ordered_data.csv',
 'proteome_last_mofa_data.csv',
 'proteome_last_mofa_impute-norm_data.csv',
 'SampleInfo.csv',
 'SampleInfo_raw.csv',
 'single-omics',
 'transcriptome_last_mofa_data.csv',
 'transcriptome_last_mofa_norm_data.csv',
 'transcriptome_last_norm_data.csv',
 'transcriptome_last_norm_data_t.csv',
 'transcriptome_last_norm_final_data.csv',
 'transcriptome_last_norm_ordered_data.csv']

In [7]:
df = pd.read_csv("metabolome_first_norm_ordered_data.csv")
df = pd.DataFrame(df)

df

,Label,A09_072_C9a,A08_045_C8a,A08_056_C9a,S08_043_C8a,S09_072_C9a,S09_104_C9a,S09_053_C9a,S09_122_C8a,A10_020_C9a,...,A33,A44,A54,A6,A76,A80,GA034,GA048,GA062,GA109
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,met1,21.52666958,21.1187418,20.85199523,20.7621937,21.20570999,20.4900206,21.46751721,21.22525484,20.45011388,...,22.09519996,21.58911532,21.33025253,22.21776362,22.18329385,21.99055661,21.88093052,22.17676543,21.14070596,21.23050913
2,met2,15.4262445,15.07610315,12.17465312,12.19912667,14.13172771,15.01009957,15.51532673,13.80539015,13.82591452,...,13.95206417,13.76208763,14.21266475,13.94160036,15.35264055,15.38398531,15.45512607,15.29516248,15.49820359,12.50026465
3,met4,24.54412998,23.69850317,19.43812106,19.51549094,18.25285307,23.94841805,23.95538441,24.00231548,24.23305735,...,24.42924174,24.23591023,24.20999698,24.35394412,18.07705723,23.51919081,24.28818022,24.37130879,19.3075932,19.80464935
4,met5,17.04468563,17.36892193,16.49692052,18.03918999,16.58491747,16.41165333,16.60712349,17.28942208,17.91241474,...,16.82287044,15.76905552,15.12996133,14.32114129,14.8037406,15.32607869,15.9998172,15.87056895,16.50385937,15.58628402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,met1140,17.70740886,19.27085605,19.44417293,18.30386258,18.36271605,18.76333231,16.63852068,18.36528073,18.81957771,...,17.8376961,18.22686989,18.2193628,18.01778186,16.2361601,17.86878908,16.81000579,17.16182225,18.06754382,18.54742415
749,met1141,20.88821565,20.90404618,20.50465515,20.71518604,20.8439788,20.7201479,20.6937023,19.66432946,20.26431649,...,20.28680049,20.95005674,20.93622503,20.36413427,21.61916632,19.88292324,20.22629967,20.46278549,21.14411098,20.25203377
750,met1142,17.01507387,17.25049523,16.66781744,17.1136205,16.3340238,17.09739077,16.70214439,16.61976708,16.72551785,...,16.92748154,17.27464518,17.05586585,16.84507595,15.81278703,16.20390625,16.34537184,16.41966819,17.20440921,15.93440421
751,met1143,17.72455891,19.08626908,18.9094556,17.92113485,17.76878527,18.90754998,16.61509896,18.2870447,17.93899152,...,17.77653612,17.96903328,17.68733425,17.94601206,17.23639631,18.09832178,17.50327977,17.16514752,18.50611373,17.96260375
752,met1144,15.63412119,15.7931329,15.33378067,15.56461608,16.10773755,15.64813671,16.00256942,15.84940165,15.21069224,...,15.58289641,16.22262205,16.31387273,15.83028035,15.6871031,14.03616106,15.299983,16.40120667,16.3498469,15.07380411

In [9]:
df.loc[:, 'Label']

0        Group
1         met1
2         met2
3         met4
4         met5
        ...
748    met1140
749    met1141
750    met1142
751    met1143
752    met1144
Name: Label, Length: 753, dtype: object

In [11]:
group_info = df.iloc[0]
df = df[1:]
df.index = df.loc[:, 'Label']
df = df.drop('Label', axis=1)
df

,A09_072_C9a,A08_045_C8a,A08_056_C9a,S08_043_C8a,S09_072_C9a,S09_104_C9a,S09_053_C9a,S09_122_C8a,A10_020_C9a,A09_126_C9a,...,A33,A44,A54,A6,A76,A80,GA034,GA048,GA062,GA109
Label,,,,,,,,,,,,,,,,,,,,,
met1,21.52666958,21.1187418,20.85199523,20.7621937,21.20570999,20.4900206,21.46751721,21.22525484,20.45011388,20.22283215,...,22.09519996,21.58911532,21.33025253,22.21776362,22.18329385,21.99055661,21.88093052,22.17676543,21.14070596,21.23050913
met2,15.4262445,15.07610315,12.17465312,12.19912667,14.13172771,15.01009957,15.51532673,13.80539015,13.82591452,13.70229996,...,13.95206417,13.76208763,14.21266475,13.94160036,15.35264055,15.38398531,15.45512607,15.29516248,15.49820359,12.50026465
met4,24.54412998,23.69850317,19.43812106,19.51549094,18.25285307,23.94841805,23.95538441,24.00231548,24.23305735,24.19197261,...,24.42924174,24.23591023,24.20999698,24.35394412,18.07705723,23.51919081,24.28818022,24.37130879,19.3075932,19.80464935
met5,17.04468563,17.36892193,16.49692052,18.03918999,16.58491747,16.41165333,16.60712349,17.28942208,17.91241474,17.33779952,...,16.82287044,15.76905552,15.12996133,14.32114129,14.8037406,15.32607869,15.9998172,15.87056895,16.50385937,15.58628402
met6,17.04468563,17.36892193,16.49692052,18.03918999,16.58491747,16.41165333,16.60712349,17.28942208,17.91241474,17.33779952,...,16.82287044,15.76905552,15.12996133,17.24447301,14.8037406,16.22370678,15.9998172,15.87056895,16.50385937,15.58628402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
met1140,17.70740886,19.27085605,19.44417293,18.30386258,18.36271605,18.76333231,16.63852068,18.36528073,18.81957771,19.06423307,...,17.8376961,18.22686989,18.2193628,18.01778186,16.2361601,17.86878908,16.81000579,17.16182225,18.06754382,18.54742415
met1141,20.88821565,20.90404618,20.50465515,20.71518604,20.8439788,20.7201479,20.6937023,19.66432946,20.26431649,20.06232689,...,20.28680049,20.95005674,20.93622503,20.36413427,21.61916632,19.88292324,20.22629967,20.46278549,21.14411098,20.25203377
met1142,17.01507387,17.25049523,16.66781744,17.1136205,16.3340238,17.09739077,16.70214439,16.61976708,16.72551785,16.7370195,...,16.92748154,17.27464518,17.05586585,16.84507595,15.81278703,16.20390625,16.34537184,16.41966819,17.20440921,15.93440421
met1143,17.72455891,19.08626908,18.9094556,17.92113485,17.76878527,18.90754998,16.61509896,18.2870447,17.93899152,18.05553639,...,17.77653612,17.96903328,17.68733425,17.94601206,17.23639631,18.09832178,17.50327977,17.16514752,18.50611373,17.96260375
met1144,15.63412119,15.7931329,15.33378067,15.56461608,16.10773755,15.64813671,16.00256942,15.84940165,15.21069224,15.80673534,...,15.58289641,16.22262205,16.31387273,15.83028035,15.6871031,14.03616106,15.299983,16.40120667,16.3498469,15.07380411

In [13]:
group_info = group_info[1:]
group_info

A09_072_C9a    group_1
A08_045_C8a    group_1
A08_056_C9a    group_1
S08_043_C8a    group_1
S09_072_C9a    group_1
                ...
A80            group_5
GA034          group_5
GA048          group_5
GA062          group_5
GA109          group_5
Name: 0, Length: 90, dtype: object

In [15]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [17]:
sample_list

['A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',

In [19]:
feature_list

['met1',
 'met2',
 'met4',
 'met5',
 'met6',
 'met7',
 'met14',
 'met15',
 'met16',
 'met19',
 'met20',
 'met22',
 'met25',
 'met26',
 'met27',
 'met28',
 'met29',
 'met30',
 'met31',
 'met32',
 'met33',
 'met34',
 'met35',
 'met37',
 'met38',
 'met39',
 'met40',
 'met41',
 'met43',
 'met44',
 'met45',
 'met46',
 'met47',
 'met48',
 'met54',
 'met56',
 'met57',
 'met58',
 'met60',
 'met64',
 'met65',
 'met69',
 'met70',
 'met71',
 'met72',
 'met73',
 'met74',
 'met77',
 'met81',
 'met82',
 'met85',
 'met86',
 'met90',
 'met91',
 'met92',
 'met93',
 'met94',
 'met95',
 'met96',
 'met97',
 'met101',
 'met102',
 'met103',
 'met104',
 'met105',
 'met108',
 'met110',
 'met111',
 'met114',
 'met115',
 'met116',
 'met117',
 'met118',
 'met119',
 'met120',
 'met121',
 'met123',
 'met124',
 'met125',
 'met126',
 'met127',
 'met131',
 'met132',
 'met133',
 'met134',
 'met136',
 'met137',
 'met138',
 'met140',
 'met141',
 'met142',
 'met146',
 'met148',
 'met149',
 'met150',
 'met151',
 'met152',
 'met153',
 'met154',
 'met158',
 'met159',
 'met160',
 'met164',
 'met168',
 'met169',
 'met171',
 'met173',
 'met174',
 'met177',
 'met181',
 'met182',
 'met184',
 'met185',
 'met186',
 'met187',
 'met188',
 'met190',
 'met191',
 'met192',
 'met193',
 'met195',
 'met196',
 'met197',
 'met198',
 'met199',
 'met203',
 'met207',
 'met209',
 'met210',
 'met211',
 'met212',
 'met214',
 'met215',
 'met217',
 'met218',
 'met219',
 'met220',
 'met221',
 'met222',
 'met223',
 'met226',
 'met227',
 'met228',
 'met229',
 'met231',
 'met232',
 'met233',
 'met234',
 'met235',
 'met236',
 'met238',
 'met239',
 'met240',
 'met241',
 'met242',
 'met243',
 'met244',
 'met246',
 'met247',
 'met248',
 'met249',
 'met251',
 'met252',
 'met253',
 'met254',
 'met255',
 'met256',
 'met257',
 'met259',
 'met260',
 'met261',
 'met264',
 'met265',
 'met266',
 'met267',
 'met270',
 'met271',
 'met272',
 'met273',
 'met277',
 'met278',
 'met280',
 'met281',
 'met282',
 'met284',
 'met285',
 'met286',
 'met288',
 'met289',
 'met291',
 'met292',
 'met294',
 'met295',
 'met296',
 'met297',
 'met298',
 'met299',
 'met301',
 'met302',
 'met303',
 'met306',
 'met308',
 'met309',
 'met311',
 'met312',
 'met313',
 'met314',
 'met316',
 'met317',
 'met318',
 'met319',
 'met320',
 'met321',
 'met322',
 'met323',
 'met324',
 'met326',
 'met327',
 'met328',
 'met329',
 'met332',
 'met333',
 'met334',
 'met336',
 'met339',
 'met341',
 'met342',
 'met344',
 'met345',
 'met346',
 'met347',
 'met348',
 'met349',
 'met350',
 'met351',
 'met352',
 'met354',
 'met355',
 'met357',
 'met358',
 'met360',
 'met361',
 'met362',
 'met363',
 'met364',
 'met365',
 'met366',
 'met367',
 'met368',
 'met371',
 'met372',
 'met374',
 'met375',
 'met376',
 'met377',
 'met381',
 'met383',
 'met384',
 'met390',
 'met393',
 'met394',
 'met395',
 'met396',
 'met397',
 'met399',
 'met400',
 'met402',
 'met403',
 'met404',
 'met405',
 'met406',
 'met408',
 'met409',
 'met410',
 'met415',
 'met416',
 'met417',
 'met418',
 'met421',
 'met424',
 'met426',
 'met427',
 'met430',
 'met431',
 'met432',
 'met433',
 'met434',
 'met436',
 'met437',
 'met438',
 'met439',
 'met440',
 'met441',
 'met443',
 'met444',
 'met447',
 'met449',
 'met450',
 'met451',
 'met452',
 'met453',
 'met455',
 'met457',
 'met459',
 'met460',
 'met461',
 'met462',
 'met467',
 'met469',
 'met470',
 'met471',
 'met473',
 'met474',
 'met476',
 'met477',
 'met478',
 'met479',
 'met482',
 'met485',
 'met486',
 'met487',
 'met488',
 'met489',
 'met490',
 'met491',
 'met492',
 'met493',
 'met496',
 'met497',
 'met499',
 'met501',
 'met502',
 'met504',
 'met506',
 'met507',
 'met508',
 'met509',
 'met511',
 'met512',
 'met513',
 'met514',
 'met515',
 'met516',
 'met519',
 'met520',
 'met521',
 'met522',
 'met523',
 'met526',
 'met527',
 'met528',
 'met530',
 'met531',
 'met533',
 'met534',
 'met536',
 'met537',
 'met540',
 'met541',
 'met542',
 'met543',
 'met545',
 'met546',
 'met548',
 'met549',
 'met554',
 'met559',
 'met560',
 'met566',
 'met567',
 'met569',
 'met570',
 'met576',
 'met578',
 'met580',
 'met581',
 'met582',
 'met585',
 'met589',
 'met593',
 'met594',
 'met595',
 'met596',
 'met597',
 'met600',
 'met601',
 'met602',
 'met604',
 'met606',
 'met607',
 'met608',
 'met609',
 'met610',
 'met611',
 'met612',
 'met615',
 'met616',
 'met617',
 'met618',
 'met619',
 'met620',
 'met621',
 'met622',
 'met623',
 'met625',
 'met627',
 'met628',
 'met629',
 'met630',
 'met631',
 'met632',
 'met633',
 'met634',
 'met635',
 'met636',
 'met637',
 'met638',
 'met639',
 'met640',
 'met642',
 'met643',
 'met644',
 'met646',
 'met647',
 'met648',
 'met649',
 'met651',
 'met652',
 'met653',
 'met654',
 'met655',
 'met656',
 'met657',
 'met658',
 'met661',
 'met662',
 'met664',
 'met665',
 'met667',
 'met668',
 'met669',
 'met670',
 'met674',
 'met675',
 'met676',
 'met677',
 'met680',
 'met681',
 'met683',
 'met684',
 'met686',
 'met687',
 'met688',
 'met689',
 'met690',
 'met691',
 'met693',
 'met695',
 'met697',
 'met700',
 'met701',
 'met706',
 'met714',
 'met715',
 'met716',
 'met717',
 'met718',
 'met719',
 'met720',
 'met721',
 'met722',
 'met723',
 'met724',
 'met725',
 'met726',
 'met727',
 'met728',
 'met729',
 'met730',
 'met731',
 'met732',
 'met733',
 'met734',
 'met735',
 'met736',
 'met737',
 'met738',
 'met739',
 'met740',
 'met741',
 'met742',
 'met743',
 'met744',
 'met745',
 'met746',
 'met747',
 'met748',
 'met749',
 'met750',
 'met751',
 'met754',
 'met756',
 'met757',
 'met758',
 'met759',
 'met760',
 'met762',
 'met763',
 'met764',
 'met765',
 'met766',
 'met767',
 'met773',
 'met774',
 'met775',
 'met777',
 'met778',
 'met779',
 'met780',
 'met781',
 'met782',
 'met783',
 'met784',
 'met785',
 'met788',
 'met789',
 'met790',
 'met791',
 'met792',
 'met793',
 'met794',
 'met795',
 'met796',
 'met797',
 'met798',
 'met799',
 'met800',
 'met802',
 'met803',
 'met804',
 'met805',
 'met807',
 'met810',
 'met811',
 'met812',
 'met813',
 'met815',
 'met817',
 'met818',
 'met819',
 'met820',
 'met821',
 'met825',
 'met826',
 'met827',
 'met828',
 'met830',
 'met833',
 'met837',
 'met840',
 'met844',
 'met845',
 'met847',
 'met850',
 'met853',
 'met857',
 'met858',
 'met859',
 'met860',
 'met864',
 'met865',
 'met866',
 'met867',
 'met870',
 'met871',
 'met872',
 'met873',
 'met874',
 'met877',
 'met879',
 'met884',
 'met886',
 'met887',
 'met888',
 'met889',
 'met890',
 'met895',
 'met896',
 'met898',
 'met899',
 'met900',
 'met903',
 'met904',
 'met906',
 'met911',
 'met914',
 'met915',
 'met916',
 'met917',
 'met918',
 'met920',
 'met921',
 'met924',
 'met925',
 'met926',
 'met932',
 'met933',
 'met934',
 'met935',
 'met936',
 'met937',
 'met940',
 'met942',
 'met943',
 'met945',
 'met947',
 'met948',
 'met951',
 'met952',
 'met953',
 'met954',
 'met957',
 'met961',
 'met962',
 'met963',
 'met964',
 'met965',
 'met966',
 'met967',
 'met968',
 'met969',
 'met970',
 'met972',
 'met974',
 'met975',
 'met976',
 'met979',
 'met980',
 'met981',
 'met982',
 'met983',
 'met984',
 'met985',
 'met988',
 'met989',
 'met990',
 'met992',
 'met994',
 'met995',
 'met996',
 'met997',
 'met998',
 'met1000',
 'met1001',
 'met1002',
 'met1003',
 'met1005',
 'met1006',
 'met1008',
 'met1011',
 'met1012',
 'met1014',
 'met1015',
 'met1016',
 'met1020',
 'met1024',
 'met1025',
 'met1026',
 'met1027',
 'met1028',
 'met1029',
 'met1030',
 'met1032',
 'met1033',
 'met1034',
 'met1035',
 'met1036',
 'met1037',
 'met1038',
 'met1040',
 'met1042',
 'met1044',
 'met1045',
 'met1046',
 'met1047',
 'met1048',
 'met1050',
 'met1052',
 'met1053',
 'met1056',
 'met1058',
 'met1059',
 'met1060',
 'met1061',
 'met1062',
 'met1066',
 'met1068',
 'met1069',
 'met1070',
 'met1071',
 'met1073',
 'met1074',
 'met1075',
 'met1076',
 'met1077',
 'met1079',
 'met1081',
 'met1082',
 'met1083',
 'met1084',
 'met1086',
 'met1087',
 'met1088',
 'met1089',
 'met1090',
 'met1091',
 'met1092',
 'met1093',
 'met1094',
 'met1096',
 'met1097',
 'met1099',
 'met1100',
 'met1101',
 'met1102',
 'met1103',
 'met1104',
 'met1105',
 'met1106',
 'met1107',
 'met1108',
 'met1111',
 'met1112',
 'met1113',
 'met1114',
 'met1117',
 'met1118',
 'met1121',
 'met1127',
 'met1130',
 'met1131',
 'met1132',
 'met1134',
 'met1136',
 'met1137',
 'met1138',
 'met1139',
 'met1140',
 'met1141',
 'met1142',
 'met1143',
 'met1144',
 'met1',
 'met2',
 'met4',
 'met5',
 'met6',
 'met7',
 'met14',
 'met15',
 'met16',
 'met19',
 'met20',
 'met22',
 'met25',
 'met26',
 'met27',
 'met28',
 'met29',
 'met30',
 'met31',
 'met32',
 'met33',
 'met34',
 'met35',
 'met37',
 'met38',
 'met39',
 'met40',
 'met41',
 'met43',
 'met44',
 'met45',
 'met46',
 'met47',
 'met48',
 'met54',
 'met56',
 'met57',
 'met58',
 'met60',
 'met64',
 'met65',
 'met69',
 'met70',
 'met71',
 'met72',
 'met73',
 'met74',
 'met77',
 'met81',
 'met82',
 'met85',
 'met86',
 'met90',
 'met91',
 'met92',
 'met93',
 'met94',
 'met95',
 'met96',
 'met97',
 'met101',
 'met102',
 'met103',
 'met104',
 'met105',
 'met108',
 'met110',
 'met111',
 'met114',
 'met115',
 'met116',
 'met117',
 'met118',
 'met119',
 'met120',
 'met121',
 'met123',
 'met124',
 'met125',
 'met126',
 'met127',
 'met131',
 'met132',
 'met133',
 'met134',
 'met136',
 'met137',
 'met138',
 'met140',
 'met141',
 'met142',
 'met146',
 'met148',
 'met149',
 'met150',
 'met151',
 'met152',
 'met153',
 'met154',
 'met158',
 'met159',
 'met160',
 'met164',
 'met168',
 'met169',
 'met171',
 'met173',
 'met174',
 'met177',
 'met181',
 'met182',
 'met184',
 'met185',
 'met186',
 'met187',
 'met188',
 'met190',
 'met191',
 'met192',
 'met193',
 'met195',
 'met196',
 'met197',
 'met198',
 'met199',
 'met203',
 'met207',
 'met209',
 'met210',
 'met211',
 'met212',
 'met214',
 'met215',
 'met217',
 'met218',
 'met219',
 'met220',
 'met221',
 'met222',
 'met223',
 'met226',
 'met227',
 'met228',
 'met229',
 'met231',
 'met232',
 'met233',
 'met234',
 'met235',
 'met236',
 'met238',
 'met239',
 'met240',
 'met241',
 'met242',
 'met243',
 'met244',
 'met246',
 'met247',
 'met248',
 'met249',
 'met251',
 'met252',
 'met253',
 'met254',
 'met255',
 'met256',
 'met257',
 'met259',
 'met260',
 'met261',
 'met264',
 'met265',
 'met266',
 'met267',
 'met270',
 'met271',
 'met272',
 'met273',
 'met277',
 'met278',
 'met280',
 'met281',
 'met282',
 'met284',
 'met285',
 'met286',
 'met288',
 'met289',
 'met291',
 'met292',
 'met294',
 'met295',
 'met296',
 'met297',
 'met298',
 'met299',
 'met301',
 'met302',
 'met303',
 'met306',
 'met308',
 'met309',
 'met311',
 'met312',
 'met313',
 'met314',
 'met316',
 'met317',
 'met318',
 'met319',
 'met320',
 'met321',
 'met322',
 'met323',
 'met324',
 'met326',
 'met327',
 'met328',
 'met329',
 'met332',
 'met333',
 'met334',
 'met336',
 'met339',
 'met341',
 'met342',
 'met344',
 'met345',
 'met346',
 'met347',
 'met348',
 'met349',
 'met350',
 'met351',
 'met352',
 'met354',
 'met355',
 'met357',
 'met358',
 'met360',
 'met361',
 'met362',
 'met363',
 'met364',
 'met365',
 'met366',
 'met367',
 ...]

In [23]:
metabolome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

metabolome_data       # 752 * 90 = 67680

                    sample    group  feature        value
0      A09_072_C9a_group_1  group_1     met1  21.52666958
1      A09_072_C9a_group_1  group_1     met2   15.4262445
2      A09_072_C9a_group_1  group_1     met4  24.54412998
3      A09_072_C9a_group_1  group_1     met5  17.04468563
4      A09_072_C9a_group_1  group_1     met6  17.04468563
...                    ...      ...      ...          ...
67675        GA109_group_5  group_5  met1140  18.54742415
67676        GA109_group_5  group_5  met1141  20.25203377
67677        GA109_group_5  group_5  met1142  15.93440421
67678        GA109_group_5  group_5  met1143  17.96260375
67679        GA109_group_5  group_5  met1144  15.07380411

[67680 rows x 4 columns]

In [25]:
metabolome_data.to_csv("./metabolome_first_mofa_norm_data.csv")

In [27]:
## Proteome
df = pd.read_csv("proteome_first_impute-norm_ordered_data.csv")
df = pd.DataFrame(df)

df

,Label,A09_072_C9a,A08_045_C8a,A08_056_C9a,S08_043_C8a,S09_072_C9a,S09_104_C9a,S09_053_C9a,S09_122_C8a,A10_020_C9a,...,A33,A44,A54,A6,A76,A80,GA034,GA048,GA062,GA109
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,P05154,10.57039353,10.42050112,10.84542902,10.60604484,10.88365718,10.98652448,10.96531384,10.98648122,11.05935058,...,11.08077084,10.85010078,10.96905698,10.67393048,10.88611418,10.47665677,10.89548623,10.88759833,11.00765647,10.99564207
2,P02786,5.976345511,5.680864746,5.653032697,5.922996489,5.436000764,5.749223799,5.350565763,5.620504744,5.551523088,...,6.175838359,5.50351152,5.598393506,5.829397078,6.100242264,5.9623048,5.710338997,5.875858495,5.506706597,5.899000061
3,Q9Y490,4.38103767,4.726590702,5.013207829,4.778860909,7.119728093,4.665806339,6.304875985,5.570592733,5.721163077,...,5.814051237,4.934112188,5.189282057,5.979214744,4.391969304,4.90798402,6.238480028,5.15776598,5.480525119,5.864719137
4,Q15063-5,4.650894142,5.194993348,4.36281689,4.649979241,4.844749372,4.254478686,4.345302311,4.601354999,5.094332845,...,3.880788281,3.961011317,4.271531897,4.259126439,4.587827001,4.659375824,3.650148756,4.306891523,4.35169475,4.593876089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,P52701;P52701-3;P52701-4,6.539631875,6.303901272,6.782408565,6.646853879,6.691394579,6.426266432,6.659696266,6.644317778,6.991408467,...,6.98230913,6.998127791,6.963312274,6.736280151,6.472632359,6.521975688,6.962664693,7.355571338,6.028456437,6.674220521
826,Q9C0G6,10.99405718,4.38528607,11.08107852,10.77686148,4.420394816,11.08924386,11.07262821,3.861836292,10.97400674,...,11.00945315,3.736474994,5.626100326,3.59962725,11.00242731,7.093465103,3.988839172,4.522532885,11.10226065,2.441031903
827,Q9Y5R5,12.45308282,12.71218305,11.08107852,11.72551964,10.87116994,12.4714339,11.07262821,11.07016623,12.676702,...,11.00945315,12.51627867,12.6340464,12.77388921,12.5030381,12.699811,11.22212476,10.97841044,12.38571683,11.06743145
828,Q01581,4.359380605,4.502305139,3.877538136,4.300255538,4.73939449,4.425190721,4.340946747,4.925130693,10.97400674,...,4.740614601,4.764112567,4.819622205,4.167711171,4.601143813,11.10022537,4.748096219,5.320401638,4.995176952,11.06743145
829,P01814,6.07653558,5.258371934,4.742771563,3.038771531,5.115282995,4.154161913,5.070659808,5.060561922,3.298954448,...,3.300040236,6.014607475,3.524402238,5.41110757,5.241767742,5.413252187,3.952426761,5.06696746,4.48039439,5.274183373

In [29]:
df.loc[:, 'Label']

0                         Group
1                        P05154
2                        P02786
3                        Q9Y490
4                      Q15063-5
                 ...
825    P52701;P52701-3;P52701-4
826                      Q9C0G6
827                      Q9Y5R5
828                      Q01581
829                      P01814
Name: Label, Length: 830, dtype: object

In [31]:
group_info = df.iloc[0]
df = df[1:]
df.index = df.loc[:, 'Label']
df = df.drop('Label', axis=1)
df

,A09_072_C9a,A08_045_C8a,A08_056_C9a,S08_043_C8a,S09_072_C9a,S09_104_C9a,S09_053_C9a,S09_122_C8a,A10_020_C9a,A09_126_C9a,...,A33,A44,A54,A6,A76,A80,GA034,GA048,GA062,GA109
Label,,,,,,,,,,,,,,,,,,,,,
P05154,10.57039353,10.42050112,10.84542902,10.60604484,10.88365718,10.98652448,10.96531384,10.98648122,11.05935058,10.96312882,...,11.08077084,10.85010078,10.96905698,10.67393048,10.88611418,10.47665677,10.89548623,10.88759833,11.00765647,10.99564207
P02786,5.976345511,5.680864746,5.653032697,5.922996489,5.436000764,5.749223799,5.350565763,5.620504744,5.551523088,5.259447399,...,6.175838359,5.50351152,5.598393506,5.829397078,6.100242264,5.9623048,5.710338997,5.875858495,5.506706597,5.899000061
Q9Y490,4.38103767,4.726590702,5.013207829,4.778860909,7.119728093,4.665806339,6.304875985,5.570592733,5.721163077,6.127905906,...,5.814051237,4.934112188,5.189282057,5.979214744,4.391969304,4.90798402,6.238480028,5.15776598,5.480525119,5.864719137
Q15063-5,4.650894142,5.194993348,4.36281689,4.649979241,4.844749372,4.254478686,4.345302311,4.601354999,5.094332845,4.42295672,...,3.880788281,3.961011317,4.271531897,4.259126439,4.587827001,4.659375824,3.650148756,4.306891523,4.35169475,4.593876089
P02730,5.034665667,4.896343015,5.393544873,4.601275143,5.556128522,4.425960149,4.974738104,5.346226775,5.130800303,4.107440988,...,4.551228228,4.418982614,4.932352805,5.628044449,5.139272971,4.562076205,4.805555602,5.334655401,4.074081775,4.777487021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P52701;P52701-3;P52701-4,6.539631875,6.303901272,6.782408565,6.646853879,6.691394579,6.426266432,6.659696266,6.644317778,6.991408467,6.749748779,...,6.98230913,6.998127791,6.963312274,6.736280151,6.472632359,6.521975688,6.962664693,7.355571338,6.028456437,6.674220521
Q9C0G6,10.99405718,4.38528607,11.08107852,10.77686148,4.420394816,11.08924386,11.07262821,3.861836292,10.97400674,5.16849763,...,11.00945315,3.736474994,5.626100326,3.59962725,11.00242731,7.093465103,3.988839172,4.522532885,11.10226065,2.441031903
Q9Y5R5,12.45308282,12.71218305,11.08107852,11.72551964,10.87116994,12.4714339,11.07262821,11.07016623,12.676702,10.9104132,...,11.00945315,12.51627867,12.6340464,12.77388921,12.5030381,12.699811,11.22212476,10.97841044,12.38571683,11.06743145
Q01581,4.359380605,4.502305139,3.877538136,4.300255538,4.73939449,4.425190721,4.340946747,4.925130693,10.97400674,10.9104132,...,4.740614601,4.764112567,4.819622205,4.167711171,4.601143813,11.10022537,4.748096219,5.320401638,4.995176952,11.06743145
P01814,6.07653558,5.258371934,4.742771563,3.038771531,5.115282995,4.154161913,5.070659808,5.060561922,3.298954448,3.510367001,...,3.300040236,6.014607475,3.524402238,5.41110757,5.241767742,5.413252187,3.952426761,5.06696746,4.48039439,5.274183373

In [33]:
group_info = group_info[1:]
group_info

A09_072_C9a    group_1
A08_045_C8a    group_1
A08_056_C9a    group_1
S08_043_C8a    group_1
S09_072_C9a    group_1
                ...
A80            group_5
GA034          group_5
GA048          group_5
GA062          group_5
GA109          group_5
Name: 0, Length: 80, dtype: object

In [35]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [37]:
sample_list

['A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',
 'A08_045_C8a_group_1',

In [39]:
feature_list

['P05154',
 'P02786',
 'Q9Y490',
 'Q15063-5',
 'P02730',
 'P0C0L4',
 'P02768',
 'P17483',
 'P06753',
 'P02766',
 'P26927',
 'O95445-2',
 'P98160',
 'P04114',
 'P19827',
 'P02765',
 'P01019',
 'P31146',
 'P01854',
 'O00391',
 'P12111-4',
 'A0M8Q6',
 'P04180',
 'P04075',
 'P01023',
 'P18206;P18206-2',
 'P10643',
 'P01042-2',
 'P02649',
 'P02549',
 'Q9Y6Y1;Q9Y6Y1-2',
 'P39060;P39060-1',
 'P06733',
 'P01024',
 'P00558',
 'P05156',
 'P00742',
 'Q16610;Q16610-4',
 'Q8IUL8',
 'P01833',
 'P35579',
 'P01008',
 'P00915',
 'B9A064',
 'Q13113',
 'P12259',
 'P13645',
 'P04196',
 'P07900;P07900-2',
 'P01011',
 'Q12805;Q12805-2;Q12805-3;Q12805-4',
 'P02787',
 'P22105;P22105-1;P22105-4',
 'P0DOY2;P0DOY3',
 'P02538',
 'P04040',
 'P09493-8',
 'P04264',
 'P21333;P21333-2',
 'Q14624',
 'P08514',
 'P07360',
 'P13796',
 'P19823',
 'A0A075B6Q5',
 'A0A0C4DH30',
 'A0A0C4DH32',
 'P01782',
 'P01764',
 'P01780',
 'P0DTE1',
 'A0A0J9YX35',
 'A0A0C4DH35',
 'P00450',
 'P00748',
 'P06276',
 'Q9Y5Y7',
 'P67936',
 'P04275',
 'P14618',
 'A0A0C4DH36',
 'P14151;P14151-2',
 'Q93084;Q93084-1;Q93084-3;Q93084-4;Q93084-5;Q93084-6;Q93084-7',
 'P02647',
 'P0C0L5',
 'P02748',
 'P43652',
 'P01031',
 'P23229;P23229-2;P23229-3;P23229-4;P23229-5;P23229-6;P23229-9',
 'P02760',
 'Q8N972',
 'O95445',
 'P08571',
 'P08253;P08253-2;P08253-3',
 'P00747',
 'P68366;P68366-2',
 'P35858;P35858-2',
 'Q01518',
 'P06396',
 'P55058',
 'P27487',
 'Q86UX7;Q86UX7-2',
 'P01766',
 'P13591;P13591-1;P13591-3;P13591-4',
 'P08603',
 'P25311',
 'P60709;P63261',
 'O75636',
 'P22792',
 'P08294',
 'Q9NTI5;Q9NTI5-2',
 'Q96PD5',
 'Q92945',
 'P02776',
 'P52209;P52209-2',
 'Q9UKY3',
 'P07996',
 'Q8N4Q0;Q8N4Q0-2',
 'Q9Y6Z7',
 'O00187',
 'O95925-2',
 'P11277;P11277-2',
 'Q8NBP7',
 'P07225',
 'P02675',
 'Q86XI6',
 'P07357',
 'P00734',
 'Q9UGM5',
 'Q9BWP8-6',
 'Q92954-3',
 'Q9Y6R7',
 'P00751',
 'Q96KN2',
 'P07437',
 'Q9NP58;Q9NP58-4',
 'P02679;P02679-2',
 'P23142',
 'P02774;P02774-3',
 'Q8IUG5;Q8IUG5-2;Q8IUG5-3',
 'O15511',
 'O14791;O14791-2',
 'P04278',
 'P17936;P17936-2',
 'P01034',
 'P12814',
 'Q06033;Q06033-2',
 'P02533',
 'Q04695',
 'P80108',
 'O43301',
 'P14770',
 'Q8NHQ9',
 'A0A0B4J1V2',
 'A0A0C4DH43',
 'Q13740;Q13740-2',
 'Q8TDL5',
 'P02750',
 'P60660;P60660-2',
 'P06681',
 'P04211',
 'P20851;P20851-2',
 'P20742',
 'Q86YD7',
 'Q10588',
 'P00390;P00390-2;P00390-3',
 'O75144;O75144-2',
 'O00329',
 'P13671',
 'P05109',
 'P01857',
 'P51841',
 'P15259',
 'P09211',
 'P02790',
 'P10909-6',
 'P11226',
 'P03951',
 'P16070;P16070-10;P16070-11;P16070-16;P16070-17;P16070-3;P16070-4;P16070-5;P16070-6;P16070-7;P16070-9',
 'Q9H4B7',
 'P02671',
 'P07333',
 'P26038',
 'Q99497',
 'P06727',
 'P29622',
 'O75882-2',
 'P36955',
 'Q9BXR6',
 'Q2KHR3;Q2KHR3-2',
 'P11597',
 'A0A0B4J1V6',
 'A0A0B4J1Y9',
 'P24592',
 'P22891;P22891-2',
 'P01880;P01880-2',
 'Q9NZP8',
 'A0A087WSZ0',
 'P48740-2',
 'P09486',
 'P02741',
 'P52566',
 'P05019;P05019-2;P05019-3;P05019-4',
 'P08779',
 'P04217-2',
 'P01889',
 'Q15166',
 'P41222',
 'P02751-1',
 'P00813',
 'Q02985;Q02985-2',
 'Q9UDT6;Q9UDT6-2',
 'Q6UXB8',
 'P05543',
 'P13647',
 'P35908',
 'Q9HBI1;Q9HBI1-2;Q9HBI1-3',
 'Q6ZMI0;Q6ZMI0-2;Q6ZMI0-3',
 'Q9H4G4',
 'A0A0C4DH38',
 'A0A0C4DH39',
 'P01742',
 'A0A087WW87;P01614',
 'O75884;O75884-2',
 'P23083',
 'A0A0C4DH29',
 'A0A0J9YVY3',
 'P0DP01',
 'A0A0C4DH31',
 'P01743',
 'A0A0A0MS14',
 'Q08380',
 'P14543;P14543-2',
 'Q12860;Q12860-2',
 'P04430',
 'A0A075B6S5',
 'A0A0B4J2D9;P0DP09',
 'P01601',
 'A0A0C4DH67',
 'A0A0A0MT36',
 'P0DOX7',
 'P01602',
 'P01597;P04432',
 'A0A087WSY6',
 'P01619',
 'A0A075B6H7',
 'P04433',
 'Q53LP3',
 'O43795',
 'Q6UX71',
 'P05362',
 'O43166;O43166-2;O43166-3',
 'P18428',
 'P32119',
 'P02749',
 'Q2Q1W2',
 'P04259',
 'P69891',
 'P00746',
 'A0A0C4DH25',
 'P61626',
 'P24844',
 'P04217',
 'P49747',
 'Q71U36;Q71U36-2',
 'P00738',
 'A0A075B6K2',
 'P23528',
 'P08185',
 'P01009',
 'P68371',
 'Q99543;Q99543-2',
 'P00488',
 'P16452;P16452-2;P16452-3',
 'P00918',
 'P04004',
 'Q12913;Q12913-3',
 'Q9NR56;Q9NR56-2;Q9NR56-3;Q9NR56-4;Q9NR56-5;Q9NR56-6;Q9NR56-7',
 'Q04917',
 'P54198;P54198-2',
 'P08637',
 'P12955',
 'P24593',
 'P55056',
 'Q9UGU5',
 'A0A0A0MS15',
 'Q96IY4',
 'Q03692',
 'P02743',
 'P35542',
 'P27918',
 'P01859',
 'P07358',
 'P04003',
 'P05160',
 'P05452',
 'O00151',
 'Q92496;Q92496-2',
 'P49908',
 'P36980;P36980-2',
 'P03952',
 'P00736',
 'P78380;P78380-3',
 'P01860',
 'P01042',
 'P05090',
 'P05106',
 'P09871',
 'P04070;P04070-2',
 'O43866',
 'P01591',
 'P40197',
 'P48740',
 'P11142',
 'P11021',
 'P0DMV8;P0DMV8-2;P0DMV9',
 'P19320;P19320-2;P19320-3',
 'P05546',
 'Q13103',
 'P02656',
 'P51451',
 'P43251;P43251-2;P43251-3;P43251-4',
 'P01877',
 'P01876',
 'P37802;P37802-2',
 'Q7Z794',
 'Q9NQ79;Q9NQ79-2;Q9NQ79-3',
 'Q14520;Q14520-2',
 'P08697',
 'O15037',
 'P05155;P05155-3',
 'P30041',
 'P02788;P02788-2',
 'P0DP23;P0DP24;P0DP25',
 'P04439;P04439-2',
 'P01871',
 'P04792',
 'P63104',
 'O95452',
 'P35527',
 'Q6DN14;Q6DN14-2;Q6DN14-3;Q6DN14-4;Q6DN14-5',
 'Q8WTT2',
 'P00338;P00338-3',
 'P02768-2',
 'P50395',
 'P23142-4',
 'Q15582',
 'P15144',
 'P06702',
 'P04066',
 'P98194;P98194-2;P98194-3;P98194-4;P98194-5;P98194-6;P98194-7;P98194-8;P98194-9',
 'P62736',
 'Q9UBX5',
 'O95810',
 'P02753',
 'P0DJI8',
 'O14792',
 'Q13201',
 'P02745',
 'P02746',
 'Q04756',
 'P01718',
 'P06310',
 'Q8N4C7',
 'P07737',
 'A0A075B6K5',
 'P01834',
 'P61224;P61224-3',
 'Q96PQ0',
 'Q8ND24',
 'P12109',
 'P23284',
 'P21926',
 'Q96KJ4',
 'Q92820',
 'P62258',
 'Q8N5G2',
 'Q05682;Q05682-2;Q05682-3;Q05682-4;Q05682-5;Q05682-6',
 'Q9H8L6',
 'Q63HM2',
 'P15169',
 'O94812;O94812-2;O94812-3;O94812-5;O94812-6;O94812-7',
 'P08519',
 'P27105',
 'P51884',
 'P08567',
 'P78417',
 'O95497',
 'P06753-2',
 'P02775',
 'P14625',
 'P02654',
 'Q9UNN8',
 'P68871',
 'P02042',
 'Q9C0A6;Q9C0A6-2;Q9C0A6-3',
 'P16157;P16157-10;P16157-12;P16157-14;P16157-16;P16157-3;P16157-5;P16157-8',
 'P62937',
 'Q13418',
 'P05976-2',
 'P37840;P37840-2',
 'P19652',
 'Q15063-2',
 'Q9HBB8;Q9HBB8-2;Q9HBB8-4',
 'Q9UHG3',
 'Q9NR34',
 'P33151',
 'Q8TCU4;Q8TCU4-2;Q8TCU4-3',
 'Q15404;Q15404-2',
 'P59998;P59998-2;P59998-3',
 'P26447',
 'Q9NRC6',
 'P30101',
 'Q14643;Q14643-2;Q14643-3;Q14643-4;Q14643-5;Q14643-6;Q14643-7;Q14643-8',
 'P81605;P81605-2',
 'Q7L1S5',
 'P33908',
 'P02652',
 'P01861',
 'Q8IWU2',
 'P02763',
 'P0DOX6',
 'O95793-3',
 'P01817',
 'Q6EMK4',
 'Q96Q89;Q96Q89-2;Q96Q89-3;Q96Q89-4',
 'P02655',
 'P0CG47;P0CG48;P62979;P62987',
 'P09493-5',
 'P09172',
 'Q9UK55',
 'P05062',
 'P42680',
 'O14503',
 'P0DOX3',
 'Q08257;Q08257-3',
 'P0DOX2',
 'P27169',
 'P43121',
 'P00740',
 'P49913',
 'P07339',
 'B2RNN3',
 'Q76LX8;Q76LX8-2',
 'Q9BYV7-5',
 'P00491',
 'Q15942',
 'Q99784;Q99784-3;Q99784-5',
 'P40227;P40227-2',
 'P07195',
 'P69905',
 'Q8N309',
 'P22352',
 'Q9H3R1',
 'Q6YHK3;Q6YHK3-2;Q6YHK3-4',
 'A0A075B6K6',
 'P02747',
 'Q8ND04-2',
 'O14867',
 'Q08AN1',
 'A0A075B6R9;A0A0C4DH68',
 'P01721',
 'A0A075B6I0',
 'A0A075B6I9',
 'A0A0A0MRZ9',
 'A0A075B6I1',
 'A0A075B6H9',
 'P01714',
 'A2NJV5',
 'P08709;P08709-2',
 'P40261',
 'A0A0B4J1Y8',
 'O14950;P19105',
 'Q9HB29;Q9HB29-2',
 'P48059-2',
 'O14786;O14786-2;O14786-3',
 'P0DJI9',
 'P04406',
 'Q96LP6;Q96LP6-2',
 'P62491;P62491-2;Q15907;Q15907-2',
 'P38646',
 'Q9UBR2',
 'Q15848',
 'P55290;P55290-4',
 'Q07954',
 'P01033',
 'Q14315;Q14315-2',
 'P40967;P40967-2;P40967-4;P40967-5',
 'Q9HBA9',
 'Q8NEP3;Q8NEP3-2;Q8NEP3-3',
 'Q5JTN6',
 'Q6P4A7;Q6P4A7-2;Q6P4A7-3',
 'Q9NRV9',
 'P13473;P13473-2;P13473-3',
 'P01344;P01344-2;P01344-3',
 'P06331',
 'A0A075B6R2',
 'P0DP08',
 'A0A0B4J1U7',
 'A0A0C4DH33',
 'A0A0J9YXX1',
 'P01768;P0DP03',
 'A0A0B4J1V1',
 'P01763',
 'Q9HDC9',
 'Q06830',
 'P07359',
 'P05783',
 'Q99439',
 'Q5JSZ5',
 'P29508',
 'A0A0B4J1X5',
 'P08F94',
 'Q9H0W8;Q9H0W8-2',
 'O00533;O00533-2',
 'Q9Y2Z2;Q9Y2Z2-2;Q9Y2Z2-4;Q9Y2Z2-5;Q9Y2Z2-6',
 'Q0VDD7;Q0VDD7-2',
 'Q9P281',
 'A0A075B6J1',
 'Q92934',
 'Q9NVM6',
 'P11166',
 'Q15485',
 'P31151',
 'P48634;P48634-2;P48634-3',
 'Q9NQC3-3',
 'Q15113',
 'P52895;Q04828',
 'Q3LI63',
 'Q15555-5',
 'P61586',
 'P15153',
 'A0A075B6S4',
 'Q13402;Q13402-2;Q13402-5;Q13402-6;Q13402-7;Q13402-8',
 'P07237',
 'A0A1B0GVH6',
 'O95622;O95622-2',
 'Q9ULV4;Q9ULV4-2;Q9ULV4-3',
 'O75602;O75602-2;O75602-3;O75602-5',
 'Q8TDM6;Q8TDM6-2;Q8TDM6-4',
 'Q9ULV3;Q9ULV3-2;Q9ULV3-3;Q9ULV3-4;Q9ULV3-5',
 'O75083',
 'Q08830',
 'P30740',
 'Q14651',
 'Q9Y6J0;Q9Y6J0-2',
 'P68104;Q5VTE0',
 'Q8NI27',
 'Q96BY7',
 'Q5T013;Q5T013-3',
 'O95568',
 'Q8N103;Q8N103-2;Q8N103-3',
 'P29401;P29401-2',
 'P25705;P25705-2',
 'Q4KWH8;Q4KWH8-3;Q4KWH8-4',
 'P06744-2',
 'P13598',
 'Q99459',
 'P61204;P84077',
 'Q9NP80-2',
 'Q92823;Q92823-2;Q92823-3;Q92823-4;Q92823-5;Q92823-6',
 'Q6UY14;Q6UY14-2;Q6UY14-3',
 'P59665;P59666',
 'P17301',
 'Q8TCS8',
 'Q92608',
 'P59190-2',
 'Q9H299',
 'P07864',
 'A0A075B6K4',
 'A0A075B6K0',
 'Q7Z6K1;Q7Z6K1-2',
 'Q86U17',
 'Q5TCS8',
 'Q8WWZ8',
 'Q86VZ2',
 'A0A087WSX0',
 'Q86V48;Q86V48-2;Q86V48-3',
 'P37837;P37837-2',
 'P25391',
 'Q8NI99',
 'O15484',
 'P13716;P13716-2',
 'Q5T6F0',
 'Q5SRE5;Q5SRE5-2',
 'P19013',
 'Q86VD1;Q86VD1-2',
 'O95479;O95479-2',
 'Q9UNW1',
 'P58335;P58335-2;P58335-4',
 'P83105',
 'Q09161',
 'Q96H15;Q96H15-2',
 'Q9Y259',
 'P18065',
 'P16112;P16112-2;P16112-3',
 'P16930',
 'Q9Y2X3',
 'A8MQ27;A8MQ27-2',
 'P24557;P24557-2;P24557-3',
 'Q9ULL1',
 'Q16853',
 'Q12884',
 'Q99996;Q99996-1;Q99996-3;Q99996-5;Q99996-6',
 'O15145',
 'O94973;O94973-2;O94973-3',
 'Q7Z7G0',
 'Q9HC35;Q9HC35-2',
 'P01599',
 'P09086;P09086-2;P09086-3;P09086-4;P09086-5;P14859;P14859-2;P14859-3;P14859-4;P14859-5;P14859-6;Q9UKI9;Q9UKI9-2;Q9UKI9-3',
 'P14174',
 'Q9Y4R8',
 'Q14571',
 'O60312',
 'Q92887',
 'P01593;P01594',
 'P01701',
 'P01703',
 'A0A075B6S9;P0DSN7',
 'P01700',
 'P06312',
 'A0A0B4J1U3',
 'Q08345;Q08345-5',
 'Q9NQU5;Q9NQU5-2',
 'P52907',
 'O60814;P06899;P23527;P33778;P57053;P58876;P62807;Q16778;Q5QNW6;Q5QNW6-2;Q93079;Q99877;Q99879;Q99880',
 'Q6ZS72',
 'O95477',
 'Q9BQL6;Q9BQL6-2;Q9BQL6-4',
 'P13224;P13224-2',
 'B1AJZ9;B1AJZ9-4',
 'Q9Y2X7-3',
 'P08195;P08195-2;P08195-3;P08195-4',
 'P01706',
 'P01705',
 'P01709',
 'A0A075B6J9',
 'P01704',
 'Q68DL7',
 'P30043',
 'O43677',
 'Q96MM7;Q96MM7-2;Q96MM7-3;Q96MM7-4',
 'A0A0B4J1X8',
 'A0A0B4J1V0',
 'P0DOX5',
 'P01767',
 'Q8NGJ5',
 'P19022;P19022-2',
 'P05556',
 'O75717;O75717-2',
 'P02100',
 'O15270',
 'Q02224;Q02224-3',
 'A0A075B6V5',
 'A0A0C4DH34',
 'Q9H6Y7;Q9H6Y7-2',
 'Q9Y277;Q9Y277-2',
 'Q53FP2',
 'Q96JA1;Q96JA1-2',
 'Q9BTZ2;Q9BTZ2-2;Q9BTZ2-7',
 'Q86VB7-2',
 'Q99969',
 'Q13228;Q13228-4',
 'Q14118',
 'Q9NPH3-5',
 'Q8TAW3',
 'Q9Y5Z7',
 'P12830',
 'O60841',
 'Q8NB91',
 'Q13609;Q13609-2',
 'P08493;P08493-2',
 'O95980',
 'Q9NVF9;Q9NVF9-2;Q9NVF9-3',
 'Q8WXW3;Q8WXW3-4',
 'P07093;P07093-2;P07093-3',
 'Q99715;Q99715-4',
 'Q9HAR2-2;Q9HAR2-4',
 'Q9NTJ5',
 'A0A075B6I4',
 'P35443',
 'P03950',
 'P00739',
 'Q14697;Q14697-2',
 'Q823',
 'Q8WTQ7',
 'Q16627;Q16627-2',
 'P80748',
 'A0A075B6S2',
 'A0A075B6P5;P01615',
 'P01715',
 'Q8TBB0-2',
 'P63272',
 'A0A1W2PQ73',
 'Q8IUX7',
 'A6NM28',
 'P07203',
 'Q99700;Q99700-2;Q99700-4',
 'Q13467',
 'P36957;P36957-2',
 'Q9BYG5',
 'Q6AHZ1;Q6AHZ1-2',
 'Q16706',
 'Q9HAS0',
 'Q9Y3R4',
 'Q86UP2;Q86UP2-2;Q86UP2-4',
 'Q3V6T2;Q3V6T2-2;Q3V6T2-3;Q3V6T2-4;Q3V6T2-5',
 'P98077',
 'Q9UKN1;Q9UKN1-2',
 'O15034',
 'Q9NQW1;Q9NQW1-2;Q9NQW1-4;Q9NQW1-5',
 'Q6ZQQ6;Q6ZQQ6-2',
 'Q86Y38',
 'Q8WXA3;Q8WXA3-1;Q8WXA3-3',
 'Q9H3Y8',
 'P60174;P60174-3',
 'P01906',
 'Q16644',
 'P0DOX4',
 'P16671',
 'P01717',
 'Q5CZC0',
 'A7MCY6',
 'Q6ZU45',
 'Q13822;Q13822-3',
 'P25100',
 'Q14244;Q14244-3;Q14244-5;Q14244-6;Q14244-7',
 'A6NLC5',
 'P84243',
 'P28340',
 'Q5T749',
 'A0A0G2JS06',
 'Q13790',
 'Q96QB1;Q96QB1-3;Q96QB1-5',
 'Q96Q40;Q96Q40-3;Q96Q40-4;Q96Q40-5',
 'Q9NP78;Q9NP78-2;Q9NP78-3;Q9NP78-5;Q9NP78-6;Q9NP78-7',
 'Q9NVI1;Q9NVI1-1;Q9NVI1-2',
 'Q7Z2Z1;Q7Z2Z1-2',
 'Q96ME1',
 'P61769',
 'Q9Y4B5',
 'Q92802;Q92802-2;Q92802-3',
 'Q17RB8;Q17RB8-2',
 'Q03591',
 'Q9Y5Q9',
 'Q15772;Q15772-1',
 'Q8WZ59',
 'Q86UX2;Q86UX2-3',
 'P51797;P51797-5',
 'P10599;P10599-2',
 'Q9H0C2',
 'Q9NU02',
 'Q66GS9',
 'P15531;P15531-2;P22392;P22392-2',
 'Q9HAU8',
 'P62913;P62913-2',
 'P09668',
 'Q14515',
 'A8MTZ0-4',
 'Q8NB49;Q8NB49-2;Q8NB49-3;Q8NB49-4',
 'P08238',
 'Q13939',
 'Q16515-2',
 'Q562R1',
 'O14498',
 'P23378',
 'Q16891;Q16891-2;Q16891-3;Q16891-4',
 'Q9NZ43-3',
 'Q14247;Q14247-3',
 'P12273',
 'P21980;P21980-2',
 'Q14376;Q14376-2',
 'Q4G0P3',
 'O95340;O95340-2',
 'P09496;P09496-3',
 'A6NHZ5',
 'A6NGE4',
 'P15291;P15291-2',
 'Q9BYX7',
 'P07738',
 'P09417;P09417-2',
 'Q96IK1;Q96IK1-2',
 'Q15413;Q15413-2;Q15413-3',
 'Q13098;Q13098-5;Q13098-7',
 'Q9H8W3',
 'Q9H8M5;Q9H8M5-2',
 'Q9Y646',
 'Q9BUN1',
 'Q02413',
 'Q16773;Q16773-2',
 'P63241;P63241-2',
 'P0DOX8',
 'P78563;P78563-2;P78563-4;P78563-5',
 'P35030;P35030-2',
 'Q96S38;Q96S38-2',
 'Q6ZRS2;Q6ZRS2-2;Q6ZRS2-3',
 'P13929;P13929-2;P13929-3',
 'Q9NZJ4;Q9NZJ4-2',
 'Q9NQV5;Q9NQV5-2',
 'Q9HCH0;Q9HCH0-2',
 'Q9H257;Q9H257-2;Q9H257-3',
 'Q8TDD1;Q8TDD1-2',
 'Q9NPR2',
 'A0A0G2JMI3',
 'P24821;P24821-4',
 'A0A075B6S6',
 'Q15326;Q15326-2;Q15326-3;Q15326-4;Q15326-5;Q15326-6',
 'P19235;P19235-2;P19235-3',
 'P01699',
 'O14543',
 'P78324;P78324-2;P78324-4;Q5TFQ8;Q9P1W8;Q9P1W8-2;Q9P1W8-3;Q9P1W8-4',
 'A6NHQ2',
 'P13727;P13727-2',
 'P54108;P54108-2;P54108-3',
 'P54793',
 'Q9H5I1;Q9H5I1-2;Q9H5I1-3',
 'Q6ZMG9-2',
 'A0A0A0MT89',
 'P15814',
 'Q7L014',
 'A0A0C4DH24',
 'Q8WWW0;Q8WWW0-3',
 'Q16880',
 'P07998',
 'P52701;P52701-3;P52701-4',
 'Q9C0G6',
 'Q9Y5R5',
 'Q01581',
 'P01814',
 'P05154',
 'P02786',
 'Q9Y490',
 'Q15063-5',
 'P02730',
 'P0C0L4',
 'P02768',
 'P17483',
 'P06753',
 'P02766',
 'P26927',
 'O95445-2',
 'P98160',
 'P04114',
 'P19827',
 'P02765',
 'P01019',
 'P31146',
 'P01854',
 'O00391',
 'P12111-4',
 'A0M8Q6',
 'P04180',
 'P04075',
 'P01023',
 'P18206;P18206-2',
 'P10643',
 'P01042-2',
 'P02649',
 'P02549',
 'Q9Y6Y1;Q9Y6Y1-2',
 'P39060;P39060-1',
 'P06733',
 'P01024',
 'P00558',
 'P05156',
 'P00742',
 'Q16610;Q16610-4',
 'Q8IUL8',
 'P01833',
 'P35579',
 'P01008',
 'P00915',
 'B9A064',
 'Q13113',
 'P12259',
 'P13645',
 'P04196',
 'P07900;P07900-2',
 'P01011',
 'Q12805;Q12805-2;Q12805-3;Q12805-4',
 'P02787',
 'P22105;P22105-1;P22105-4',
 'P0DOY2;P0DOY3',
 'P02538',
 'P04040',
 'P09493-8',
 'P04264',
 'P21333;P21333-2',
 'Q14624',
 'P08514',
 'P07360',
 'P13796',
 'P19823',
 'A0A075B6Q5',
 'A0A0C4DH30',
 'A0A0C4DH32',
 'P01782',
 'P01764',
 'P01780',
 'P0DTE1',
 'A0A0J9YX35',
 'A0A0C4DH35',
 'P00450',
 'P00748',
 'P06276',
 'Q9Y5Y7',
 'P67936',
 'P04275',
 'P14618',
 'A0A0C4DH36',
 'P14151;P14151-2',
 'Q93084;Q93084-1;Q93084-3;Q93084-4;Q93084-5;Q93084-6;Q93084-7',
 'P02647',
 'P0C0L5',
 'P02748',
 'P43652',
 'P01031',
 'P23229;P23229-2;P23229-3;P23229-4;P23229-5;P23229-6;P23229-9',
 'P02760',
 'Q8N972',
 'O95445',
 'P08571',
 'P08253;P08253-2;P08253-3',
 'P00747',
 'P68366;P68366-2',
 'P35858;P35858-2',
 'Q01518',
 'P06396',
 'P55058',
 'P27487',
 'Q86UX7;Q86UX7-2',
 'P01766',
 'P13591;P13591-1;P13591-3;P13591-4',
 'P08603',
 'P25311',
 'P60709;P63261',
 'O75636',
 'P22792',
 'P08294',
 'Q9NTI5;Q9NTI5-2',
 'Q96PD5',
 'Q92945',
 'P02776',
 'P52209;P52209-2',
 'Q9UKY3',
 'P07996',
 'Q8N4Q0;Q8N4Q0-2',
 'Q9Y6Z7',
 'O00187',
 'O95925-2',
 'P11277;P11277-2',
 'Q8NBP7',
 'P07225',
 'P02675',
 'Q86XI6',
 'P07357',
 'P00734',
 'Q9UGM5',
 'Q9BWP8-6',
 'Q92954-3',
 'Q9Y6R7',
 'P00751',
 'Q96KN2',
 'P07437',
 'Q9NP58;Q9NP58-4',
 'P02679;P02679-2',
 'P23142',
 'P02774;P02774-3',
 'Q8IUG5;Q8IUG5-2;Q8IUG5-3',
 'O15511',
 'O14791;O14791-2',
 'P04278',
 'P17936;P17936-2',
 'P01034',
 'P12814',
 'Q06033;Q06033-2',
 'P02533',
 'Q04695',
 'P80108',
 'O43301',
 'P14770',
 'Q8NHQ9',
 'A0A0B4J1V2',
 'A0A0C4DH43',
 'Q13740;Q13740-2',
 'Q8TDL5',
 'P02750',
 'P60660;P60660-2',
 'P06681',
 'P04211',
 'P20851;P20851-2',
 'P20742',
 'Q86YD7',
 'Q10588',
 'P00390;P00390-2;P00390-3',
 'O75144;O75144-2',
 'O00329',
 'P13671',
 'P05109',
 'P01857',
 ...]

In [43]:
proteome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

proteome_data      # 829 * 80 = 66320

                    sample    group                   feature        value
0      A09_072_C9a_group_1  group_1                    P05154  10.57039353
1      A09_072_C9a_group_1  group_1                    P02786  5.976345511
2      A09_072_C9a_group_1  group_1                    Q9Y490   4.38103767
3      A09_072_C9a_group_1  group_1                  Q15063-5  4.650894142
4      A09_072_C9a_group_1  group_1                    P02730  5.034665667
...                    ...      ...                       ...          ...
66315        GA109_group_5  group_5  P52701;P52701-3;P52701-4  6.674220521
66316        GA109_group_5  group_5                    Q9C0G6  2.441031903
66317        GA109_group_5  group_5                    Q9Y5R5  11.06743145
66318        GA109_group_5  group_5                    Q01581  11.06743145
66319        GA109_group_5  group_5                    P01814  5.274183373

[66320 rows x 4 columns]

In [45]:
proteome_data.to_csv("./proteome_first_mofa_norm_data.csv")

In [47]:
## Methylome
df = pd.read_csv("methylome_first_norm_ordered_data.csv")
df = pd.DataFrame(df)

df

,Label,A09_072_C9a,A08_045_C8a,A08_056_C9a,S08_043_C8a,S09_072_C9a,S09_104_C9a,S09_053_C9a,S09_122_C8a,A10_020_C9a,...,A33,A44,A54,A6,A76,A80,GA034,GA048,GA062,GA109
0,Group,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,group_1,...,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5,group_5
1,cg25625370,0.0289,0.06573,0.08737,0.02716,0.03867,0.03553,0.44195,0.03193,0.07114,...,0.04448,0.04433,0.04687,0.0839,0.04928,0.05982,0.10801,0.03252,0.06914,0.0572
2,cg25980689,0.02582,0.03304,0.03303,0.02998,0.02844,0.30402,0.02922,0.02762,0.02813,...,0.02009,0.02898,0.37323,0.03113,0.02425,0.03108,0.31506,0.0313,0.36271,0.27577
3,cg00767000,0.0371,0.04128,0.06014,0.05444,0.03799,0.05143,0.0469,0.03983,0.04132,...,0.03105,0.27594,0.04501,0.03599,0.41395,0.05443,0.04216,0.30578,0.03183,0.03649
4,cg15212418,0.06619,0.05718,0.19599,0.12365,0.08646,0.12477,0.09502,0.13364,0.07696,...,0.04616,0.04913,0.08028,0.05144,0.07344,0.11279,0.06472,0.06333,0.05879,0.08732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,rs6426327,0.85116,0.03712,0.98619,0.95314,0.95132,0.03209,0.03898,0.03767,0.03758,...,0.93489,0.85755,0.03629,0.96985,4.91709,0.75076,0.04449,0.97597,0.91962,0.86909
1472,rs7660805,0.03199,0.03773,0.98726,1.0264,0.02324,0.03904,1.01864,4.80175,4.77608,...,0.02996,4.86125,0.03494,0.86698,0.98986,0.0362,4.22966,0.03921,4.82179,0.99237
1473,rs9363764,0.03973,0.0409,0.94009,1.00478,0.04222,1.0098,0.90844,0.88113,0.03683,...,0.03319,0.03796,0.94889,0.03584,1.01091,4.75718,0.03819,0.03677,1.00727,0.04043
1474,rs348937,1.1474,1.15005,0.07812,1.23564,0.04828,0.05357,1.06973,0.05462,0.04913,...,0.04828,0.05284,4.71341,4.69734,0.0453,0.05388,1.12954,1.24613,0.04607,0.05844
1475,rs7746156,0.05303,0.04979,1.03762,0.03278,0.03977,4.53558,4.99079,1.04652,1.02538,...,0.05033,0.02954,0.04029,0.04531,0.05011,0.0281,0.05137,1.00871,0.04643,0.07593

In [49]:
df.loc[:, 'Label']

0            Group
1       cg25625370
2       cg25980689
3       cg00767000
4       cg15212418
           ...
1471     rs6426327
1472     rs7660805
1473     rs9363764
1474      rs348937
1475     rs7746156
Name: Label, Length: 1476, dtype: object

In [51]:
group_info = df.iloc[0]
df = df[1:]
df.index = df.loc[:, 'Label']
df = df.drop('Label', axis=1)
df

,A09_072_C9a,A08_045_C8a,A08_056_C9a,S08_043_C8a,S09_072_C9a,S09_104_C9a,S09_053_C9a,S09_122_C8a,A10_020_C9a,A09_126_C9a,...,A33,A44,A54,A6,A76,A80,GA034,GA048,GA062,GA109
Label,,,,,,,,,,,,,,,,,,,,,
cg25625370,0.0289,0.06573,0.08737,0.02716,0.03867,0.03553,0.44195,0.03193,0.07114,0.14563,...,0.04448,0.04433,0.04687,0.0839,0.04928,0.05982,0.10801,0.03252,0.06914,0.0572
cg25980689,0.02582,0.03304,0.03303,0.02998,0.02844,0.30402,0.02922,0.02762,0.02813,0.02927,...,0.02009,0.02898,0.37323,0.03113,0.02425,0.03108,0.31506,0.0313,0.36271,0.27577
cg00767000,0.0371,0.04128,0.06014,0.05444,0.03799,0.05143,0.0469,0.03983,0.04132,0.03294,...,0.03105,0.27594,0.04501,0.03599,0.41395,0.05443,0.04216,0.30578,0.03183,0.03649
cg15212418,0.06619,0.05718,0.19599,0.12365,0.08646,0.12477,0.09502,0.13364,0.07696,0.08709,...,0.04616,0.04913,0.08028,0.05144,0.07344,0.11279,0.06472,0.06333,0.05879,0.08732
cg19515398,0.069,0.07057,0.08474,0.06298,0.06533,0.07356,0.0849,0.06934,0.10513,0.0643,...,0.06923,0.06675,0.07231,0.07055,0.1224,0.06065,0.07209,0.07214,0.12652,0.07901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs6426327,0.85116,0.03712,0.98619,0.95314,0.95132,0.03209,0.03898,0.03767,0.03758,4.63273,...,0.93489,0.85755,0.03629,0.96985,4.91709,0.75076,0.04449,0.97597,0.91962,0.86909
rs7660805,0.03199,0.03773,0.98726,1.0264,0.02324,0.03904,1.01864,4.80175,4.77608,1.05074,...,0.02996,4.86125,0.03494,0.86698,0.98986,0.0362,4.22966,0.03921,4.82179,0.99237
rs9363764,0.03973,0.0409,0.94009,1.00478,0.04222,1.0098,0.90844,0.88113,0.03683,0.03468,...,0.03319,0.03796,0.94889,0.03584,1.01091,4.75718,0.03819,0.03677,1.00727,0.04043
rs348937,1.1474,1.15005,0.07812,1.23564,0.04828,0.05357,1.06973,0.05462,0.04913,4.65738,...,0.04828,0.05284,4.71341,4.69734,0.0453,0.05388,1.12954,1.24613,0.04607,0.05844
rs7746156,0.05303,0.04979,1.03762,0.03278,0.03977,4.53558,4.99079,1.04652,1.02538,1.06337,...,0.05033,0.02954,0.04029,0.04531,0.05011,0.0281,0.05137,1.00871,0.04643,0.07593

In [53]:
group_info = group_info[1:]
group_info

A09_072_C9a    group_1
A08_045_C8a    group_1
A08_056_C9a    group_1
S08_043_C8a    group_1
S09_072_C9a    group_1
                ...
A80            group_5
GA034          group_5
GA048          group_5
GA062          group_5
GA109          group_5
Name: 0, Length: 75, dtype: object

In [55]:
sample_list = []
group_list = []
feature_list = []
value_list = []

for col in df.columns:
    for i in range(df.shape[0]):
        sample_list.append(f"{col}_{group_info[col]}")
        group_list.append(group_info[col])
        feature_list.append(df.index[i])
        value_list.append(df[col].iloc[i])

In [57]:
sample_list

['A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',
 'A09_072_C9a_group_1',

In [59]:
feature_list

['cg25625370',
 'cg25980689',
 'cg00767000',
 'cg15212418',
 'cg19515398',
 'cg16298867',
 'cg06749803',
 'cg16574807',
 'cg06545038',
 'cg14414865',
 'cg27169846',
 'cg18171715',
 'cg17504203',
 'cg00414890',
 'cg05237023',
 'cg24364070',
 'cg10387956',
 'cg15694117',
 'cg18232235',
 'cg22621695',
 'cg26764761',
 'cg23800435',
 'cg01050810',
 'cg13571460',
 'cg04386759',
 'cg01831771',
 'cg17723549',
 'cg20079298',
 'cg07178278',
 'cg09520857',
 'cg09655876',
 'cg09698465',
 'cg08103988',
 'cg21897676',
 'cg11342941',
 'cg05162523',
 'cg04633141',
 'cg15257930',
 'cg13752114',
 'cg05923197',
 'cg01079515',
 'cg17189020',
 'cg05475404',
 'cg05692422',
 'cg10243004',
 'cg24783935',
 'cg02820566',
 'cg20973476',
 'cg12951094',
 'cg00614959',
 'cg18337575',
 'cg11383134',
 'cg24519533',
 'cg18805164',
 'cg18853010',
 'cg08008636',
 'cg23353080',
 'cg22846391',
 'cg14677130',
 'cg13565624',
 'cg13632935',
 'cg13641185',
 'cg25735398',
 'cg16784970',
 'cg00810939',
 'cg11064039',
 'cg02198617',
 'cg13474370',
 'cg03653399',
 'cg19778375',
 'cg22691119',
 'cg22712681',
 'cg15715746',
 'cg02885007',
 'cg04454872',
 'cg06406458',
 'cg01628528',
 'cg01651570',
 'cg01676844',
 'cg07600533',
 'cg14215338',
 'cg10365886',
 'cg22494932',
 'cg16059038',
 'cg12045875',
 'cg27508960',
 'cg23182840',
 'cg23376390',
 'cg09565319',
 'cg08162124',
 'cg18447419',
 'cg09139047',
 'cg24289452',
 'cg05694749',
 'cg07028389',
 'cg12005649',
 'cg22526939',
 'cg11479503',
 'cg00400448',
 'cg16936421',
 'cg22262702',
 'cg22708961',
 'cg02004499',
 'cg05928290',
 'cg15472170',
 'cg24451422',
 'cg17266581',
 'cg26695758',
 'cg18251019',
 'cg21110052',
 'cg23473419',
 'cg03543448',
 'cg16237672',
 'cg13162615',
 'cg11717189',
 'cg17380795',
 'cg12500731',
 'cg04011897',
 'cg24002522',
 'cg03003335',
 'cg23651812',
 'cg22923398',
 'cg08311689',
 'cg08857906',
 'cg10864200',
 'cg16903122',
 'cg18202502',
 'cg19205926',
 'cg25445931',
 'cg26845390',
 'cg02976929',
 'cg05522011',
 'cg06003267',
 'cg04781796',
 'cg24449463',
 'cg06127335',
 'cg16550477',
 'cg09595050',
 'cg00889627',
 'cg23450357',
 'cg21477691',
 'cg27527593',
 'cg25840318',
 'cg20483857',
 'cg21679391',
 'cg12274407',
 'cg13362546',
 'cg20883195',
 'cg22999099',
 'cg15838301',
 'cg10244666',
 'cg07828340',
 'cg17052964',
 'cg19023977',
 'cg07303187',
 'cg03308399',
 'cg14496753',
 'cg16003687',
 'cg24077454',
 'cg02463440',
 'cg04785299',
 'cg16752592',
 'cg00964333',
 'cg27215475',
 'cg19486507',
 'cg03444184',
 'cg21540367',
 'cg18582362',
 'cg01224393',
 'cg22103003',
 'cg20146569',
 'cg23997132',
 'cg08941173',
 'cg03338924',
 'cg05062510',
 'cg17702455',
 'cg19873602',
 'cg26393261',
 'cg14862260',
 'cg19052042',
 'cg13737221',
 'cg12973548',
 'cg11445109',
 'cg08203849',
 'cg10951117',
 'cg03973420',
 'cg05904041',
 'cg22821289',
 'cg24231558',
 'cg16904399',
 'cg17983814',
 'cg05069728',
 'cg24521757',
 'cg12014181',
 'cg15260428',
 'cg05216211',
 'cg24251942',
 'cg13853046',
 'cg07618979',
 'cg03613822',
 'cg09570535',
 'cg23834812',
 'cg21840211',
 'cg04764687',
 'cg18141400',
 'cg11836154',
 'cg02113521',
 'cg11949518',
 'cg06657917',
 'cg13639582',
 'cg05390473',
 'cg19004594',
 'cg01707795',
 'cg01586208',
 'cg13262513',
 'cg24757533',
 'cg09247692',
 'cg01882058',
 'cg24522982',
 'cg11615743',
 'cg26877022',
 'cg02158065',
 'cg03704748',
 'cg14767529',
 'cg18550476',
 'cg16234831',
 'cg11674105',
 'cg23896871',
 'cg24488271',
 'cg01282504',
 'cg24785250',
 'cg14512630',
 'cg07968522',
 'cg02816447',
 'cg09514664',
 'cg01121464',
 'cg13556539',
 'cg15158031',
 'cg09860529',
 'cg07102406',
 'cg27461200',
 'cg27036347',
 'cg05827468',
 'cg02869163',
 'cg06238300',
 'cg25974442',
 'cg15656087',
 'cg03310027',
 'cg27380724',
 'cg11990813',
 'cg18155407',
 'cg12479899',
 'cg05917748',
 'cg00629117',
 'cg00451058',
 'cg08845486',
 'cg10000246',
 'cg03662545',
 'cg18624777',
 'cg01156747',
 'cg09763180',
 'cg24209115',
 'cg09122588',
 'cg21537187',
 'cg17999099',
 'cg27562174',
 'cg13695309',
 'cg18492799',
 'cg19508985',
 'cg06583077',
 'cg07571142',
 'cg13193179',
 'cg01391680',
 'cg06528862',
 'cg08763351',
 'cg14272706',
 'cg22185378',
 'cg21948655',
 'cg03035849',
 'cg16575408',
 'cg01957330',
 'cg04413148',
 'cg07597976',
 'cg01365152',
 'cg07403350',
 'cg08947964',
 'cg26709720',
 'cg06090864',
 'cg23959977',
 'cg26813508',
 'cg00455546',
 'cg05942349',
 'cg21104276',
 'cg13046237',
 'cg00329040',
 'cg23621496',
 'cg20363450',
 'cg20472752',
 'cg09532726',
 'cg23248424',
 'cg22622899',
 'cg20795680',
 'cg19767548',
 'cg21856695',
 'cg21469772',
 'cg03249561',
 'cg05627365',
 'cg05297328',
 'cg26697424',
 'cg22258388',
 'cg24875593',
 'cg19106893',
 'cg22135490',
 'cg22909333',
 'cg21358336',
 'cg24441899',
 'cg10867226',
 'cg10985479',
 'cg27063237',
 'cg21133261',
 'cg22591002',
 'cg06713830',
 'cg09721595',
 'cg02891314',
 'cg04282082',
 'cg14904079',
 'cg06989968',
 'cg22459517',
 'cg01179055',
 'cg01218414',
 'cg16216281',
 'cg03433313',
 'cg03513647',
 'cg06610254',
 'cg15059639',
 'cg15135166',
 'cg22843765',
 'cg14356213',
 'cg06182205',
 'cg07700233',
 'cg16932820',
 'cg00356500',
 'cg15727285',
 'cg13803647',
 'cg25764137',
 'cg06244897',
 'cg06533319',
 'cg16272324',
 'cg18406106',
 'cg05521315',
 'cg08186575',
 'cg15553776',
 'cg11218060',
 'cg24056954',
 'cg07615435',
 'cg04611087',
 'cg12659291',
 'cg17984198',
 'cg23736728',
 'cg04531182',
 'cg10877170',
 'cg01934390',
 'cg13295660',
 'cg26094470',
 'cg00917413',
 'cg13502686',
 'cg12392126',
 'cg18872420',
 'cg17242574',
 'cg18837922',
 'cg08368792',
 'cg01403557',
 'cg10669755',
 'cg12418213',
 'cg16912848',
 'cg07037964',
 'cg09013068',
 'cg06707197',
 'cg20318229',
 'cg00645431',
 'cg24088508',
 'cg25371048',
 'cg25485190',
 'cg02002523',
 'cg02771260',
 'cg09869665',
 'cg09996597',
 'cg11379809',
 'cg13862711',
 'cg11043221',
 'cg18358136',
 'cg03649429',
 'cg27354084',
 'cg27374734',
 'cg08556080',
 'cg08564027',
 'cg08653161',
 'cg08750459',
 'cg08776296',
 'cg25597117',
 'cg25709703',
 'cg00077566',
 'cg22867893',
 'cg26519051',
 'cg11037025',
 'cg05850870',
 'cg05906492',
 'cg10354017',
 'cg02954704',
 'cg05212259',
 'cg01144124',
 'cg23985820',
 'cg23403192',
 'cg23489630',
 'cg23495837',
 'cg17857456',
 'cg12797157',
 'cg07506458',
 'cg14332815',
 'cg14345464',
 'cg03571863',
 'cg18712599',
 'cg08041188',
 'cg04592785',
 'cg05111364',
 'cg13320211',
 'cg06198928',
 'cg24672310',
 'cg25155158',
 'cg01505705',
 'cg04553038',
 'cg27063617',
 'cg10587254',
 'cg15131001',
 'cg02905940',
 'cg14474522',
 'cg15103446',
 'cg05939300',
 'cg05953785',
 'cg27373156',
 'cg23076151',
 'cg09414774',
 'cg09503310',
 'cg13552668',
 'cg09769427',
 'cg09853393',
 'cg05437771',
 'cg05465951',
 'cg06107030',
 'cg19247601',
 'cg22234267',
 'cg09610179',
 'cg19585676',
 'cg03471711',
 'cg17537241',
 'cg21551951',
 'cg02057050',
 'cg02088761',
 'cg17661563',
 'cg05374263',
 'cg15882603',
 'cg15898343',
 'cg18835549',
 'cg18928442',
 'cg18974084',
 'cg19029797',
 'cg19126690',
 'cg10644638',
 'cg10691742',
 'cg10725542',
 'cg06655840',
 'cg01429604',
 'cg01475204',
 'cg01496381',
 'cg01498833',
 'cg07434806',
 'cg07711952',
 'cg18484110',
 'cg21629581',
 'cg07906019',
 'cg20870820',
 'cg17064981',
 'cg17147978',
 'cg17189664',
 'cg03867377',
 'cg03897729',
 'cg00398911',
 'cg13244672',
 'cg17698935',
 'cg17861914',
 'cg16100486',
 'cg04761931',
 'cg04798314',
 'cg18346506',
 'cg03363289',
 'cg03430065',
 'cg16961923',
 'cg14379000',
 'cg25221180',
 'cg04294438',
 'cg01591573',
 'cg01595178',
 'cg04454629',
 'cg09067993',
 'cg08234376',
 'cg16527105',
 'cg25052156',
 'cg14846874',
 'cg14904946',
 'cg20467217',
 'cg04839741',
 'cg14019859',
 'cg24882168',
 'cg02255808',
 'cg05225889',
 'cg03046482',
 'cg07214562',
 'cg15512879',
 'cg20498994',
 'cg20544479',
 'cg26451856',
 'cg09629758',
 'cg18466312',
 'cg12046064',
 'cg14921999',
 'cg05170020',
 'cg15044146',
 'cg03647307',
 'cg04453629',
 'cg06667758',
 'cg18148620',
 'cg20668001',
 'cg25448407',
 'cg07811074',
 'cg00178122',
 'cg08165340',
 'cg04755386',
 'cg18429374',
 'cg22985281',
 'cg25071794',
 'cg11139599',
 'cg14186321',
 'cg05997278',
 'cg04022560',
 'cg04098985',
 'cg11238518',
 'cg09125286',
 'cg22768676',
 'cg06148784',
 'cg00353407',
 'cg08786822',
 'cg04634182',
 'cg26828494',
 'cg19307391',
 'cg10607557',
 'cg13041470',
 'cg27311590',
 'cg23673397',
 'cg15882726',
 'cg03889251',
 'cg01291129',
 'cg02257700',
 'cg06848468',
 'cg11217934',
 'cg22814916',
 'cg02443816',
 'cg01101677',
 'cg00605523',
 'cg25350722',
 'cg01022189',
 'cg03959147',
 'cg27585147',
 'cg09811599',
 'cg23671626',
 'cg19455292',
 'cg13402298',
 'cg11398309',
 'cg22159109',
 'cg18575452',
 'cg10507762',
 'cg15004787',
 'cg00389619',
 'cg10156706',
 'cg21445764',
 'cg21331845',
 'cg11081809',
 'cg04636251',
 'cg01765322',
 'cg00998735',
 'cg21908960',
 'cg10362527',
 'cg02105087',
 'cg27292870',
 'cg10174575',
 'cg23659308',
 'cg06870484',
 'cg21475003',
 'cg26319363',
 'cg26308992',
 'cg10089413',
 'cg10506618',
 'cg02033040',
 'cg11655389',
 'cg11380092',
 'cg00554858',
 'cg07166795',
 'cg24429037',
 'cg23946548',
 'cg03446399',
 'cg05777410',
 'cg09060784',
 'cg14862385',
 'cg13647486',
 'cg13691824',
 'cg07278174',
 'cg11371162',
 'cg11430766',
 'cg08010337',
 'cg08295072',
 'cg00097088',
 'cg00019826',
 'cg03521085',
 'cg06665095',
 'cg08370506',
 'cg04348561',
 'cg01421044',
 'cg18677812',
 'cg19530800',
 'cg21958394',
 'cg05672616',
 'cg05652528',
 'cg24673955',
 'cg19270089',
 'cg16057532',
 'cg08548315',
 'cg21972741',
 'cg27511630',
 'cg00178877',
 'cg00119241',
 'cg00152878',
 'cg02154531',
 'cg19729188',
 'cg17416233',
 'cg01114138',
 'cg19079233',
 'cg07418777',
 'cg26835568',
 'cg00610205',
 'cg02032984',
 'cg21513803',
 'cg03920522',
 'cg22394948',
 'cg08258915',
 'cg03722185',
 'cg16819768',
 'cg07180897',
 'cg14412639',
 'cg15676292',
 'cg11514604',
 'cg25315991',
 'cg04086327',
 'cg16667459',
 'cg18762825',
 'cg07290269',
 'cg13676726',
 'cg05369766',
 'cg10482532',
 'cg21083936',
 'cg08621168',
 'cg02918166',
 'cg04225508',
 'cg25548350',
 'cg23932711',
 'cg22690322',
 'cg05032595',
 'cg04306248',
 'cg26496920',
 'cg24849475',
 'cg07068181',
 'cg10221654',
 'cg14136372',
 'cg19992785',
 'cg06891613',
 'cg21440284',
 'cg01409873',
 'cg10494638',
 'cg02172885',
 'cg03812751',
 'cg01904886',
 'cg13209192',
 'cg18671115',
 'cg05134857',
 'cg03065803',
 'cg06669598',
 'cg20347648',
 'cg10390762',
 'cg12955305',
 'cg20093020',
 'cg14233716',
 'cg05188488',
 'cg09179397',
 'cg19436700',
 'cg07454788',
 'cg08604594',
 'cg06728077',
 'cg03220363',
 'cg27135936',
 'cg11930274',
 'cg21178568',
 'cg13468804',
 'cg22562569',
 'cg00315816',
 'cg25511725',
 'cg08272591',
 'cg04426607',
 'cg03849834',
 'cg12294678',
 'cg06145508',
 'cg07420867',
 'cg08112356',
 'cg26014281',
 'cg01145442',
 'cg10596483',
 'cg19098690',
 'cg14415857',
 'cg27229586',
 'cg09005399',
 'cg14528451',
 'cg13486404',
 'cg09077672',
 'cg25687777',
 'cg15476885',
 'cg22236485',
 'cg14715383',
 'cg07005960',
 'cg09869811',
 'cg13689497',
 'cg02513556',
 'cg25824218',
 'cg18290190',
 'cg18098534',
 'cg14354881',
 'cg10226073',
 'cg14647989',
 'cg16989086',
 'cg10476347',
 'cg13124801',
 'cg10273072',
 'cg10293824',
 'cg11140875',
 'cg25388939',
 'cg07141545',
 'cg00781839',
 'cg13990980',
 'cg16668397',
 'cg02341645',
 'cg07092293',
 'cg06661612',
 'cg02719221',
 'cg01096587',
 'cg18691133',
 'cg05135033',
 'cg05444556',
 'cg03381007',
 'cg00151170',
 'cg18998002',
 'cg05726756',
 'cg02311180',
 'cg10284310',
 'cg19874095',
 'cg22615910',
 'cg00128718',
 'cg10064312',
 'cg11666515',
 'cg26933384',
 'cg25271770',
 'cg11881861',
 'cg12582555',
 'cg25357666',
 'cg25524108',
 'cg17199181',
 'cg02391633',
 'cg04461311',
 'cg22825473',
 'cg00855396',
 'cg26175287',
 'cg10943931',
 'cg04395006',
 'cg07876611',
 'cg18048953',
 'cg27018309',
 'cg27075786',
 'cg24943736',
 'cg21013395',
 'cg09743906',
 'cg22696944',
 'cg08628428',
 'cg17860133',
 'cg26256771',
 'cg19366479',
 'cg19037241',
 'cg20045696',
 'cg16887110',
 'cg01525839',
 'cg19899561',
 'cg23467628',
 'cg18284050',
 'cg24190979',
 'cg18047214',
 'cg05207870',
 'cg10980860',
 'cg05222618',
 'cg15251217',
 'cg23554922',
 'cg16598774',
 'cg09891332',
 'cg19104037',
 'cg25610945',
 'cg13577755',
 'cg26584465',
 'cg23076547',
 'cg01363387',
 'cg20186982',
 'cg15684003',
 'cg08879722',
 'cg24224638',
 'cg20082916',
 'cg03947687',
 'cg20020625',
 'cg21329470',
 'cg23583501',
 'cg23670702',
 'cg22729091',
 'cg08977827',
 'cg04897744',
 'cg25984203',
 'cg03838944',
 'cg20059427',
 'cg10984515',
 'cg12039910',
 'cg16361921',
 'cg09184537',
 'cg04631440',
 'cg07160992',
 'cg02756136',
 'cg25486412',
 'cg21294295',
 'cg24676276',
 'cg23568161',
 'cg05853394',
 'cg23042158',
 'cg00005249',
 'cg03860010',
 'cg18602829',
 'cg01705981',
 'cg10508018',
 'cg27418891',
 'cg23366754',
 'cg10694456',
 'cg07526131',
 'cg14606439',
 'cg09251548',
 'cg08286630',
 'cg27249778',
 'cg00879723',
 'cg00308904',
 'cg14614789',
 'cg22878634',
 'cg22408844',
 'cg25002963',
 'cg22704163',
 'cg13758111',
 'cg01053354',
 'cg06993367',
 'cg08024468',
 'cg10936998',
 'cg12365675',
 'cg22998472',
 'cg12334758',
 'cg24116081',
 'cg11571098',
 'cg23202853',
 'cg07374666',
 'cg18702850',
 'cg22664564',
 'cg21200055',
 'cg22711847',
 'cg10081084',
 'cg22281761',
 'cg11627090',
 'cg22640553',
 'cg09007881',
 'cg22223109',
 'cg18809403',
 'cg05400446',
 'cg24819596',
 'cg09214323',
 'cg01003893',
 'cg09208012',
 'cg01920890',
 'cg14476057',
 'cg04345744',
 'cg11722504',
 'cg05330301',
 'cg11240813',
 'cg15997319',
 'cg08679702',
 'cg14596477',
 'cg25558228',
 'cg11853350',
 'cg17539777',
 'cg09684899',
 'cg25913970',
 'cg09409594',
 'cg04067970',
 'cg26430004',
 'cg05003619',
 'cg12080266',
 'cg07195891',
 'cg05642964',
 'cg06725641',
 'cg06937654',
 'cg19227294',
 'cg10651174',
 'cg15648058',
 'cg11654142',
 'cg13278328',
 'cg14475362',
 'cg06578230',
 'cg10154189',
 'cg03816966',
 'cg19316074',
 'cg20569482',
 'cg22891632',
 'cg15124400',
 'cg12304447',
 'cg21015078',
 'cg20055392',
 'cg02969609',
 'cg09422970',
 'cg26801741',
 'cg03412823',
 'cg05004137',
 'cg25665103',
 'cg23102351',
 'cg06698547',
 'cg11877490',
 'cg23411027',
 'cg26269565',
 'cg24517995',
 'cg21785376',
 'cg07725712',
 'cg18390724',
 'cg25182828',
 'cg19121956',
 'cg25447813',
 'cg17947181',
 'cg01672655',
 'cg26054541',
 'cg16263148',
 'cg06059109',
 'cg03252488',
 'cg23114830',
 'cg11691705',
 'cg05780479',
 'cg22771850',
 'cg27400458',
 'cg04921708',
 'cg21063107',
 'cg00629612',
 'cg22750284',
 'cg21863379',
 'cg13643885',
 'cg17171826',
 'cg05041591',
 'cg06853088',
 'cg20296174',
 'cg15124946',
 'cg22312534',
 'cg01392238',
 'cg22306690',
 'cg23071707',
 'cg00038681',
 'cg23024108',
 'cg24214626',
 'cg19799745',
 'cg17769356',
 'cg08986950',
 'cg02054390',
 'cg02053175',
 'cg00982543',
 'cg10870282',
 'cg19613533',
 'cg09659380',
 'cg24690092',
 'cg13529673',
 'cg02970458',
 'cg03063030',
 'cg17764313',
 'cg10436837',
 ...]

In [63]:
methylome_data = pd.DataFrame({
    'sample': sample_list,
    'group': group_list,
    'feature': feature_list,
    'value': value_list
})

methylome_data      # 1475 * 75 = 110625

                     sample    group     feature    value
0       A09_072_C9a_group_1  group_1  cg25625370   0.0289
1       A09_072_C9a_group_1  group_1  cg25980689  0.02582
2       A09_072_C9a_group_1  group_1  cg00767000   0.0371
3       A09_072_C9a_group_1  group_1  cg15212418  0.06619
4       A09_072_C9a_group_1  group_1  cg19515398    0.069
...                     ...      ...         ...      ...
110620        GA109_group_5  group_5   rs6426327  0.86909
110621        GA109_group_5  group_5   rs7660805  0.99237
110622        GA109_group_5  group_5   rs9363764  0.04043
110623        GA109_group_5  group_5    rs348937  0.05844
110624        GA109_group_5  group_5   rs7746156  0.07593

[110625 rows x 4 columns]

In [65]:
methylome_data.to_csv("./methylome_first_mofa_norm_data.csv")

In [ ]:
# Add view
metabolome_data.insert(3, 'view', 'metabolome')
proteome_data.insert(3, 'view', 'proteome')
methylome_data.insert(3, 'view', 'methylome')

In [71]:
metabolome_data.to_csv("./metabolome_first_mofa_data.csv")
proteome_data.to_csv("./proteome_first_mofa_data.csv")
methylome_data.to_csv("./methylome_first_mofa_data.csv")

In [73]:
# feature update
metabolome_data['feature'] = metabolome_data['feature'] + '_' + metabolome_data['view']
metabolome_data

,sample,group,feature,view,value
0,A09_072_C9a_group_1,group_1,met1_metabolome,metabolome,21.52666958
1,A09_072_C9a_group_1,group_1,met2_metabolome,metabolome,15.4262445
2,A09_072_C9a_group_1,group_1,met4_metabolome,metabolome,24.54412998
3,A09_072_C9a_group_1,group_1,met5_metabolome,metabolome,17.04468563
4,A09_072_C9a_group_1,group_1,met6_metabolome,metabolome,17.04468563
...,...,...,...,...,...
67675,GA109_group_5,group_5,met1140_metabolome,metabolome,18.54742415
67676,GA109_group_5,group_5,met1141_metabolome,metabolome,20.25203377
67677,GA109_group_5,group_5,met1142_metabolome,metabolome,15.93440421
67678,GA109_group_5,group_5,met1143_metabolome,metabolome,17.96260375
67679,GA109_group_5,group_5,met1144_metabolome,metabolome,15.07380411

In [75]:
proteome_data['feature'] = proteome_data['feature'] + '_' + proteome_data['view']
proteome_data

,sample,group,feature,view,value
0,A09_072_C9a_group_1,group_1,P05154_proteome,proteome,10.57039353
1,A09_072_C9a_group_1,group_1,P02786_proteome,proteome,5.976345511
2,A09_072_C9a_group_1,group_1,Q9Y490_proteome,proteome,4.38103767
3,A09_072_C9a_group_1,group_1,Q15063-5_proteome,proteome,4.650894142
4,A09_072_C9a_group_1,group_1,P02730_proteome,proteome,5.034665667
...,...,...,...,...,...
66315,GA109_group_5,group_5,P52701;P52701-3;P52701-4_proteome,proteome,6.674220521
66316,GA109_group_5,group_5,Q9C0G6_proteome,proteome,2.441031903
66317,GA109_group_5,group_5,Q9Y5R5_proteome,proteome,11.06743145
66318,GA109_group_5,group_5,Q01581_proteome,proteome,11.06743145
66319,GA109_group_5,group_5,P01814_proteome,proteome,5.274183373

In [77]:
methylome_data['feature'] = methylome_data['feature'] + '_' + methylome_data['view']
methylome_data

                     sample    group               feature       view    value
0       A09_072_C9a_group_1  group_1  cg25625370_methylome  methylome   0.0289
1       A09_072_C9a_group_1  group_1  cg25980689_methylome  methylome  0.02582
2       A09_072_C9a_group_1  group_1  cg00767000_methylome  methylome   0.0371
3       A09_072_C9a_group_1  group_1  cg15212418_methylome  methylome  0.06619
4       A09_072_C9a_group_1  group_1  cg19515398_methylome  methylome    0.069
...                     ...      ...                   ...        ...      ...
110620        GA109_group_5  group_5   rs6426327_methylome  methylome  0.86909
110621        GA109_group_5  group_5   rs7660805_methylome  methylome  0.99237
110622        GA109_group_5  group_5   rs9363764_methylome  methylome  0.04043
110623        GA109_group_5  group_5    rs348937_methylome  methylome  0.05844
110624        GA109_group_5  group_5   rs7746156_methylome  methylome  0.07593

[110625 rows x 5 columns]

In [79]:
omics1 = pd.concat([proteome_data, metabolome_data])
omics2 = pd.concat([omics1, methylome_data])
omics2

,sample,group,feature,view,value
0,A09_072_C9a_group_1,group_1,P05154_proteome,proteome,10.57039353
1,A09_072_C9a_group_1,group_1,P02786_proteome,proteome,5.976345511
2,A09_072_C9a_group_1,group_1,Q9Y490_proteome,proteome,4.38103767
3,A09_072_C9a_group_1,group_1,Q15063-5_proteome,proteome,4.650894142
4,A09_072_C9a_group_1,group_1,P02730_proteome,proteome,5.034665667
...,...,...,...,...,...
110620,GA109_group_5,group_5,rs6426327_methylome,methylome,0.86909
110621,GA109_group_5,group_5,rs7660805_methylome,methylome,0.99237
110622,GA109_group_5,group_5,rs9363764_methylome,methylome,0.04043
110623,GA109_group_5,group_5,rs348937_methylome,methylome,0.05844
110624,GA109_group_5,group_5,rs7746156_methylome,methylome,0.07593

In [81]:
omics2.to_csv("./multiome_first_mofa-data.csv")

In [83]:
# first_data editing
omics = pd.read_csv("./multiome_first_mofa-data.csv", low_memory=False)
omics = pd.DataFrame(omics)
omics

,Unnamed: 0,sample,group,feature,view,value
0,0,A09_072_C9a_group_1,group_1,P05154_proteome,proteome,10.570394
1,1,A09_072_C9a_group_1,group_1,P02786_proteome,proteome,5.976346
2,2,A09_072_C9a_group_1,group_1,Q9Y490_proteome,proteome,4.381038
3,3,A09_072_C9a_group_1,group_1,Q15063-5_proteome,proteome,4.650894
4,4,A09_072_C9a_group_1,group_1,P02730_proteome,proteome,5.034666
...,...,...,...,...,...,...
244620,110620,GA109_group_5,group_5,rs6426327_methylome,methylome,0.869090
244621,110621,GA109_group_5,group_5,rs7660805_methylome,methylome,0.992370
244622,110622,GA109_group_5,group_5,rs9363764_methylome,methylome,0.040430
244623,110623,GA109_group_5,group_5,rs348937_methylome,methylome,0.058440
244624,110624,GA109_group_5,group_5,rs7746156_methylome,methylome,0.075930

In [ ]:
import pandas as pd
import re

omics_comp1 = omics[omics['group'] != 'group_1'].copy()
omics_comp1

,Unnamed: 0,sample,group,feature,view,value
8290,8290,A23_group_2,group_2,P05154_proteome,proteome,10.535671
8291,8291,A23_group_2,group_2,P02786_proteome,proteome,6.165555
8292,8292,A23_group_2,group_2,Q9Y490_proteome,proteome,4.497359
8293,8293,A23_group_2,group_2,Q15063-5_proteome,proteome,4.313883
8294,8294,A23_group_2,group_2,P02730_proteome,proteome,5.253890
...,...,...,...,...,...,...
244620,110620,GA109_group_5,group_5,rs6426327_methylome,methylome,0.869090
244621,110621,GA109_group_5,group_5,rs7660805_methylome,methylome,0.992370
244622,110622,GA109_group_5,group_5,rs9363764_methylome,methylome,0.040430
244623,110623,GA109_group_5,group_5,rs348937_methylome,methylome,0.058440
244624,110624,GA109_group_5,group_5,rs7746156_methylome,methylome,0.075930

In [ ]:
omics_comp1.loc[:, 'group'] = omics_comp1['group'].replace({
    'group_2': 'group_1',
    'group_3': 'group_2',
    'group_4': 'group_2',
    'group_5': 'group_3'
})

omics_comp1

,Unnamed: 0,sample,group,feature,view,value
8290,8290,A23_group_2,group_1,P05154_proteome,proteome,10.535671
8291,8291,A23_group_2,group_1,P02786_proteome,proteome,6.165555
8292,8292,A23_group_2,group_1,Q9Y490_proteome,proteome,4.497359
8293,8293,A23_group_2,group_1,Q15063-5_proteome,proteome,4.313883
8294,8294,A23_group_2,group_1,P02730_proteome,proteome,5.253890
...,...,...,...,...,...,...
244620,110620,GA109_group_5,group_3,rs6426327_methylome,methylome,0.869090
244621,110621,GA109_group_5,group_3,rs7660805_methylome,methylome,0.992370
244622,110622,GA109_group_5,group_3,rs9363764_methylome,methylome,0.040430
244623,110623,GA109_group_5,group_3,rs348937_methylome,methylome,0.058440
244624,110624,GA109_group_5,group_3,rs7746156_methylome,methylome,0.075930

In [ ]:
# Change group information of sample column - using regular expression
def update_sample(sample_name):
    match = re.search(r'_group_(\d+)', sample_name)
    if match:
        group_number = int(match.group(1))
        if group_number == 2:
            new_group_number = 1
        elif group_number in [3, 4]:
            new_group_number = 2
        elif group_number == 5:
            new_group_number = 3
        else:
            return sample_name
        return re.sub(r'_group_\d+', f'_group_{new_group_number}', sample_name)
    return sample_name

omics_comp1.loc[:, 'sample'] = omics_comp1['sample'].apply(update_sample)

print(omics_comp1)

        Unnamed: 0         sample    group              feature       view  \
8290          8290    A23_group_1  group_1      P05154_proteome   proteome
8291          8291    A23_group_1  group_1      P02786_proteome   proteome
8292          8292    A23_group_1  group_1      Q9Y490_proteome   proteome
8293          8293    A23_group_1  group_1    Q15063-5_proteome   proteome
8294          8294    A23_group_1  group_1      P02730_proteome   proteome
...            ...            ...      ...                  ...        ...
244620      110620  GA109_group_3  group_3  rs6426327_methylome  methylome
244621      110621  GA109_group_3  group_3  rs7660805_methylome  methylome
244622      110622  GA109_group_3  group_3  rs9363764_methylome  methylome
244623      110623  GA109_group_3  group_3   rs348937_methylome  methylome
244624      110624  GA109_group_3  group_3  rs7746156_methylome  methylome

            value
8290    10.535671
8291     6.165555
8292     4.497359
8293     4.313883
8294     5.253890
...           ...
244620   0.869090
244621   0.992370
244622   0.040430
244623   0.058440
244624   0.075930

[206545 rows x 6 columns]

In [91]:
omics_comp1 = omics_comp1.drop(columns=['Unnamed: 0'])
omics_comp1.index = range(1, len(omics_comp1)+1)

print(omics_comp1)

               sample    group              feature       view      value
1         A23_group_1  group_1      P05154_proteome   proteome  10.535671
2         A23_group_1  group_1      P02786_proteome   proteome   6.165555
3         A23_group_1  group_1      Q9Y490_proteome   proteome   4.497359
4         A23_group_1  group_1    Q15063-5_proteome   proteome   4.313883
5         A23_group_1  group_1      P02730_proteome   proteome   5.253890
...               ...      ...                  ...        ...        ...
206541  GA109_group_3  group_3  rs6426327_methylome  methylome   0.869090
206542  GA109_group_3  group_3  rs7660805_methylome  methylome   0.992370
206543  GA109_group_3  group_3  rs9363764_methylome  methylome   0.040430
206544  GA109_group_3  group_3   rs348937_methylome  methylome   0.058440
206545  GA109_group_3  group_3  rs7746156_methylome  methylome   0.075930

[206545 rows x 5 columns]

In [93]:
omics_comp1.to_csv("./multiome_first_comp1_data.csv")

In [ ]:
# comp2 (vs 2 groups)
import re
# exclude group_1 (unexposed normal), group_5 (severe lung injury) data
omics_comp2 = omics[~omics['group'].isin(['group_1', 'group_5'])].copy()

omics_comp2

,Unnamed: 0,sample,group,feature,view,value
8290,8290,A23_group_2,group_2,P05154_proteome,proteome,10.535671
8291,8291,A23_group_2,group_2,P02786_proteome,proteome,6.165555
8292,8292,A23_group_2,group_2,Q9Y490_proteome,proteome,4.497359
8293,8293,A23_group_2,group_2,Q15063-5_proteome,proteome,4.313883
8294,8294,A23_group_2,group_2,P02730_proteome,proteome,5.253890
...,...,...,...,...,...,...
229870,95870,GA505_group_4,group_4,rs6426327_methylome,methylome,0.746190
229871,95871,GA505_group_4,group_4,rs7660805_methylome,methylome,0.028610
229872,95872,GA505_group_4,group_4,rs9363764_methylome,methylome,1.012140
229873,95873,GA505_group_4,group_4,rs348937_methylome,methylome,1.173250
229874,95874,GA505_group_4,group_4,rs7746156_methylome,methylome,0.054600

In [ ]:
omics_comp2.loc[:, 'group'] = omics_comp2['group'].replace({
    'group_2': 'group_1',
    'group_3': 'group_2',
    'group_4': 'group_2',
})

omics_comp2

,Unnamed: 0,sample,group,feature,view,value
8290,8290,A23_group_2,group_1,P05154_proteome,proteome,10.535671
8291,8291,A23_group_2,group_1,P02786_proteome,proteome,6.165555
8292,8292,A23_group_2,group_1,Q9Y490_proteome,proteome,4.497359
8293,8293,A23_group_2,group_1,Q15063-5_proteome,proteome,4.313883
8294,8294,A23_group_2,group_1,P02730_proteome,proteome,5.253890
...,...,...,...,...,...,...
229870,95870,GA505_group_4,group_2,rs6426327_methylome,methylome,0.746190
229871,95871,GA505_group_4,group_2,rs7660805_methylome,methylome,0.028610
229872,95872,GA505_group_4,group_2,rs9363764_methylome,methylome,1.012140
229873,95873,GA505_group_4,group_2,rs348937_methylome,methylome,1.173250
229874,95874,GA505_group_4,group_2,rs7746156_methylome,methylome,0.054600

In [ ]:
# Change group information of sample column - using regular expression
def update_sample(sample_name):
    match = re.search(r'_group_(\d+)', sample_name)
    if match:
        group_number = int(match.group(1))
        if group_number == 2:
            new_group_number = 1
        elif group_number in [3, 4]:
            new_group_number = 2
        else:
            return sample_name
        return re.sub(r'_group_\d+', f'_group_{new_group_number}', sample_name)
    return sample_name

omics_comp2.loc[:, 'sample'] = omics_comp2['sample'].apply(update_sample)

print(omics_comp2)

        Unnamed: 0         sample    group              feature       view  \
8290          8290    A23_group_1  group_1      P05154_proteome   proteome
8291          8291    A23_group_1  group_1      P02786_proteome   proteome
8292          8292    A23_group_1  group_1      Q9Y490_proteome   proteome
8293          8293    A23_group_1  group_1    Q15063-5_proteome   proteome
8294          8294    A23_group_1  group_1      P02730_proteome   proteome
...            ...            ...      ...                  ...        ...
229870       95870  GA505_group_2  group_2  rs6426327_methylome  methylome
229871       95871  GA505_group_2  group_2  rs7660805_methylome  methylome
229872       95872  GA505_group_2  group_2  rs9363764_methylome  methylome
229873       95873  GA505_group_2  group_2   rs348937_methylome  methylome
229874       95874  GA505_group_2  group_2  rs7746156_methylome  methylome

            value
8290    10.535671
8291     6.165555
8292     4.497359
8293     4.313883
8294     5.253890
...           ...
229870   0.746190
229871   0.028610
229872   1.012140
229873   1.173250
229874   0.054600

[175985 rows x 6 columns]

In [101]:
omics_comp2 = omics_comp2.drop(columns=['Unnamed: 0'])
omics_comp2.index = range(1, len(omics_comp2)+1)

print(omics_comp2)

               sample    group              feature       view      value
1         A23_group_1  group_1      P05154_proteome   proteome  10.535671
2         A23_group_1  group_1      P02786_proteome   proteome   6.165555
3         A23_group_1  group_1      Q9Y490_proteome   proteome   4.497359
4         A23_group_1  group_1    Q15063-5_proteome   proteome   4.313883
5         A23_group_1  group_1      P02730_proteome   proteome   5.253890
...               ...      ...                  ...        ...        ...
175981  GA505_group_2  group_2  rs6426327_methylome  methylome   0.746190
175982  GA505_group_2  group_2  rs7660805_methylome  methylome   0.028610
175983  GA505_group_2  group_2  rs9363764_methylome  methylome   1.012140
175984  GA505_group_2  group_2   rs348937_methylome  methylome   1.173250
175985  GA505_group_2  group_2  rs7746156_methylome  methylome   0.054600

[175985 rows x 5 columns]

In [103]:
omics_comp2.to_csv("./multiome_first_comp2_data.csv")

In [105]:
omics_comp3 = omics_comp2[omics_comp2['group'] != 'group_1'].copy()
omics_comp3

               sample    group              feature       view      value
16581     A18_group_2  group_2      P05154_proteome   proteome  11.145261
16582     A18_group_2  group_2      P02786_proteome   proteome   5.873615
16583     A18_group_2  group_2      Q9Y490_proteome   proteome   4.618975
16584     A18_group_2  group_2    Q15063-5_proteome   proteome   4.218690
16585     A18_group_2  group_2      P02730_proteome   proteome   5.105826
...               ...      ...                  ...        ...        ...
175981  GA505_group_2  group_2  rs6426327_methylome  methylome   0.746190
175982  GA505_group_2  group_2  rs7660805_methylome  methylome   0.028610
175983  GA505_group_2  group_2  rs9363764_methylome  methylome   1.012140
175984  GA505_group_2  group_2   rs348937_methylome  methylome   1.173250
175985  GA505_group_2  group_2  rs7746156_methylome  methylome   0.054600

[117815 rows x 5 columns]

In [ ]:
omics_comp3.loc[:, 'group'] = omics_comp3['group'].replace({'group_2': 'group_1'})

# Change group information of sample column - using regular expression
import re

def update_sample(sample_name):
    match = re.search(r'_group_(\d+)', sample_name)
    if match:
        group_number = int(match.group(1))
        if group_number == 2:
            new_group_number = 1
        else:
            return sample_name
        return re.sub(r'_group_\d+', f'_group_{new_group_number}', sample_name)
    return sample_name

omics_comp3.loc[:, 'sample'] = omics_comp3['sample'].apply(update_sample)

print(omics_comp3)

               sample    group              feature       view      value
16581     A18_group_1  group_1      P05154_proteome   proteome  11.145261
16582     A18_group_1  group_1      P02786_proteome   proteome   5.873615
16583     A18_group_1  group_1      Q9Y490_proteome   proteome   4.618975
16584     A18_group_1  group_1    Q15063-5_proteome   proteome   4.218690
16585     A18_group_1  group_1      P02730_proteome   proteome   5.105826
...               ...      ...                  ...        ...        ...
175981  GA505_group_1  group_1  rs6426327_methylome  methylome   0.746190
175982  GA505_group_1  group_1  rs7660805_methylome  methylome   0.028610
175983  GA505_group_1  group_1  rs9363764_methylome  methylome   1.012140
175984  GA505_group_1  group_1   rs348937_methylome  methylome   1.173250
175985  GA505_group_1  group_1  rs7746156_methylome  methylome   0.054600

[117815 rows x 5 columns]

In [109]:
omics_comp3.index = range(1, len(omics_comp3)+1)
print(omics_comp3)

               sample    group              feature       view      value
1         A18_group_1  group_1      P05154_proteome   proteome  11.145261
2         A18_group_1  group_1      P02786_proteome   proteome   5.873615
3         A18_group_1  group_1      Q9Y490_proteome   proteome   4.618975
4         A18_group_1  group_1    Q15063-5_proteome   proteome   4.218690
5         A18_group_1  group_1      P02730_proteome   proteome   5.105826
...               ...      ...                  ...        ...        ...
117811  GA505_group_1  group_1  rs6426327_methylome  methylome   0.746190
117812  GA505_group_1  group_1  rs7660805_methylome  methylome   0.028610
117813  GA505_group_1  group_1  rs9363764_methylome  methylome   1.012140
117814  GA505_group_1  group_1   rs348937_methylome  methylome   1.173250
117815  GA505_group_1  group_1  rs7746156_methylome  methylome   0.054600

[117815 rows x 5 columns]

In [111]:
omics_comp3.to_csv("multiome_first_comp3_data.csv")